In [1]:
# load the SQL magic extension
# https://github.com/catherinedevlin/ipython-sql
# this extension allows us to connect to DBs and issue SQL command
%load_ext sql

In [2]:
# now we can use the magic extension to connect to our SQLite DB
# use %sql to write an inline SQL command
# use %%sql to write SQL commands in a cell
%sql sqlite:///NewDB.sqlite3

In [3]:
%%sql
CREATE TABLE employee (
    Employee_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL,
    Age INTEGER NOT NULL,
    Address TEXT,
    Salary REAL NOT NULL,
    Position TEXT,
    Department TEXT,
    Date_of_Joining DATE,
    Experience_Years INTEGER,
    Number_of_Leaves INTEGER,
    Performance_Rating REAL,
    Employee_Satisfaction REAL,
    Number_of_Promotions INTEGER,
    Number_of_Projects_Working INTEGER
);

 * sqlite:///NewDB.sqlite3
(sqlite3.OperationalError) table employee already exists
[SQL: CREATE TABLE employee (
    Employee_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL,
    Age INTEGER NOT NULL,
    Address TEXT,
    Salary REAL NOT NULL,
    Position TEXT,
    Department TEXT,
    Date_of_Joining DATE,
    Experience_Years INTEGER,
    Number_of_Leaves INTEGER,
    Performance_Rating REAL,
    Employee_Satisfaction REAL,
    Number_of_Promotions INTEGER,
    Number_of_Projects_Working INTEGER
);]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

Employee_ID:

    Description: A unique identifier for each employee.
    Data Type: INTEGER
    Constraints: PRIMARY KEY, AUTOINCREMENT
    Details: Automatically increments with each new record, ensuring uniqueness.

Name:

    Description: The full name of the employee.
    Data Type: TEXT
    Constraints: NOT NULL
    Details: Required field; should contain the employee's name.

Age:

    Description: The age of the employee.
    Data Type: INTEGER
    Constraints: NOT NULL
    Details: Required field; should contain the employee's age.

Address:

    Description: The residential address of the employee.
    Data Type: TEXT
    Constraints: None
    Details: Optional field; can contain the full address of the employee.

Salary:

    Description: The monthly or annual salary of the employee.
    Data Type: REAL
    Constraints: NOT NULL
    Details: Required field; should reflect the employee's salary.

Position:

    Description: The job title or role of the employee within the company.
    Data Type: TEXT
    Constraints: None
    Details: Optional field; should contain the employee's job title.

Department:

    Description: The department in which the employee works.
    Data Type: TEXT
    Constraints: None
    Details: Optional field; should reflect the department name.

Date_of_Joining:

    Description: The date when the employee joined the company.
    Data Type: DATE
    Constraints: None
    Details: Optional field; should be in a date format (YYYY-MM-DD).

Experience_Years:

    Description: The number of years of experience the employee has.
    Data Type: INTEGER
    Constraints: None
    Details: Optional field; should indicate the total years of experience.

Number_of_Leaves:

    Description: The total number of leaves taken by the employee.
    Data Type: INTEGER
    Constraints: None
    Details: Optional field; should reflect the number of leave days.

Performance_Rating:

    Description: A rating of the employee's performance.
    Data Type: REAL
    Constraints: None
    Details: Optional field; can be a numerical value representing performance.

Employee_Satisfaction:

    Description: The level of satisfaction the employee has with their job.
    Data Type: REAL
    Constraints: None
    Details: Optional field; can be a numerical value or percentage indicating satisfaction.

Number_of_Promotions:

    Description: The number of promotions the employee has received.
    Data Type: INTEGER
    Constraints: None
    Details: Optional field; should reflect the total number of promotions.

Number_of_Projects_Working:

    Description: The number of projects the employee is currently working on.
    Data Type: INTEGER
    Constraints: None
    Details: Optional field; should indicate the number of active projects.

In [4]:
''' INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working) VALUES
('John Doe', 28, '123 Elm St', 55000.00, 'Software Engineer', 'IT', '2020-01-15', 4, 5, 4.5, 4.7, 2, 5),
('Jane Smith', 34, '456 Oak St', 60000.00, 'Senior Developer', 'IT', '2018-03-22', 6, 3, 4.8, 4.9, 3, 7),
('Michael Johnson', 25, '789 Pine St', 52000.00, 'Junior Developer', 'IT', '2021-06-10', 2, 7, 4.2, 4.5, 1, 4),
('Emily Davis', 29, '101 Maple St', 58000.00, 'Project Manager', 'HR', '2019-09-05', 5, 4, 4.6, 4.8, 2, 6),
('William Brown', 40, '202 Birch St', 75000.00, 'Team Lead', 'Finance', '2015-12-20', 9, 2, 4.9, 4.6, 4, 8),
('Olivia Wilson', 32, '303 Cedar St', 62000.00, 'Business Analyst', 'Finance', '2018-08-14', 7, 3, 4.7, 4.7, 2, 5),
('James Moore', 26, '404 Spruce St', 53000.00, 'Software Engineer', 'IT', '2020-11-30', 3, 6, 4.3, 4.6, 1, 3),
('Sophia Taylor', 31, '505 Fir St', 59000.00, 'QA Engineer', 'IT', '2019-05-23', 6, 4, 4.5, 4.4, 2, 5),
('Daniel Anderson', 27, '606 Cherry St', 56000.00, 'Data Scientist', 'IT', '2021-04-12', 3, 7, 4.4, 4.7, 1, 4),
('Ava Thomas', 33, '707 Walnut St', 64000.00, 'HR Manager', 'HR', '2017-10-01', 8, 2, 4.6, 4.8, 3, 7),
('Lucas Martinez', 35, '808 Ash St', 65000.00, 'Product Manager', 'Marketing', '2016-07-19', 8, 3, 4.7, 4.5, 4, 6),
('Mia Robinson', 30, '909 Elm St', 57000.00, 'Software Engineer', 'IT', '2020-02-29', 4, 5, 4.2, 4.6, 2, 5),
('Ethan Clark', 28, '1010 Oak St', 54000.00, 'Junior Developer', 'IT', '2021-01-15', 3, 6, 4.3, 4.4, 1, 3),
('Isabella Lewis', 27, '1111 Pine St', 53000.00, 'Technical Writer', 'IT', '2020-11-05', 3, 4, 4.2, 4.5, 1, 4),
('Liam Lee', 26, '1212 Maple St', 50000.00, 'Software Engineer', 'IT', '2021-09-23', 2, 8, 4.1, 4.2, 1, 4),
('Charlotte Walker', 29, '1313 Birch St', 57000.00, 'Database Administrator', 'IT', '2019-07-15', 5, 3, 4.6, 4.8, 2, 5),
('Noah Hall', 34, '1414 Cedar St', 60000.00, 'IT Consultant', 'IT', '2018-05-20', 7, 2, 4.7, 4.9, 3, 6),
('Amelia Allen', 31, '1515 Spruce St', 58000.00, 'Project Coordinator', 'HR', '2019-03-10', 5, 5, 4.5, 4.6, 2, 4),
('Mason Young', 36, '1616 Cherry St', 62000.00, 'Business Analyst', 'Finance', '2017-12-25', 8, 4, 4.8, 4.7, 3, 5),
('Avery King', 25, '1717 Walnut St', 52000.00, 'Junior Developer', 'IT', '2021-08-12', 2, 6, 4.1, 4.3, 1, 4),
('Harper Scott', 30, '1818 Ash St', 56000.00, 'Software Engineer', 'IT', '2019-11-18', 5, 3, 4.4, 4.6, 2, 6),
('Elijah Wright', 29, '1919 Elm St', 54000.00, 'System Analyst', 'IT', '2020-02-20', 4, 4, 4.3, 4.5, 1, 4),
('Ella Adams', 32, '2020 Oak St', 59000.00, 'Data Analyst', 'IT', '2018-06-30', 7, 3, 4.6, 4.8, 3, 5),
('Jacob Baker', 27, '2121 Pine St', 53000.00, 'Software Engineer', 'IT', '2021-07-10', 3, 5, 4.4, 4.5, 2, 4),
('Mia Nelson', 34, '2222 Maple St', 60000.00, 'HR Specialist', 'HR', '2016-01-10', 9, 2, 4.7, 4.8, 4, 6),
('James Carter', 31, '2323 Birch St', 58000.00, 'QA Engineer', 'IT', '2018-03-20', 6, 5, 4.5, 4.7, 2, 5),
('Madison Mitchell', 28, '2424 Cedar St', 57000.00, 'Technical Lead', 'IT', '2019-04-15', 5, 3, 4.6, 4.8, 3, 6),
('Benjamin Perez', 30, '2525 Spruce St', 55000.00, 'Product Designer', 'Design', '2019-05-12', 5, 4, 4.4, 4.6, 2, 5),
('Harper Evans', 32, '2626 Cherry St', 59000.00, 'HR Coordinator', 'HR', '2017-10-15', 7, 2, 4.7, 4.7, 3, 6),
('Owen Foster', 33, '2727 Walnut St', 61000.00, 'Business Consultant', 'Finance', '2016-11-25', 8, 4, 4.8, 4.6, 4, 7),
('Ella Murphy', 29, '2828 Ash St', 56000.00, 'IT Support Specialist', 'IT', '2019-08-15', 5, 6, 4.4, 4.5, 2, 4),
('Liam Green', 30, '2929 Elm St', 55000.00, 'Software Developer', 'IT', '2018-12-30', 6, 5, 4.5, 4.6, 2, 6),
('Charlotte Price', 27, '3030 Oak St', 54000.00, 'Systems Engineer', 'IT', '2021-03-20', 3, 7, 4.3, 4.4, 1, 5),
('Noah Bell', 35, '3131 Pine St', 62000.00, 'Data Scientist', 'IT', '2016-05-10', 9, 3, 4.6, 4.8, 3, 6),
('Olivia Roberts', 31, '3232 Maple St', 59000.00, 'Technical Project Manager', 'IT', '2018-11-11', 6, 4, 4.5, 4.7, 2, 5),
('Mason Lewis', 28, '3333 Birch St', 57000.00, 'Software Tester', 'IT', '2020-07-05', 4, 5, 4.4, 4.6, 1, 4),
('Amelia Walker', 26, '3434 Cedar St', 52000.00, 'Junior Data Analyst', 'IT', '2021-02-22', 2, 6, 4.2, 4.3, 1, 4),
('Ethan Scott', 30, '3535 Spruce St', 55000.00, 'Software Architect', 'IT', '2019-01-15', 5, 3, 4.5, 4.6, 2, 6),
('Isabella Rivera', 33, '3636 Cherry St', 58000.00, 'Project Coordinator', 'HR', '2017-09-10', 6, 2, 4.6, 4.7, 3, 5),
('Lucas Thompson', 31, '3737 Walnut St', 60000.00, 'Business Analyst', 'Finance', '2018-04-15', 7, 4, 4.7, 4.8, 2, 6),
('Lily Collins', 32, '3838 Ash St', 57000.00, 'Senior Developer', 'IT', '2019-12-01', 6, 5, 4.5, 4.7, 2, 5),
('Jackson Martinez', 29, '3939 Elm St', 55000.00, 'Software Developer', 'IT', '2020-05-20', 4, 6, 4.4, 4.5, 1, 4),
('Emily Hall', 27, '4040 Oak St', 53000.00, 'Technical Support', 'IT', '2021-08-01', 3, 7, 4.3, 4.4, 1, 4),
('Oliver Allen', 36, '4141 Pine St', 64000.00, 'Software Engineer', 'IT', '2016-03-15', 8, 2, 4.6, 4.7, 3, 6),
('Chloe Carter', 25, '4242 Maple St', 50000.00, 'Junior Developer', 'IT', '2021-06-05', 2, 5, 4.2, 4.3, 1, 4),
('Mia Turner', 28, '4343 Birch St', 54000.00, 'System Analyst', 'IT', '2020-09-20', 3, 6, 4.4, 4.5, 2, 5),
('James Scott', 30, '4444 Cedar St', 57000.00, 'QA Specialist', 'IT', '2019-02-15', 5, 4, 4.5, 4.6, 2, 5),
('Ella Rivera', 31, '4545 Spruce St', 58000.00, 'HR Manager', 'HR', '2018-05-30', 6, 3, 4.6, 4.8, 2, 4),
('Aiden Brooks', 29, '4646 Cherry St', 56000.00, 'Technical Lead', 'IT', '2019-01-20', 4, 5, 4.4, 4.5, 2, 6),
('Grace Reed', 27, '4747 Walnut St', 53000.00, 'Software Engineer', 'IT', '2020-07-10', 3, 6, 4.3, 4.4, 1, 4),
('Benjamin James', 32, '4848 Ash St', 60000.00, 'Product Manager', 'Marketing', '2017-10-20', 7, 3, 4.6, 4.7, 3, 6),
('Avery Foster', 30, '4949 Elm St', 57000.00, 'Software Architect', 'IT', '2018-06-10', 6, 4, 4.5, 4.6, 2, 5),
('Daniel Jenkins', 33, '5050 Oak St', 61000.00, 'Business Consultant', 'Finance', '2016-12-15', 8, 3, 4.7, 4.8, 3, 6),
('Sofia Howard', 31, '5151 Pine St', 58000.00, 'Project Coordinator', 'HR', '2018-07-10', 6, 5, 4.6, 4.8, 2, 5);'''

" INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working) VALUES\n('John Doe', 28, '123 Elm St', 55000.00, 'Software Engineer', 'IT', '2020-01-15', 4, 5, 4.5, 4.7, 2, 5),\n('Jane Smith', 34, '456 Oak St', 60000.00, 'Senior Developer', 'IT', '2018-03-22', 6, 3, 4.8, 4.9, 3, 7),\n('Michael Johnson', 25, '789 Pine St', 52000.00, 'Junior Developer', 'IT', '2021-06-10', 2, 7, 4.2, 4.5, 1, 4),\n('Emily Davis', 29, '101 Maple St', 58000.00, 'Project Manager', 'HR', '2019-09-05', 5, 4, 4.6, 4.8, 2, 6),\n('William Brown', 40, '202 Birch St', 75000.00, 'Team Lead', 'Finance', '2015-12-20', 9, 2, 4.9, 4.6, 4, 8),\n('Olivia Wilson', 32, '303 Cedar St', 62000.00, 'Business Analyst', 'Finance', '2018-08-14', 7, 3, 4.7, 4.7, 2, 5),\n('James Moore', 26, '404 Spruce St', 53000.00, 'Software Engineer', 'IT', '2020-11-30', 3, 6, 4.3, 4.6, 1, 3),\n('Sophia Taylor', 31, '505 Fir St', 59000.00, 'QA Engineer', 'IT', '2019-05-23', 6, 4, 4.5, 4.4, 2, 5),\n('Daniel Anderson', 27, '606 Cherry St', 56000.00, 'Data Scientist', 'IT', '2021-04-12', 3, 7, 4.4, 4.7, 1, 4),\n('Ava Thomas', 33, '707 Walnut St', 64000.00, 'HR Manager', 'HR', '2017-10-01', 8, 2, 4.6, 4.8, 3, 7),\n('Lucas Martinez', 35, '808 Ash St', 65000.00, 'Product Manager', 'Marketing', '2016-07-19', 8, 3, 4.7, 4.5, 4, 6),\n('Mia Robinson', 30, '909 Elm St', 57000.00, 'Software Engineer', 'IT', '2020-02-29', 4, 5, 4.2, 4.6, 2, 5),\n('Ethan Clark', 28, '1010 Oak St', 54000.00, 'Junior Developer', 'IT', '2021-01-15', 3, 6, 4.3, 4.4, 1, 3),\n('Isabella Lewis', 27, '1111 Pine St', 53000.00, 'Technical Writer', 'IT', '2020-11-05', 3, 4, 4.2, 4.5, 1, 4),\n('Liam Lee', 26, '1212 Maple St', 50000.00, 'Software Engineer', 'IT', '2021-09-23', 2, 8, 4.1, 4.2, 1, 4),\n('Charlotte Walker', 29, '1313 Birch St', 57000.00, 'Database Administrator', 'IT', '2019-07-15', 5, 3, 4.6, 4.8, 2, 5),\n('Noah Hall', 34, '1414 Cedar St', 60000.00, 'IT Consultant', 'IT', '2018-05-20', 7, 2, 4.7, 4.9, 3, 6),\n('Amelia Allen', 31, '1515 Spruce St', 58000.00, 'Project Coordinator', 'HR', '2019-03-10', 5, 5, 4.5, 4.6, 2, 4),\n('Mason Young', 36, '1616 Cherry St', 62000.00, 'Business Analyst', 'Finance', '2017-12-25', 8, 4, 4.8, 4.7, 3, 5),\n('Avery King', 25, '1717 Walnut St', 52000.00, 'Junior Developer', 'IT', '2021-08-12', 2, 6, 4.1, 4.3, 1, 4),\n('Harper Scott', 30, '1818 Ash St', 56000.00, 'Software Engineer', 'IT', '2019-11-18', 5, 3, 4.4, 4.6, 2, 6),\n('Elijah Wright', 29, '1919 Elm St', 54000.00, 'System Analyst', 'IT', '2020-02-20', 4, 4, 4.3, 4.5, 1, 4),\n('Ella Adams', 32, '2020 Oak St', 59000.00, 'Data Analyst', 'IT', '2018-06-30', 7, 3, 4.6, 4.8, 3, 5),\n('Jacob Baker', 27, '2121 Pine St', 53000.00, 'Software Engineer', 'IT', '2021-07-10', 3, 5, 4.4, 4.5, 2, 4),\n('Mia Nelson', 34, '2222 Maple St', 60000.00, 'HR Specialist', 'HR', '2016-01-10', 9, 2, 4.7, 4.8, 4, 6),\n('James Carter', 31, '2323 Birch St', 58000.00, 'QA Engineer', 'IT', '2018-03-20', 6, 5, 4.5, 4.7, 2, 5),\n('Madison Mitchell', 28, '2424 Cedar St', 57000.00, 'Technical Lead', 'IT', '2019-04-15', 5, 3, 4.6, 4.8, 3, 6),\n('Benjamin Perez', 30, '2525 Spruce St', 55000.00, 'Product Designer', 'Design', '2019-05-12', 5, 4, 4.4, 4.6, 2, 5),\n('Harper Evans', 32, '2626 Cherry St', 59000.00, 'HR Coordinator', 'HR', '2017-10-15', 7, 2, 4.7, 4.7, 3, 6),\n('Owen Foster', 33, '2727 Walnut St', 61000.00, 'Business Consultant', 'Finance', '2016-11-25', 8, 4, 4.8, 4.6, 4, 7),\n('Ella Murphy', 29, '2828 Ash St', 56000.00, 'IT Support Specialist', 'IT', '2019-08-15', 5, 6, 4.4, 4.5, 2, 4),\n('Liam Green', 30, '2929 Elm St', 55000.00, 'Software Developer', 'IT', '2018-12-30', 6, 5, 4.5, 4.6, 2, 6),\n('Charlotte Price', 27, '3030 Oak St', 54000.00, 'Systems Engineer', 'IT', '2021-03-20', 3, 7, 4.3, 4.4, 1, 5),\n('Noah Bell', 35, '3131 Pine St', 62000.00, 'Data Scientist', 'IT', '2016-05-10', 9, 3, 4.6, 4.8, 3, 6),\n('Olivia Roberts', 31, '3232 Maple St', 59000.00, 'Technical Project Manager', 'IT', '2018-11-11', 6, 4, 4.5, 4.7, 2, 5),\n('Mason Lewis', 28, '3333 Birch St', 57000.00, 'Software Tester', 'IT', '2020-07-05', 4, 5, 4.4, 4.6, 1, 4),\n('Amelia Walker', 26, '3434 Cedar St', 52000.00, 'Junior Data Analyst', 'IT', '2021-02-22', 2, 6, 4.2, 4.3, 1, 4),\n('Ethan Scott', 30, '3535 Spruce St', 55000.00, 'Software Architect', 'IT', '2019-01-15', 5, 3, 4.5, 4.6, 2, 6),\n('Isabella Rivera', 33, '3636 Cherry St', 58000.00, 'Project Coordinator', 'HR', '2017-09-10', 6, 2, 4.6, 4.7, 3, 5),\n('Lucas Thompson', 31, '3737 Walnut St', 60000.00, 'Business Analyst', 'Finance', '2018-04-15', 7, 4, 4.7, 4.8, 2, 6),\n('Lily Collins', 32, '3838 Ash St', 57000.00, 'Senior Developer', 'IT', '2019-12-01', 6, 5, 4.5, 4.7, 2, 5),\n('Jackson Martinez', 29, '3939 Elm St', 55000.00, 'Software Developer', 'IT', '2020-05-20', 4, 6, 4.4, 4.5, 1, 4),\n('Emily Hall', 27, '4040 Oak St', 53000.00, 'Technical Support', 'IT', '2021-08-01', 3, 7, 4.3, 4.4, 1, 4),\n('Oliver Allen', 36, '4141 Pine St', 64000.00, 'Software Engineer', 'IT', '2016-03-15', 8, 2, 4.6, 4.7, 3, 6),\n('Chloe Carter', 25, '4242 Maple St', 50000.00, 'Junior Developer', 'IT', '2021-06-05', 2, 5, 4.2, 4.3, 1, 4),\n('Mia Turner', 28, '4343 Birch St', 54000.00, 'System Analyst', 'IT', '2020-09-20', 3, 6, 4.4, 4.5, 2, 5),\n('James Scott', 30, '4444 Cedar St', 57000.00, 'QA Specialist', 'IT', '2019-02-15', 5, 4, 4.5, 4.6, 2, 5),\n('Ella Rivera', 31, '4545 Spruce St', 58000.00, 'HR Manager', 'HR', '2018-05-30', 6, 3, 4.6, 4.8, 2, 4),\n('Aiden Brooks', 29, '4646 Cherry St', 56000.00, 'Technical Lead', 'IT', '2019-01-20', 4, 5, 4.4, 4.5, 2, 6),\n('Grace Reed', 27, '4747 Walnut St', 53000.00, 'Software Engineer', 'IT', '2020-07-10', 3, 6, 4.3, 4.4, 1, 4),\n('Benjamin James', 32, '4848 Ash St', 60000.00, 'Product Manager', 'Marketing', '2017-10-20', 7, 3, 4.6, 4.7, 3, 6),\n('Avery Foster', 30, '4949 Elm St', 57000.00, 'Software Architect', 'IT', '2018-06-10', 6, 4, 4.5, 4.6, 2, 5),\n('Daniel Jenkins', 33, '5050 Oak St', 61000.00, 'Business Consultant', 'Finance', '2016-12-15', 8, 3, 4.7, 4.8, 3, 6),\n('Sofia Howard', 31, '5151 Pine St', 58000.00, 'Project Coordinator', 'HR', '2018-07-10', 6, 5, 4.6, 4.8, 2, 5);"

In [5]:
%%sql
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('John Doe', 30, '123 Maple St', 60000.0, 'Software Engineer', 'IT', '2015-06-01', 5, 10, 4.5, 4.7, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Jane Smith', 40, '456 Oak St', 75000.0, 'Project Manager', 'IT', '2010-08-15', 10, 8, 4.8, 4.9, 2, 5);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Alice Johnson', 35, '789 Pine St', 65000.0, 'Business Analyst', 'Business', '2012-11-20', 8, 12, 4.3, 4.5, 1, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Bob Brown', 45, '321 Birch St', 80000.0, 'HR Manager', 'HR', '2008-03-30', 15, 5, 4.7, 4.8, 3, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Charlie Davis', 28, '654 Cedar St', 55000.0, 'Marketing Specialist', 'Marketing', '2017-09-12', 3, 15, 4.1, 4.3, 0, 6);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('David Miller', 32, '123 Elm St', 61000.0, 'Data Analyst', 'IT', '2016-05-15', 6, 11, 4.4, 4.6, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Eva Taylor', 29, '234 Pine St', 58000.0, 'UX Designer', 'Design', '2018-07-01', 4, 9, 4.2, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Frank White', 38, '345 Cedar St', 72000.0, 'Systems Engineer', 'IT', '2013-12-05', 9, 7, 4.6, 4.7, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Grace Lee', 26, '456 Birch St', 54000.0, 'Content Writer', 'Marketing', '2019-03-22', 2, 13, 4.0, 4.1, 0, 1);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Henry Walker', 41, '567 Maple St', 78000.0, 'Network Administrator', 'IT', '2011-09-10', 12, 6, 4.7, 4.8, 3, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Isabella Harris', 27, '678 Oak St', 56000.0, 'Graphic Designer', 'Design', '2017-11-15', 3, 14, 4.3, 4.5, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Jack Martin', 34, '789 Pine St', 63000.0, 'Database Administrator', 'IT', '2014-06-18', 7, 10, 4.5, 4.6, 2, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Karen Young', 45, '890 Cedar St', 85000.0, 'Finance Manager', 'Finance', '2009-02-25', 15, 5, 4.8, 4.9, 3, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Liam Carter', 28, '901 Birch St', 57000.0, 'Marketing Coordinator', 'Marketing', '2018-04-10', 3, 12, 4.1, 4.2, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Mia Thompson', 33, '123 Maple St', 62000.0, 'QA Engineer', 'IT', '2015-10-05', 6, 11, 4.4, 4.5, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Noah Roberts', 30, '234 Oak St', 59000.0, 'Technical Writer', 'IT', '2016-08-20', 5, 9, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Olivia Lewis', 39, '345 Pine St', 70000.0, 'Operations Manager', 'Operations', '2012-03-15', 10, 8, 4.6, 4.7, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Paul Green', 27, '456 Cedar St', 55000.0, 'Customer Support', 'Support', '2017-07-30', 3, 14, 4.2, 4.3, 0, 1);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Quinn Scott', 42, '567 Birch St', 76000.0, 'Business Development', 'Business', '2010-05-22', 12, 6, 4.7, 4.8, 3, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Rachel King', 31, '678 Maple St', 60000.0, 'Product Manager', 'Product', '2015-12-01', 5, 10, 4.5, 4.6, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Samuel Wright', 29, '789 Oak St', 58000.0, 'Software Developer', 'IT', '2017-11-05', 4, 11, 4.3, 4.4, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Tina Hall', 35, '890 Pine St', 64000.0, 'HR Specialist', 'HR', '2014-08-25', 7, 9, 4.6, 4.7, 2, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Uma Baker', 40, '901 Cedar St', 75000.0, 'Sales Manager', 'Sales', '2010-04-18', 10, 8, 4.8, 4.9, 3, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Victor Phillips', 28, '123 Birch St', 57000.0, 'SEO Specialist', 'Marketing', '2018-05-10', 3, 13, 4.2, 4.3, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Wendy Campbell', 36, '234 Maple St', 65000.0, 'Accountant', 'Finance', '2014-09-20', 8, 9, 4.5, 4.6, 2, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Xander James', 33, '345 Oak St', 63000.0, 'Technical Support', 'Support', '2015-06-15', 6, 11, 4.4, 4.5, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Yara Flores', 29, '456 Pine St', 59000.0, 'Copywriter', 'Marketing', '2016-07-10', 5, 10, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Zachary Morris', 40, '567 Cedar St', 77000.0, 'Logistics Manager', 'Operations', '2011-02-18', 12, 7, 4.7, 4.8, 3, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Anna Rogers', 28, '678 Birch St', 56000.0, 'Social Media Manager', 'Marketing', '2018-06-30', 3, 12, 4.1, 4.2, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Brian Nelson', 32, '789 Maple St', 61000.0, 'DevOps Engineer', 'IT', '2016-11-25', 6, 11, 4.4, 4.5, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Catherine Bryant', 30, '890 Oak St', 60000.0, 'Business Analyst', 'Business', '2016-03-20', 5, 10, 4.5, 4.6, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Daniel Foster', 34, '901 Pine St', 63000.0, 'Web Developer', 'IT', '2015-12-10', 7, 9, 4.6, 4.7, 2, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Eleanor Reed', 45, '123 Cedar St', 78000.0, 'HR Director', 'HR', '2009-01-25', 15, 6, 4.8, 4.9, 3, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Francis Diaz', 27, '234 Birch St', 55000.0, 'Customer Success Manager', 'Support', '2017-04-15', 3, 14, 4.2, 4.3, 0, 1);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Gabriella Hughes', 31, '345 Maple St', 60000.0, 'Product Designer', 'Design', '2015-09-20', 5, 10, 4.5, 4.6, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Harry Alexander', 28, '456 Oak St', 57000.0, 'IT Support', 'IT', '2018-03-15', 3, 12, 4.3, 4.4, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Ivy Brooks', 29, '567 Pine St', 58000.0, 'Content Strategist', 'Marketing', '2016-10-10', 4, 11, 4.4, 4.5, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Jackie Sanders', 36, '678 Cedar St', 65000.0, 'Finance Analyst', 'Finance', '2014-07-20', 8, 9, 4.6, 4.7, 2, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Keith Ross', 33, '789 Birch St', 63000.0, 'System Administrator', 'IT', '2015-04-15', 6, 10, 4.5, 4.6, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Laura Jenkins', 40, '890 Maple St', 74000.0, 'Marketing Manager', 'Marketing', '2011-06-20', 10, 8, 4.7, 4.8, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Mike Griffin', 27, '901 Oak St', 55000.0, 'Technical Support Engineer', 'Support', '2017-08-25', 3, 12, 4.2, 4.3, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Nina Wallace', 35, '123 Pine St', 64000.0, 'Data Scientist', 'IT', '2014-03-10', 7, 9, 4.6, 4.7, 2, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Oscar Daniels', 32, '234 Cedar St', 61000.0, 'Backend Developer', 'IT', '2015-12-05', 6, 11, 4.4, 4.5, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Patricia Stewart', 29, '345 Birch St', 58000.0, 'Digital Marketing Specialist', 'Marketing', '2016-05-20', 4, 10, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Quentin Collins', 27, '456 Maple St', 55000.0, 'Front-end Developer', 'IT', '2017-11-10', 3, 13, 4.2, 4.3, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Ruth Bennett', 36, '567 Oak St', 65000.0, 'Compliance Officer', 'Operations', '2014-02-15', 8, 9, 4.5, 4.6, 2, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Steven Hamilton', 33, '678 Pine St', 63000.0, 'Network Engineer', 'IT', '2015-07-20', 6, 10, 4.4, 4.5, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Tina Adams', 40, '789 Cedar St', 74000.0, 'HR Consultant', 'HR', '2011-04-10', 10, 8, 4.7, 4.8, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Uma Grant', 27, '890 Birch St', 55000.0, 'Sales Representative', 'Sales', '2017-06-15', 3, 12, 4.2, 4.3, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Victor Mitchell', 36, '901 Maple St', 64000.0, 'Operations Analyst', 'Operations', '2014-09-20', 8, 9, 4.6, 4.7, 2, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Wendy Edwards', 33, '123 Oak St', 61000.0, 'IT Project Manager', 'IT', '2015-04-25', 6, 11, 4.5, 4.6, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Xander Fox', 28, '234 Pine St', 57000.0, 'UX Researcher', 'Design', '2018-02-10', 3, 13, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Yara Adams', 35, '345 Cedar St', 65000.0, 'Business Consultant', 'Business', '2014-06-20', 8, 9, 4.6, 4.7, 2, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Zachary Foster', 33, '456 Birch St', 63000.0, 'Software Engineer', 'IT', '2015-10-15', 6, 10, 4.4, 4.5, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Alice Johnson', 28, '789 Elm St', 59000.0, 'Data Analyst', 'Business', '2016-08-20', 4, 11, 4.2, 4.3, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Bob Smith', 42, '123 Walnut St', 82000.0, 'IT Manager', 'IT', '2010-07-15', 12, 8, 4.7, 4.8, 3, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Carol Taylor', 30, '456 Cedar St', 63000.0, 'HR Specialist', 'HR', '2015-05-20', 5, 10, 4.5, 4.6, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('David Brown', 34, '789 Oak St', 68000.0, 'Sales Manager', 'Sales', '2013-11-10', 7, 9, 4.6, 4.7, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Eva Wilson', 29, '123 Pine St', 61000.0, 'Marketing Coordinator', 'Marketing', '2016-01-15', 4, 12, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Frank Garcia', 38, '456 Elm St', 75000.0, 'Finance Manager', 'Finance', '2012-09-25', 10, 8, 4.7, 4.8, 2, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Grace Martinez', 32, '789 Walnut St', 66000.0, 'Content Writer', 'Marketing', '2014-04-10', 6, 11, 4.4, 4.5, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Henry Robinson', 31, '123 Cedar St', 65000.0, 'Product Manager', 'Business', '2015-06-20', 5, 10, 4.5, 4.6, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Isabella Clark', 27, '456 Oak St', 57000.0, 'Graphic Designer', 'Design', '2017-03-15', 3, 13, 4.2, 4.3, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Jack White', 35, '789 Pine St', 69000.0, 'Operations Manager', 'Operations', '2013-02-20', 8, 9, 4.6, 4.7, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Karen Lewis', 40, '123 Elm St', 74000.0, 'HR Director', 'HR', '2010-07-25', 12, 7, 4.8, 4.9, 3, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Liam Harris', 28, '456 Walnut St', 59000.0, 'SEO Specialist', 'Marketing', '2016-08-30', 4, 12, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Mia Lee', 33, '789 Cedar St', 66000.0, 'Data Scientist', 'IT', '2015-05-15', 6, 10, 4.5, 4.6, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Nathan King', 37, '123 Oak St', 72000.0, 'Logistics Coordinator', 'Operations', '2012-03-20', 9, 8, 4.7, 4.8, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Olivia Scott', 31, '456 Pine St', 64000.0, 'Sales Executive', 'Sales', '2015-10-10', 5, 11, 4.4, 4.5, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Patrick Turner', 39, '789 Elm St', 70000.0, 'Business Development Manager', 'Business', '2012-11-25', 10, 9, 4.6, 4.7, 2, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Quinn Rivera', 28, '123 Walnut St', 58000.0, 'Customer Service Representative', 'Support', '2016-02-15', 4, 13, 4.3, 4.4, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Rachel Martinez', 30, '456 Cedar St', 63000.0, 'Account Manager', 'Finance', '2015-07-10', 5, 10, 4.5, 4.6, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Sam Parker', 32, '789 Oak St', 66000.0, 'IT Support Specialist', 'IT', '2014-09-20', 6, 11, 4.4, 4.5, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Tina Clark', 34, '123 Pine St', 67000.0, 'Public Relations Manager', 'Marketing', '2013-03-25', 7, 9, 4.6, 4.7, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Umar Green', 27, '456 Elm St', 58000.0, 'Content Strategist', 'Content', '2017-05-15', 3, 12, 4.3, 4.4, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Vanessa Young', 29, '789 Walnut St', 60000.0, 'Event Planner', 'Marketing', '2016-10-20', 4, 11, 4.4, 4.5, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Walter Hernandez', 33, '123 Cedar St', 65000.0, 'Research Analyst', 'Research', '2014-06-15', 6, 10, 4.5, 4.6, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Ximena Cooper', 31, '456 Oak St', 64000.0, 'Supply Chain Manager', 'Operations', '2015-08-20', 5, 11, 4.4, 4.5, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Yvonne Campbell', 30, '789 Pine St', 62000.0, 'Sales Consultant', 'Sales', '2015-11-10', 5, 12, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Zachary Long', 35, '123 Elm St', 70000.0, 'Technical Writer', 'IT', '2013-02-20', 8, 9, 4.6, 4.7, 2, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Amelia Moore', 28, '456 Walnut St', 59000.0, 'Content Manager', 'Content', '2016-01-15', 4, 12, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Benjamin Brown', 36, '789 Cedar St', 68000.0, 'HR Generalist', 'HR', '2012-05-20', 9, 8, 4.7, 4.8, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Charlotte Davis', 29, '123 Oak St', 61000.0, 'Marketing Analyst', 'Marketing', '2015-03-25', 4, 11, 4.4, 4.5, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Daniel Gonzalez', 38, '456 Pine St', 72000.0, 'Operations Supervisor', 'Operations', '2011-09-10', 10, 8, 4.7, 4.8, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Emma Hall', 32, '789 Elm St', 64000.0, 'Financial Analyst', 'Finance', '2014-08-20', 6, 10, 4.5, 4.6, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Frankie Allen', 33, '123 Walnut St', 67000.0, 'Web Developer', 'IT', '2014-04-15', 7, 9, 4.6, 4.7, 2, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Grace King', 29, '456 Cedar St', 60000.0, 'Brand Manager', 'Marketing', '2015-06-20', 4, 11, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Henry Roberts', 35, '789 Oak St', 69000.0, 'Systems Analyst', 'IT', '2013-09-25', 8, 9, 4.6, 4.7, 2, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Isabelle Turner', 30, '123 Pine St', 62000.0, 'Sales Coordinator', 'Sales', '2015-11-15', 5, 10, 4.4, 4.5, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Jackie Clark', 37, '456 Elm St', 72000.0, 'Operations Director', 'Operations', '2012-01-10', 10, 8, 4.7, 4.8, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Kara Edwards', 31, '789 Walnut St', 63000.0, 'Content Creator', 'Content', '2015-08-20', 6, 10, 4.5, 4.6, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Liam Scott', 27, '123 Cedar St', 58000.0, 'Support Engineer', 'IT', '2016-03-25', 4, 12, 4.3, 4.4, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Molly Hughes', 33, '456 Oak St', 65000.0, 'Accountant', 'Finance', '2014-12-15', 7, 9, 4.6, 4.7, 2, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Nate Williams', 29, '789 Pine St', 61000.0, 'Product Specialist', 'Business', '2015-06-10', 5, 11, 4.4, 4.5, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Olivia Collins', 32, '123 Elm St', 66000.0, 'Financial Planner', 'Finance', '2014-05-20', 6, 10, 4.5, 4.6, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Paul Foster', 38, '456 Walnut St', 71000.0, 'Operations Analyst', 'Operations', '2011-07-15', 10, 8, 4.7, 4.8, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Quinn Howard', 30, '789 Cedar St', 63000.0, 'Sales Trainer', 'Sales', '2015-11-25', 5, 11, 4.4, 4.5, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Rose Ward', 29, '123 Oak St', 60000.0, 'Project Manager', 'Business', '2016-04-15', 4, 12, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Steven Bailey', 34, '456 Pine St', 67000.0, 'Research Scientist', 'Research', '2013-03-10', 8, 9, 4.6, 4.7, 2, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Tina Bell', 37, '789 Elm St', 71000.0, 'IT Administrator', 'IT', '2012-08-20', 10, 8, 4.7, 4.8, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Uma Murphy', 31, '123 Walnut St', 64000.0, 'Data Engineer', 'IT', '2015-01-15', 6, 10, 4.5, 4.6, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Victor Ramirez', 28, '456 Cedar St', 59000.0, 'Customer Success Manager', 'Support', '2016-06-20', 4, 12, 4.3, 4.4, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Wendy Adams', 33, '789 Oak St', 67000.0, 'Marketing Director', 'Marketing', '2013-11-15', 7, 9, 4.6, 4.7, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Xavier Hughes', 29, '123 Pine St', 60000.0, 'HR Specialist', 'HR', '2015-05-10', 4, 11, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Yasmin Lee', 30, '456 Elm St', 62000.0, 'Financial Advisor', 'Finance', '2015-03-20', 5, 10, 4.4, 4.5, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Zane Cooper', 35, '789 Walnut St', 70000.0, 'Sales Director', 'Sales', '2013-02-25', 8, 9, 4.6, 4.7, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Aiden Green', 28, '123 Maple St', 58000.0, 'Junior Developer', 'IT', '2017-09-15', 3, 15, 4.2, 4.3, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Bella Johnson', 31, '456 Oak St', 62000.0, 'Marketing Assistant', 'Marketing', '2015-02-20', 5, 10, 4.4, 4.5, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Caleb Scott', 33, '789 Elm St', 67000.0, 'Business Analyst', 'Business', '2014-07-10', 6, 8, 4.6, 4.7, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Daisy Harris', 29, '123 Cedar St', 59000.0, 'Product Designer', 'Design', '2016-01-15', 4, 12, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Ethan Lewis', 36, '456 Pine St', 71000.0, 'Project Coordinator', 'Operations', '2011-11-25', 9, 8, 4.7, 4.8, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Fiona Brown', 34, '789 Maple St', 68000.0, 'HR Manager', 'HR', '2012-06-15', 8, 9, 4.6, 4.7, 2, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('George White', 31, '123 Oak St', 60000.0, 'Data Analyst', 'IT', '2016-04-20', 5, 11, 4.4, 4.5, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Hannah King', 29, '456 Cedar St', 62000.0, 'Content Strategist', 'Content', '2016-05-15', 4, 12, 4.3, 4.4, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Ian Martinez', 35, '789 Elm St', 70000.0, 'Sales Manager', 'Sales', '2013-01-10', 8, 9, 4.6, 4.7, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Julia Turner', 30, '123 Pine St', 63000.0, 'Finance Analyst', 'Finance', '2015-07-15', 5, 10, 4.5, 4.6, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Kyle Roberts', 32, '456 Oak St', 64000.0, 'Product Manager', 'Business', '2014-08-20', 6, 9, 4.4, 4.5, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Lila Davis', 29, '789 Maple St', 59000.0, 'Marketing Specialist', 'Marketing', '2016-03-15', 4, 12, 4.3, 4.4, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Mason Evans', 34, '123 Cedar St', 67000.0, 'UX Designer', 'Design', '2013-09-20', 7, 8, 4.6, 4.7, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Nora Gonzalez', 30, '456 Pine St', 60000.0, 'IT Support Specialist', 'IT', '2015-06-20', 5, 11, 4.4, 4.5, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Oscar Miller', 29, '789 Oak St', 62000.0, 'Research Analyst', 'Research', '2016-10-05', 4, 12, 4.3, 4.4, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Paige Adams', 33, '123 Maple St', 65000.0, 'Content Manager', 'Content', '2014-02-15', 7, 10, 4.5, 4.6, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Quincy Hill', 36, '456 Oak St', 68000.0, 'Public Relations Specialist', 'PR', '2011-09-10', 9, 8, 4.6, 4.7, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Riley Baker', 28, '789 Elm St', 59000.0, 'Data Scientist', 'IT', '2017-07-15', 3, 15, 4.2, 4.3, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Sophia Evans', 31, '123 Pine St', 62000.0, 'SEO Specialist', 'Marketing', '2015-11-01', 5, 11, 4.4, 4.5, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Tyler Martinez', 35, '456 Maple St', 67000.0, 'Sales Analyst', 'Sales', '2013-08-20', 7, 9, 4.6, 4.7, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Uma Robinson', 30, '789 Cedar St', 61000.0, 'Marketing Coordinator', 'Marketing', '2015-10-15', 5, 12, 4.3, 4.4, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Vera Long', 28, '123 Elm St', 59000.0, 'Content Developer', 'Content', '2017-01-15', 3, 15, 4.2, 4.3, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('William Taylor', 33, '456 Pine St', 64000.0, 'Operations Coordinator', 'Operations', '2014-04-20', 6, 10, 4.4, 4.5, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Xander Wright', 32, '789 Maple St', 63000.0, 'Finance Manager', 'Finance', '2015-12-10', 5, 11, 4.5, 4.6, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Yara Hughes', 29, '123 Cedar St', 60000.0, 'HR Coordinator', 'HR', '2016-02-20', 4, 12, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Zara Wright', 31, '456 Oak St', 62000.0, 'Business Development Manager', 'Business', '2015-11-25', 5, 10, 4.4, 4.5, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Ariana Lopez', 27, '789 Elm St', 59000.0, 'IT Project Manager', 'IT', '2017-06-15', 3, 12, 4.3, 4.4, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Blake Adams', 30, '123 Pine St', 63000.0, 'Marketing Director', 'Marketing', '2015-04-10', 5, 11, 4.5, 4.6, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Chloe White', 32, '456 Maple St', 62000.0, 'Content Specialist', 'Content', '2016-05-20', 4, 10, 4.4, 4.5, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Daniel Clark', 34, '789 Oak St', 66000.0, 'Research Coordinator', 'Research', '2014-09-05', 6, 9, 4.5, 4.6, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Ella Brown', 29, '123 Cedar St', 61000.0, 'Operations Assistant', 'Operations', '2016-07-20', 4, 12, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Finn Garcia', 37, '456 Oak St', 68000.0, 'IT Analyst', 'IT', '2012-03-10', 9, 8, 4.7, 4.8, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Gwen Lewis', 30, '789 Maple St', 60000.0, 'Public Relations Coordinator', 'PR', '2015-06-15', 5, 10, 4.4, 4.5, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Holly Martinez', 33, '123 Pine St', 65000.0, 'Content Analyst', 'Content', '2014-08-20', 6, 9, 4.6, 4.7, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Isaac Turner', 29, '456 Cedar St', 62000.0, 'Business Analyst', 'Business', '2016-03-20', 4, 11, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Jasmine Wright', 32, '789 Elm St', 64000.0, 'Marketing Coordinator', 'Marketing', '2015-12-01', 5, 10, 4.5, 4.6, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Kurt Harris', 28, '123 Maple St', 59000.0, 'Product Manager', 'Product', '2017-04-15', 3, 12, 4.2, 4.3, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Liam Scott', 35, '456 Oak St', 67000.0, 'Operations Analyst', 'Operations', '2012-10-20', 8, 9, 4.5, 4.6, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Maya Thompson', 29, '789 Pine St', 62000.0, 'HR Specialist', 'HR', '2016-01-10', 4, 12, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Noah Allen', 31, '123 Cedar St', 63000.0, 'Design Specialist', 'Design', '2015-09-15', 5, 10, 4.4, 4.5, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Olivia Campbell', 28, '456 Maple St', 61000.0, 'Finance Coordinator', 'Finance', '2017-05-20', 3, 15, 4.2, 4.3, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Paul Collins', 34, '789 Elm St', 68000.0, 'Sales Specialist', 'Sales', '2012-12-15', 8, 8, 4.6, 4.7, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Quinn Diaz', 33, '123 Pine St', 66000.0, 'Marketing Analyst', 'Marketing', '2014-11-25', 7, 9, 4.5, 4.6, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Riley Hernandez', 31, '456 Cedar St', 63000.0, 'Product Analyst', 'Product', '2015-06-20', 5, 11, 4.4, 4.5, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Samantha Wilson', 28, '789 Pine St', 60000.0, 'Operations Manager', 'Operations', '2017-02-15', 3, 12, 4.3, 4.4, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Tyler Lopez', 32, '123 Cedar St', 64000.0, 'Customer Service Manager', 'Support', '2015-08-20', 6, 10, 4.5, 4.6, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Ursula Moore', 30, '456 Maple St', 62000.0, 'Business Development Specialist', 'Business', '2016-12-10', 4, 11, 4.4, 4.5, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Victor White', 29, '789 Elm St', 59000.0, 'IT Coordinator', 'IT', '2016-04-20', 4, 12, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Wendy Scott', 35, '123 Pine St', 65000.0, 'HR Coordinator', 'HR', '2013-09-15', 7, 9, 4.6, 4.7, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Xander Cooper', 34, '456 Cedar St', 68000.0, 'Content Manager', 'Content', '2012-11-05', 8, 8, 4.6, 4.7, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Yasmine Brooks', 30, '789 Pine St', 60000.0, 'Product Specialist', 'Product', '2015-07-10', 5, 10, 4.4, 4.5, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Zachary King', 31, '123 Maple St', 64000.0, 'Public Relations Manager', 'PR', '2014-06-15', 6, 10, 4.5, 4.6, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Alyssa Reed', 33, '456 Oak St', 63000.0, 'Business Development Manager', 'Business', '2013-12-20', 7, 9, 4.4, 4.5, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Bradley Evans', 29, '789 Cedar St', 62000.0, 'Design Coordinator', 'Design', '2016-03-25', 4, 11, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Charlotte Murphy', 30, '123 Oak St', 65000.0, 'Sales Specialist', 'Sales', '2015-05-10', 5, 12, 4.4, 4.5, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Derek Collins', 32, '456 Maple St', 67000.0, 'Customer Service Manager', 'Support', '2014-04-15', 6, 10, 4.5, 4.6, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Eva Sanchez', 27, '789 Cedar St', 61000.0, 'Product Manager', 'Product', '2017-03-05', 3, 12, 4.2, 4.3, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Frankie Scott', 31, '123 Oak St', 62000.0, 'Operations Coordinator', 'Operations', '2015-10-05', 5, 11, 4.4, 4.5, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Gina Cooper', 30, '456 Pine St', 60000.0, 'Marketing Specialist', 'Marketing', '2016-08-10', 4, 10, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Hank Wright', 35, '789 Oak St', 67000.0, 'Research Analyst', 'Research', '2012-07-20', 8, 9, 4.6, 4.7, 2, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Iris Lee', 29, '123 Maple St', 62000.0, 'Business Development Specialist', 'Business', '2016-06-10', 4, 10, 4.4, 4.5, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Jack Morris', 34, '456 Oak St', 67000.0, 'Operations Manager', 'Operations', '2013-11-15', 6, 8, 4.5, 4.6, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Kelsey Davis', 32, '789 Pine St', 63000.0, 'Finance Analyst', 'Finance', '2014-09-10', 6, 10, 4.5, 4.6, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Leo Bennett', 31, '123 Cedar St', 65000.0, 'Public Relations Specialist', 'PR', '2015-11-10', 5, 12, 4.4, 4.5, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Mia Gray', 29, '456 Maple St', 61000.0, 'Content Coordinator', 'Content', '2017-02-15', 3, 12, 4.3, 4.4, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Nina Price', 28, '789 Cedar St', 60000.0, 'HR Specialist', 'HR', '2017-01-05', 3, 14, 4.2, 4.3, 0, 1);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Oscar Wright', 30, '456 Maple St', 63000.0, 'Design Manager', 'Design', '2015-04-20', 5, 10, 4.4, 4.5, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Parker Reed', 27, '789 Pine St', 60000.0, 'Marketing Assistant', 'Marketing', '2017-07-15', 3, 12, 4.3, 4.4, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Quinn Adams', 33, '123 Cedar St', 64000.0, 'Customer Service Specialist', 'Support', '2014-10-10', 7, 10, 4.5, 4.6, 2, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Riley Evans', 32, '456 Pine St', 62000.0, 'IT Specialist', 'IT', '2015-01-20', 5, 11, 4.4, 4.5, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Sophia Knight', 29, '789 Oak St', 63000.0, 'Sales Manager', 'Sales', '2016-02-15', 4, 12, 4.3, 4.4, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Tina Harris', 30, '123 Pine St', 62000.0, 'Operations Specialist', 'Operations', '2016-11-05', 4, 12, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Ulysses Clark', 33, '456 Oak St', 65000.0, 'Product Manager', 'Product', '2014-05-10', 7, 10, 4.5, 4.6, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Violet Moore', 31, '789 Cedar St', 60000.0, 'Design Coordinator', 'Design', '2016-07-20', 5, 10, 4.4, 4.5, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Willow Young', 28, '123 Oak St', 60000.0, 'Finance Manager', 'Finance', '2017-06-15', 3, 13, 4.3, 4.4, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Xena Gray', 29, '456 Maple St', 61000.0, 'Marketing Manager', 'Marketing', '2016-09-05', 4, 11, 4.4, 4.5, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Yara Miller', 32, '789 Oak St', 64000.0, 'HR Manager', 'HR', '2015-05-20', 5, 9, 4.5, 4.6, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Zane Davis', 34, '123 Pine St', 67000.0, 'Research Specialist', 'Research', '2013-10-05', 8, 8, 4.6, 4.7, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Aidan Carter', 28, '123 Birch St', 59000.0, 'Business Analyst', 'Business', '2018-03-12', 2, 10, 4.1, 4.2, 0, 1);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Bella Martinez', 31, '456 Birch St', 62000.0, 'Sales Coordinator', 'Sales', '2016-07-22', 4, 12, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Cameron Lee', 29, '789 Birch St', 61000.0, 'Product Specialist', 'Product', '2017-04-15', 3, 11, 4.2, 4.3, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Daisy Taylor', 33, '123 Elm St', 64000.0, 'Marketing Specialist', 'Marketing', '2014-10-18', 6, 10, 4.5, 4.6, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Ethan White', 30, '456 Elm St', 63000.0, 'IT Specialist', 'IT', '2016-02-10', 5, 9, 4.4, 4.5, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Fiona Green', 28, '789 Elm St', 60000.0, 'Customer Service Specialist', 'Support', '2017-05-20', 3, 12, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('George Harris', 32, '123 Maple St', 65000.0, 'Business Development Manager', 'Business', '2015-08-25', 6, 10, 4.4, 4.5, 2, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Holly Adams', 29, '456 Maple St', 62000.0, 'Product Manager', 'Product', '2016-09-10', 4, 11, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Ian Young', 34, '789 Maple St', 68000.0, 'Operations Manager', 'Operations', '2012-11-12', 8, 8, 4.6, 4.7, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Jasmine Clark', 27, '123 Oak St', 61000.0, 'Marketing Analyst', 'Marketing', '2018-01-10', 2, 10, 4.2, 4.3, 0, 1);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Kevin Scott', 31, '456 Oak St', 63000.0, 'HR Specialist', 'HR', '2015-12-20', 5, 11, 4.4, 4.5, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Laura Nelson', 33, '789 Oak St', 64000.0, 'Design Coordinator', 'Design', '2014-07-25', 6, 9, 4.5, 4.6, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Michael Lopez', 29, '123 Birch St', 62000.0, 'Sales Specialist', 'Sales', '2016-05-15', 4, 10, 4.3, 4.4, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Natalie Turner', 31, '456 Birch St', 60000.0, 'Finance Analyst', 'Finance', '2015-09-10', 5, 12, 4.4, 4.5, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Oliver Walker', 28, '789 Birch St', 61000.0, 'IT Coordinator', 'IT', '2017-04-20', 3, 12, 4.2, 4.3, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Peyton Wright', 34, '123 Elm St', 64000.0, 'Customer Service Manager', 'Support', '2014-03-15', 6, 10, 4.4, 4.5, 2, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Quincy Morgan', 32, '456 Elm St', 63000.0, 'Operations Coordinator', 'Operations', '2015-06-10', 5, 11, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Rachel Morris', 30, '789 Elm St', 62000.0, 'Business Development Specialist', 'Business', '2016-01-10', 4, 12, 4.2, 4.3, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Sam Mitchell', 27, '123 Maple St', 60000.0, 'Design Specialist', 'Design', '2018-02-10', 2, 12, 4.1, 4.2, 0, 1);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Taylor Hughes', 31, '456 Maple St', 62000.0, 'Marketing Coordinator', 'Marketing', '2015-10-15', 5, 11, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Ursula Rivera', 29, '789 Maple St', 61000.0, 'HR Coordinator', 'HR', '2017-01-20', 3, 12, 4.2, 4.3, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Victor Turner', 32, '123 Oak St', 65000.0, 'Operations Manager', 'Operations', '2015-06-10', 6, 10, 4.4, 4.5, 2, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Wendy Allen', 30, '456 Oak St', 63000.0, 'Product Manager', 'Product', '2016-03-15', 4, 11, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Xander Brooks', 33, '789 Oak St', 62000.0, 'IT Specialist', 'IT', '2014-09-20', 7, 9, 4.5, 4.6, 2, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Yvonne Carter', 31, '123 Birch St', 61000.0, 'Marketing Specialist', 'Marketing', '2015-12-05', 5, 10, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Zachary Morris', 29, '456 Birch St', 60000.0, 'Business Analyst', 'Business', '2017-03-20', 3, 12, 4.2, 4.3, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Alyssa Bailey', 34, '789 Birch St', 62000.0, 'Customer Service Manager', 'Support', '2012-11-10', 8, 10, 4.5, 4.6, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Brandon King', 30, '123 Elm St', 64000.0, 'Design Manager', 'Design', '2015-08-20', 5, 9, 4.4, 4.5, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Clara Morgan', 27, '456 Elm St', 60000.0, 'IT Coordinator', 'IT', '2018-05-10', 2, 12, 4.2, 4.3, 0, 1);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Derek Clark', 31, '789 Elm St', 62000.0, 'HR Specialist', 'HR', '2016-04-25', 5, 11, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Eva Lewis', 28, '123 Maple St', 61000.0, 'Marketing Analyst', 'Marketing', '2017-07-20', 3, 12, 4.1, 4.2, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Frank Turner', 34, '456 Maple St', 65000.0, 'Operations Manager', 'Operations', '2013-12-10', 6, 10, 4.5, 4.6, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Grace Miller', 29, '789 Maple St', 62000.0, 'Product Specialist', 'Product', '2016-08-10', 4, 11, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Hannah Allen', 30, '123 Oak St', 63000.0, 'Finance Analyst', 'Finance', '2015-01-15', 5, 10, 4.4, 4.5, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Ian Thompson', 31, '456 Oak St', 62000.0, 'Marketing Specialist', 'Marketing', '2015-07-20', 5, 11, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Julia Carter', 29, '789 Oak St', 60000.0, 'Operations Coordinator', 'Operations', '2017-03-05', 3, 12, 4.2, 4.3, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Kevin Moore', 32, '123 Pine St', 64000.0, 'Design Specialist', 'Design', '2015-11-05', 6, 10, 4.4, 4.5, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Laura Robinson', 30, '456 Pine St', 62000.0, 'Business Development Specialist', 'Business', '2016-02-10', 4, 11, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Mark Davis', 31, '789 Pine St', 64000.0, 'Product Manager', 'Product', '2015-08-15', 5, 10, 4.4, 4.5, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Nina Evans', 29, '123 Oak St', 61000.0, 'HR Specialist', 'HR', '2017-03-20', 3, 12, 4.2, 4.3, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Oscar Taylor', 34, '456 Oak St', 67000.0, 'Marketing Manager', 'Marketing', '2012-06-10', 7, 8, 4.6, 4.7, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Paige Miller', 32, '789 Oak St', 65000.0, 'Design Coordinator', 'Design', '2015-01-15', 6, 9, 4.4, 4.5, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Quinn Wright', 30, '123 Maple St', 62000.0, 'Customer Service Specialist', 'Support', '2016-07-10', 4, 11, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Ryan Clark', 29, '456 Maple St', 60000.0, 'IT Specialist', 'IT', '2017-04-20', 3, 12, 4.2, 4.3, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Samantha Turner', 31, '789 Maple St', 64000.0, 'Finance Analyst', 'Finance', '2015-09-10', 5, 10, 4.4, 4.5, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Thomas Allen', 28, '123 Birch St', 61000.0, 'Business Analyst', 'Business', '2018-02-10', 2, 12, 4.1, 4.2, 0, 1);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Uma Patel', 33, '456 Birch St', 62000.0, 'Product Specialist', 'Product', '2014-11-10', 6, 9, 4.5, 4.6, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Victor Lewis', 34, '789 Birch St', 63000.0, 'Marketing Specialist', 'Marketing', '2013-04-05', 7, 8, 4.6, 4.7, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Wendy Harris', 30, '123 Elm St', 64000.0, 'HR Coordinator', 'HR', '2015-10-15', 5, 10, 4.4, 4.5, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Xander Walker', 29, '456 Elm St', 60000.0, 'Design Specialist', 'Design', '2017-03-15', 3, 12, 4.2, 4.3, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Yara White', 31, '789 Elm St', 62000.0, 'Operations Specialist', 'Operations', '2015-08-20', 5, 10, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Zachary Miller', 30, '123 Maple St', 63000.0, 'Sales Coordinator', 'Sales', '2016-06-10', 4, 11, 4.4, 4.5, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Ariana Davis', 29, '456 Maple St', 61000.0, 'Customer Service Specialist', 'Support', '2017-05-15', 3, 11, 4.2, 4.3, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Brandon Evans', 33, '789 Maple St', 64000.0, 'Product Manager', 'Product', '2014-09-10', 6, 9, 4.5, 4.6, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Catherine Lopez', 31, '123 Oak St', 62000.0, 'IT Specialist', 'IT', '2015-12-15', 5, 10, 4.4, 4.5, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Daniel Martin', 32, '456 Oak St', 63000.0, 'Design Manager', 'Design', '2015-05-10', 5, 9, 4.3, 4.4, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Emily Harris', 29, '789 Oak St', 61000.0, 'HR Coordinator', 'HR', '2017-08-20', 3, 12, 4.2, 4.3, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Felix Collins', 34, '123 Pine St', 65000.0, 'Operations Manager', 'Operations', '2013-11-10', 6, 10, 4.5, 4.6, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Gina Wood', 31, '456 Pine St', 62000.0, 'Product Specialist', 'Product', '2016-04-15', 4, 11, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Henry Green', 29, '789 Pine St', 60000.0, 'Marketing Specialist', 'Marketing', '2018-01-20', 2, 12, 4.1, 4.2, 0, 1);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Ivy Wright', 32, '123 Birch St', 62000.0, 'Sales Manager', 'Sales', '2015-11-15', 6, 10, 4.4, 4.5, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Jack Lee', 30, '456 Birch St', 63000.0, 'Customer Service Manager', 'Support', '2016-09-10', 4, 11, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Kelly Young', 29, '789 Birch St', 61000.0, 'IT Coordinator', 'IT', '2017-06-20', 3, 12, 4.2, 4.3, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Liam Clark', 31, '123 Elm St', 62000.0, 'Operations Specialist', 'Operations', '2015-02-10', 5, 11, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Megan Thompson', 30, '456 Elm St', 61000.0, 'HR Specialist', 'HR', '2016-10-20', 4, 12, 4.2, 4.3, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Nathan Evans', 33, '789 Elm St', 62000.0, 'Design Specialist', 'Design', '2014-07-15', 7, 9, 4.5, 4.6, 2, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Olivia Martinez', 28, '123 Maple St', 60000.0, 'Business Analyst', 'Business', '2018-04-20', 2, 12, 4.1, 4.2, 0, 1);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Patrick Brown', 31, '456 Maple St', 62000.0, 'Product Specialist', 'Product', '2016-01-15', 4, 11, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Quinn Cooper', 29, '789 Maple St', 61000.0, 'Operations Coordinator', 'Operations', '2017-07-10', 3, 12, 4.2, 4.3, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Rachel Moore', 34, '123 Oak St', 65000.0, 'Finance Analyst', 'Finance', '2012-11-10', 8, 10, 4.5, 4.6, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Sam Rogers', 30, '456 Oak St', 63000.0, 'IT Specialist', 'IT', '2016-03-15', 4, 11, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Tina Williams', 29, '789 Oak St', 60000.0, 'HR Coordinator', 'HR', '2017-04-20', 3, 12, 4.2, 4.3, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Ulysses Harris', 32, '123 Pine St', 64000.0, 'Marketing Manager', 'Marketing', '2015-12-10', 6, 10, 4.4, 4.5, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Vera Johnson', 31, '456 Pine St', 62000.0, 'Product Manager', 'Product', '2016-05-10', 5, 10, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Will Scott', 30, '789 Pine St', 63000.0, 'Design Manager', 'Design', '2017-01-20', 4, 11, 4.4, 4.5, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Xena Garcia', 33, '123 Birch St', 64000.0, 'Operations Specialist', 'Operations', '2014-09-15', 7, 8, 4.6, 4.7, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Yvonne Rodriguez', 30, '456 Birch St', 62000.0, 'HR Specialist', 'HR', '2016-04-20', 4, 11, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Zane Smith', 29, '789 Birch St', 60000.0, 'Customer Service Specialist', 'Support', '2017-08-15', 3, 12, 4.2, 4.3, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Alyssa Wilson', 31, '123 Elm St', 62000.0, 'Finance Analyst', 'Finance', '2015-06-10', 5, 10, 4.4, 4.5, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Brandon Young', 32, '456 Elm St', 63000.0, 'Marketing Manager', 'Marketing', '2014-08-10', 6, 9, 4.5, 4.6, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Cindy Brown', 30, '789 Elm St', 61000.0, 'Design Specialist', 'Design', '2016-07-15', 4, 11, 4.2, 4.3, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('David Lee', 33, '123 Maple St', 62000.0, 'Sales Specialist', 'Sales', '2013-11-10', 7, 8, 4.5, 4.6, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Ella King', 31, '456 Maple St', 64000.0, 'IT Manager', 'IT', '2015-03-20', 6, 10, 4.4, 4.5, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Felix Martinez', 30, '789 Maple St', 62000.0, 'Business Analyst', 'Business', '2016-02-10', 4, 11, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Grace Turner', 29, '123 Oak St', 61000.0, 'HR Specialist', 'HR', '2017-01-15', 3, 12, 4.2, 4.3, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Henry Roberts', 34, '456 Oak St', 67000.0, 'Marketing Specialist', 'Marketing', '2012-09-10', 8, 8, 4.6, 4.7, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Ivy Lee', 31, '789 Oak St', 63000.0, 'Product Specialist', 'Product', '2015-06-20', 5, 10, 4.4, 4.5, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('James Anderson', 32, '123 Pine St', 62000.0, 'Design Coordinator', 'Design', '2015-04-10', 5, 10, 4.3, 4.4, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Katherine Thompson', 30, '456 Pine St', 61000.0, 'Sales Coordinator', 'Sales', '2016-07-15', 4, 11, 4.2, 4.3, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Liam Moore', 29, '789 Pine St', 60000.0, 'Customer Service Specialist', 'Support', '2017-02-20', 3, 12, 4.1, 4.2, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Maya Brown', 31, '123 Birch St', 62000.0, 'Product Manager', 'Product', '2015-03-20', 5, 10, 4.4, 4.5, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Noah Adams', 34, '456 Birch St', 64000.0, 'Marketing Manager', 'Marketing', '2012-07-10', 8, 9, 4.5, 4.6, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Olivia Scott', 32, '789 Birch St', 63000.0, 'Design Specialist', 'Design', '2014-05-10', 7, 8, 4.4, 4.5, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Paul Lewis', 29, '123 Elm St', 60000.0, 'Operations Coordinator', 'Operations', '2017-03-10', 3, 12, 4.2, 4.3, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Quinn Adams', 30, '456 Elm St', 62000.0, 'HR Manager', 'HR', '2016-11-15', 4, 10, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Rachel Lewis', 33, '789 Elm St', 63000.0, 'Customer Service Manager', 'Support', '2013-12-10', 7, 9, 4.5, 4.6, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Sam Adams', 31, '123 Maple St', 61000.0, 'IT Coordinator', 'IT', '2016-07-20', 4, 12, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Tina Evans', 28, '456 Maple St', 62000.0, 'Finance Coordinator', 'Finance', '2017-05-15', 3, 11, 4.2, 4.3, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Ulysses Scott', 32, '789 Maple St', 63000.0, 'Marketing Specialist', 'Marketing', '2014-10-15', 6, 10, 4.4, 4.5, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Vera Lee', 31, '123 Oak St', 62000.0, 'Sales Manager', 'Sales', '2016-01-15', 4, 11, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Will Turner', 30, '456 Oak St', 61000.0, 'Operations Coordinator', 'Operations', '2017-05-20', 3, 12, 4.2, 4.3, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Xena Adams', 33, '789 Oak St', 64000.0, 'Customer Service Manager', 'Support', '2013-08-20', 8, 8, 4.6, 4.7, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Yvonne Lee', 30, '123 Maple St', 62000.0, 'Business Analyst', 'Business', '2016-04-20', 4, 10, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Zane Williams', 29, '456 Maple St', 60000.0, 'Design Specialist', 'Design', '2017-06-15', 3, 12, 4.2, 4.3, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Laura Robinson', 30, '456 Pine St', 62000.0, 'Business Development Specialist', 'Business', '2016-02-10', 4, 11, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Mark Davis', 31, '789 Pine St', 64000.0, 'Product Manager', 'Product', '2015-08-15', 5, 10, 4.4, 4.5, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Nina Evans', 29, '123 Oak St', 61000.0, 'HR Specialist', 'HR', '2017-03-20', 3, 12, 4.2, 4.3, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Oscar Taylor', 34, '456 Oak St', 67000.0, 'Marketing Manager', 'Marketing', '2012-06-10', 7, 8, 4.6, 4.7, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Paige Miller', 32, '789 Oak St', 65000.0, 'Design Coordinator', 'Design', '2015-01-15', 6, 9, 4.4, 4.5, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Quinn Wright', 30, '123 Maple St', 62000.0, 'Customer Service Specialist', 'Support', '2016-07-10', 4, 11, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Ryan Clark', 29, '456 Maple St', 60000.0, 'IT Specialist', 'IT', '2017-04-20', 3, 12, 4.2, 4.3, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Samantha Turner', 31, '789 Maple St', 64000.0, 'Finance Analyst', 'Finance', '2015-09-10', 5, 10, 4.4, 4.5, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Thomas Allen', 28, '123 Birch St', 61000.0, 'Business Analyst', 'Business', '2018-02-10', 2, 12, 4.1, 4.2, 0, 1);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Uma Patel', 33, '456 Birch St', 62000.0, 'Product Specialist', 'Product', '2014-11-10', 6, 9, 4.5, 4.6, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Victor Lewis', 34, '789 Birch St', 63000.0, 'Marketing Specialist', 'Marketing', '2013-04-05', 7, 8, 4.6, 4.7, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Wendy Harris', 30, '123 Elm St', 64000.0, 'HR Coordinator', 'HR', '2015-10-15', 5, 10, 4.4, 4.5, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Xander Walker', 29, '456 Elm St', 60000.0, 'Design Specialist', 'Design', '2017-03-15', 3, 12, 4.2, 4.3, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Yara White', 31, '789 Elm St', 62000.0, 'Operations Specialist', 'Operations', '2015-08-20', 5, 10, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Zachary Miller', 30, '123 Maple St', 63000.0, 'Sales Coordinator', 'Sales', '2016-06-10', 4, 11, 4.4, 4.5, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Ariana Davis', 29, '456 Maple St', 61000.0, 'Customer Service Specialist', 'Support', '2017-05-15', 3, 11, 4.2, 4.3, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Brandon Evans', 33, '789 Maple St', 64000.0, 'Product Manager', 'Product', '2014-09-10', 6, 9, 4.5, 4.6, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Catherine Lopez', 31, '123 Oak St', 62000.0, 'IT Specialist', 'IT', '2015-12-15', 5, 10, 4.4, 4.5, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Daniel Martin', 32, '456 Oak St', 63000.0, 'Design Manager', 'Design', '2015-05-10', 5, 9, 4.3, 4.4, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Emily Harris', 29, '789 Oak St', 61000.0, 'HR Coordinator', 'HR', '2017-08-20', 3, 12, 4.2, 4.3, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Felix Collins', 34, '123 Pine St', 65000.0, 'Operations Manager', 'Operations', '2013-11-10', 6, 10, 4.5, 4.6, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Gina Wood', 31, '456 Pine St', 62000.0, 'Product Specialist', 'Product', '2016-04-15', 4, 11, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Henry Green', 29, '789 Pine St', 60000.0, 'Marketing Specialist', 'Marketing', '2018-01-20', 2, 12, 4.1, 4.2, 0, 1);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Ivy Wright', 32, '123 Birch St', 62000.0, 'Sales Manager', 'Sales', '2015-11-15', 6, 10, 4.4, 4.5, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Jack Lee', 30, '456 Birch St', 63000.0, 'Customer Service Manager', 'Support', '2016-09-10', 4, 11, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Kelly Young', 29, '789 Birch St', 61000.0, 'IT Coordinator', 'IT', '2017-06-20', 3, 12, 4.2, 4.3, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Liam Clark', 31, '123 Elm St', 62000.0, 'Operations Specialist', 'Operations', '2015-02-10', 5, 11, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Megan Thompson', 30, '456 Elm St', 61000.0, 'HR Specialist', 'HR', '2016-10-20', 4, 12, 4.2, 4.3, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Nathan Evans', 33, '789 Elm St', 62000.0, 'Design Specialist', 'Design', '2014-07-15', 7, 9, 4.5, 4.6, 2, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Olivia Martinez', 28, '123 Maple St', 60000.0, 'Business Analyst', 'Business', '2018-04-20', 2, 12, 4.1, 4.2, 0, 1);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Patrick Brown', 31, '456 Maple St', 62000.0, 'Product Specialist', 'Product', '2016-01-15', 4, 11, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Quinn Cooper', 29, '789 Maple St', 61000.0, 'Operations Coordinator', 'Operations', '2017-07-10', 3, 12, 4.2, 4.3, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Rachel Moore', 34, '123 Oak St', 65000.0, 'Finance Analyst', 'Finance', '2012-11-10', 8, 10, 4.5, 4.6, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Sam Rogers', 30, '456 Oak St', 63000.0, 'IT Specialist', 'IT', '2016-03-15', 4, 11, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Tina Williams', 29, '789 Oak St', 60000.0, 'HR Coordinator', 'HR', '2017-04-20', 3, 12, 4.2, 4.3, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Ulysses Harris', 32, '123 Pine St', 64000.0, 'Marketing Manager', 'Marketing', '2015-12-10', 6, 10, 4.4, 4.5, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Vera Johnson', 31, '456 Pine St', 62000.0, 'Product Manager', 'Product', '2016-05-10', 5, 10, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Will Scott', 30, '789 Pine St', 63000.0, 'Design Manager', 'Design', '2017-01-20', 4, 11, 4.4, 4.5, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Xena Garcia', 33, '123 Birch St', 64000.0, 'Operations Specialist', 'Operations', '2014-09-15', 7, 8, 4.6, 4.7, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Yvonne Rodriguez', 30, '456 Birch St', 62000.0, 'HR Specialist', 'HR', '2016-04-20', 4, 11, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Zane Smith', 29, '789 Birch St', 60000.0, 'Customer Service Specialist', 'Support', '2017-08-15', 3, 12, 4.2, 4.3, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Alyssa Wilson', 31, '123 Elm St', 62000.0, 'Finance Analyst', 'Finance', '2015-06-10', 5, 10, 4.4, 4.5, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Brandon Young', 32, '456 Elm St', 63000.0, 'Marketing Manager', 'Marketing', '2014-08-10', 6, 9, 4.5, 4.6, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Cindy Brown', 30, '789 Elm St', 61000.0, 'Design Specialist', 'Design', '2016-07-15', 4, 11, 4.2, 4.3, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('David Lee', 33, '123 Maple St', 62000.0, 'Sales Specialist', 'Sales', '2013-11-10', 7, 8, 4.5, 4.6, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Ella King', 31, '456 Maple St', 64000.0, 'IT Manager', 'IT', '2015-03-20', 6, 10, 4.4, 4.5, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Felix Martinez', 30, '789 Maple St', 62000.0, 'Business Analyst', 'Business', '2016-02-10', 4, 11, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Grace Turner', 29, '123 Oak St', 61000.0, 'HR Specialist', 'HR', '2017-01-15', 3, 12, 4.2, 4.3, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Henry Roberts', 34, '456 Oak St', 67000.0, 'Marketing Specialist', 'Marketing', '2012-09-10', 8, 8, 4.6, 4.7, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Ivy Lee', 31, '789 Oak St', 63000.0, 'Product Specialist', 'Product', '2015-06-20', 5, 10, 4.4, 4.5, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('James Anderson', 32, '123 Pine St', 62000.0, 'Design Coordinator', 'Design', '2015-04-10', 5, 10, 4.3, 4.4, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Katherine Thompson', 30, '456 Pine St', 61000.0, 'Sales Coordinator', 'Sales', '2016-07-15', 4, 11, 4.2, 4.3, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Liam Moore', 29, '789 Pine St', 60000.0, 'Customer Service Specialist', 'Support', '2017-02-20', 3, 12, 4.1, 4.2, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Maya Brown', 31, '123 Birch St', 62000.0, 'Product Manager', 'Product', '2015-03-20', 5, 10, 4.4, 4.5, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Noah Adams', 34, '456 Birch St', 64000.0, 'Marketing Manager', 'Marketing', '2012-07-10', 8, 9, 4.5, 4.6, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Olivia Scott', 32, '789 Birch St', 63000.0, 'Design Specialist', 'Design', '2014-05-10', 7, 8, 4.4, 4.5, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Paul Lewis', 29, '123 Elm St', 60000.0, 'Operations Coordinator', 'Operations', '2017-03-10', 3, 12, 4.2, 4.3, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Quinn Adams', 30, '456 Elm St', 62000.0, 'HR Manager', 'HR', '2016-11-15', 4, 10, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Rachel Lewis', 33, '789 Elm St', 63000.0, 'Customer Service Manager', 'Support', '2013-12-10', 7, 9, 4.5, 4.6, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Sam Adams', 31, '123 Maple St', 61000.0, 'IT Coordinator', 'IT', '2016-07-20', 4, 12, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Tina Evans', 28, '456 Maple St', 62000.0, 'Finance Coordinator', 'Finance', '2017-05-15', 3, 11, 4.2, 4.3, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Ulysses Scott', 32, '789 Maple St', 63000.0, 'Marketing Specialist', 'Marketing', '2014-10-15', 6, 10, 4.4, 4.5, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Vera Lee', 31, '123 Oak St', 62000.0, 'Sales Manager', 'Sales', '2016-01-15', 4, 11, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Will Turner', 30, '456 Oak St', 61000.0, 'Operations Coordinator', 'Operations', '2017-05-20', 3, 12, 4.2, 4.3, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Xena Adams', 33, '789 Oak St', 64000.0, 'Customer Service Manager', 'Support', '2013-08-20', 8, 8, 4.6, 4.7, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Yvonne Lee', 30, '123 Maple St', 62000.0, 'Business Analyst', 'Business', '2016-04-20', 4, 10, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Zane Williams', 29, '456 Maple St', 60000.0, 'Design Specialist', 'Design', '2017-06-15', 3, 12, 4.2, 4.3, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Aiden Gray', 34, '123 Birch St', 65000.0, 'Project Manager', 'Project', '2011-06-15', 10, 7, 4.6, 4.7, 3, 5);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Becca Davis', 29, '456 Birch St', 60000.0, 'IT Specialist', 'IT', '2018-09-10', 2, 12, 4.1, 4.2, 0, 1);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Carlos Martinez', 31, '789 Birch St', 62000.0, 'HR Specialist', 'HR', '2015-07-20', 5, 10, 4.3, 4.4, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Diana Brown', 32, '123 Elm St', 63000.0, 'Finance Manager', 'Finance', '2014-03-10', 6, 8, 4.5, 4.6, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Ethan Harris', 29, '456 Elm St', 61000.0, 'Operations Specialist', 'Operations', '2017-02-20', 3, 11, 4.2, 4.3, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Fiona Clark', 30, '789 Elm St', 62000.0, 'Sales Manager', 'Sales', '2016-08-15', 4, 10, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('George Wilson', 35, '123 Maple St', 66000.0, 'Design Lead', 'Design', '2012-11-10', 8, 9, 4.6, 4.7, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Hannah Lewis', 31, '456 Maple St', 62000.0, 'Customer Service Specialist', 'Support', '2016-10-20', 4, 10, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Ian Martinez', 33, '789 Maple St', 64000.0, 'Product Manager', 'Product', '2014-05-15', 7, 8, 4.4, 4.5, 2, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Jasmine Adams', 30, '123 Oak St', 61000.0, 'Marketing Coordinator', 'Marketing', '2017-06-20', 3, 12, 4.2, 4.3, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Kevin White', 34, '456 Oak St', 65000.0, 'Business Analyst', 'Business', '2012-02-15', 8, 8, 4.5, 4.6, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Laura Green', 32, '789 Oak St', 63000.0, 'Design Specialist', 'Design', '2015-01-20', 5, 10, 4.4, 4.5, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Matthew Smith', 30, '123 Pine St', 62000.0, 'Operations Manager', 'Operations', '2016-05-10', 4, 11, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Natalie Brown', 29, '456 Pine St', 60000.0, 'HR Manager', 'HR', '2018-02-20', 2, 12, 4.1, 4.2, 0, 1);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Oscar Johnson', 31, '789 Pine St', 62000.0, 'IT Coordinator', 'IT', '2016-09-10', 4, 11, 4.2, 4.3, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Paige Green', 33, '123 Birch St', 63000.0, 'Marketing Specialist', 'Marketing', '2014-07-15', 7, 9, 4.4, 4.5, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Quincy Harris', 30, '456 Birch St', 61000.0, 'Product Specialist', 'Product', '2017-11-10', 3, 12, 4.2, 4.3, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Riley Carter', 31, '789 Birch St', 62000.0, 'Sales Specialist', 'Sales', '2016-04-15', 4, 10, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Sophie Turner', 28, '123 Elm St', 60000.0, 'Finance Specialist', 'Finance', '2019-01-15', 1, 10, 4.1, 4.2, 0, 1);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Thomas King', 33, '456 Elm St', 64000.0, 'Design Manager', 'Design', '2014-09-10', 7, 8, 4.5, 4.6, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Uma Patel', 30, '789 Elm St', 62000.0, 'Operations Specialist', 'Operations', '2016-06-15', 4, 11, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Victor Brown', 31, '123 Maple St', 63000.0, 'IT Specialist', 'IT', '2015-10-10', 5, 10, 4.4, 4.5, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Wendy Green', 32, '456 Maple St', 62000.0, 'Customer Service Specialist', 'Support', '2014-04-15', 6, 9, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Xander Lee', 30, '789 Maple St', 61000.0, 'Finance Analyst', 'Finance', '2017-01-20', 3, 12, 4.2, 4.3, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Yara Adams', 31, '123 Oak St', 62000.0, 'Sales Coordinator', 'Sales', '2015-11-15', 5, 10, 4.4, 4.5, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Zane Walker', 29, '456 Oak St', 60000.0, 'HR Specialist', 'HR', '2017-08-15', 3, 12, 4.2, 4.3, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Amelia Scott', 32, '789 Oak St', 63000.0, 'Marketing Specialist', 'Marketing', '2014-12-20', 6, 9, 4.5, 4.6, 2, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Bradley Moore', 30, '123 Pine St', 62000.0, 'Operations Manager', 'Operations', '2015-02-10', 5, 11, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Catherine Carter', 31, '456 Pine St', 61000.0, 'Product Specialist', 'Product', '2017-03-20', 3, 12, 4.2, 4.3, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Derek Taylor', 33, '789 Pine St', 62000.0, 'Design Coordinator', 'Design', '2014-06-15', 7, 8, 4.4, 4.5, 2, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Emily Evans', 30, '123 Birch St', 61000.0, 'Customer Service Specialist', 'Support', '2016-11-10', 4, 11, 4.2, 4.3, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Franklin White', 31, '456 Birch St', 62000.0, 'Marketing Manager', 'Marketing', '2015-08-20', 5, 10, 4.4, 4.5, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Grace Adams', 32, '789 Birch St', 63000.0, 'Finance Analyst', 'Finance', '2014-01-15', 7, 8, 4.5, 4.6, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Harrison Davis', 30, '123 Elm St', 62000.0, 'HR Manager', 'HR', '2016-04-15', 4, 10, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Ivy Robinson', 31, '456 Elm St', 61000.0, 'Sales Specialist', 'Sales', '2015-10-10', 5, 10, 4.4, 4.5, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Jack Lee', 34, '789 Elm St', 64000.0, 'Design Lead', 'Design', '2012-12-20', 8, 9, 4.6, 4.7, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Kara Scott', 30, '123 Maple St', 62000.0, 'Operations Specialist', 'Operations', '2016-03-10', 4, 11, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Liam Williams', 33, '456 Maple St', 63000.0, 'Product Manager', 'Product', '2014-06-15', 6, 10, 4.4, 4.5, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Mia Wright', 32, '789 Maple St', 62000.0, 'HR Coordinator', 'HR', '2015-08-15', 5, 9, 4.3, 4.4, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Noah Smith', 30, '123 Oak St', 61000.0, 'Finance Specialist', 'Finance', '2016-10-20', 4, 11, 4.2, 4.3, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Olivia Johnson', 29, '456 Oak St', 60000.0, 'Marketing Coordinator', 'Marketing', '2018-02-15', 2, 12, 4.1, 4.2, 0, 1);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Paul Davis', 31, '789 Oak St', 62000.0, 'Sales Manager', 'Sales', '2015-04-15', 5, 10, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Quinn Evans', 28, '123 Pine St', 61000.0, 'IT Specialist', 'IT', '2019-01-15', 1, 12, 4.0, 4.1, 0, 1);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Rachel Scott', 33, '456 Pine St', 64000.0, 'Finance Manager', 'Finance', '2013-06-10', 8, 8, 4.6, 4.7, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Sam Taylor', 32, '789 Pine St', 62000.0, 'Operations Coordinator', 'Operations', '2015-07-20', 6, 9, 4.4, 4.5, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Tina White', 31, '123 Birch St', 63000.0, 'HR Specialist', 'HR', '2014-11-15', 6, 8, 4.5, 4.6, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Ulysses Brown', 30, '456 Birch St', 62000.0, 'Marketing Specialist', 'Marketing', '2017-01-15', 3, 10, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Vera White', 29, '789 Birch St', 61000.0, 'Product Specialist', 'Product', '2018-03-15', 2, 11, 4.1, 4.2, 0, 1);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Will Carter', 30, '123 Elm St', 62000.0, 'Customer Service Specialist', 'Support', '2016-07-20', 4, 11, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Xena Wilson', 33, '456 Elm St', 64000.0, 'Finance Specialist', 'Finance', '2014-05-20', 6, 9, 4.5, 4.6, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Yvonne Scott', 31, '789 Elm St', 62000.0, 'HR Coordinator', 'HR', '2015-12-15', 5, 10, 4.4, 4.5, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Zane Harris', 32, '123 Maple St', 63000.0, 'Operations Specialist', 'Operations', '2014-08-20', 6, 9, 4.4, 4.5, 2, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Aiden Martinez', 29, '456 Maple St', 60000.0, 'Sales Specialist', 'Sales', '2018-11-10', 2, 12, 4.2, 4.3, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Becca Wilson', 31, '789 Maple St', 62000.0, 'Product Manager', 'Product', '2016-05-15', 4, 10, 4.3, 4.4, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Carlos Adams', 30, '123 Oak St', 61000.0, 'Finance Coordinator', 'Finance', '2017-07-20', 3, 11, 4.2, 4.3, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Diana Robinson', 32, '456 Oak St', 62000.0, 'HR Specialist', 'HR', '2015-10-10', 5, 10, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Eric Wright', 34, '789 Oak St', 63000.0, 'Marketing Specialist', 'Marketing', '2013-01-20', 8, 8, 4.6, 4.7, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Fiona Turner', 29, '123 Pine St', 60000.0, 'Sales Coordinator', 'Sales', '2018-07-15', 2, 11, 4.1, 4.2, 0, 1);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('George Murphy', 31, '456 Pine St', 62000.0, 'Design Specialist', 'Design', '2015-03-15', 5, 10, 4.4, 4.5, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Hannah Carter', 32, '789 Pine St', 62000.0, 'Product Manager', 'Product', '2014-04-20', 6, 9, 4.5, 4.6, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Ian Clark', 30, '123 Birch St', 61000.0, 'Operations Specialist', 'Operations', '2017-06-15', 3, 11, 4.2, 4.3, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Julia Davis', 34, '456 Birch St', 64000.0, 'Marketing Lead', 'Marketing', '2012-11-10', 8, 9, 4.7, 4.8, 2, 4);

VALUES ('Kevin Wilson', 33, '789 Birch St', 63000.0, 'IT Manager', 'IT', '2014-01-20', 6, 8, 4.5, 4.6, 2, 3);-- Employee data
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Aidan Brooks', 31, '123 Elm St', 63000.0, 'Customer Service Manager', 'Support', '2014-05-20', 6, 9, 4.4, 4.5, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Brianna Scott', 29, '456 Elm St', 62000.0, 'Sales Coordinator', 'Sales', '2018-04-15', 2, 12, 4.1, 4.2, 0, 1);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Carl Turner', 32, '789 Elm St', 64000.0, 'Finance Specialist', 'Finance', '2015-07-20', 5, 10, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Diana Clark', 30, '123 Maple St', 62000.0, 'Marketing Specialist', 'Marketing', '2016-02-15', 4, 11, 4.2, 4.3, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Edward Hughes', 33, '456 Maple St', 63000.0, 'HR Manager', 'HR', '2014-10-10', 7, 8, 4.4, 4.5, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Fiona Bell', 28, '789 Maple St', 61000.0, 'Design Specialist', 'Design', '2019-01-15', 1, 12, 4.0, 4.1, 0, 1);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('George Allen', 32, '123 Oak St', 62000.0, 'Product Manager', 'Product', '2015-11-10', 5, 9, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Hannah Collins', 31, '456 Oak St', 63000.0, 'Customer Service Specialist', 'Support', '2016-03-15', 4, 11, 4.2, 4.3, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Ian Reed', 30, '789 Oak St', 61000.0, 'Sales Manager', 'Sales', '2017-02-10', 3, 10, 4.1, 4.2, 0, 1);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Jasmine Young', 29, '123 Pine St', 62000.0, 'Operations Specialist', 'Operations', '2018-05-15', 2, 12, 4.0, 4.1, 0, 1);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Kyle Anderson', 34, '456 Pine St', 64000.0, 'Marketing Coordinator', 'Marketing', '2012-07-20', 8, 8, 4.5, 4.6, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Laura Evans', 31, '789 Pine St', 62000.0, 'Design Coordinator', 'Design', '2015-09-15', 5, 10, 4.4, 4.5, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Michael Green', 30, '123 Birch St', 61000.0, 'Product Specialist', 'Product', '2017-10-10', 3, 11, 4.2, 4.3, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Nora Phillips', 32, '456 Birch St', 63000.0, 'HR Coordinator', 'HR', '2014-12-10', 6, 8, 4.5, 4.6, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Oliver Wright', 31, '789 Birch St', 62000.0, 'Finance Coordinator', 'Finance', '2015-08-20', 5, 9, 4.3, 4.4, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Paige Turner', 29, '123 Elm St', 60000.0, 'Operations Coordinator', 'Operations', '2019-03-10', 1, 12, 4.1, 4.2, 0, 1);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Quincy Clark', 33, '456 Elm St', 63000.0, 'Sales Specialist', 'Sales', '2014-06-10', 7, 8, 4.4, 4.5, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Rachel King', 30, '789 Elm St', 62000.0, 'Customer Service Specialist', 'Support', '2016-07-20', 4, 11, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Steve Martinez', 34, '123 Maple St', 64000.0, 'Finance Manager', 'Finance', '2013-04-15', 8, 8, 4.7, 4.8, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Tiffany Adams', 32, '456 Maple St', 62000.0, 'Marketing Specialist', 'Marketing', '2015-03-20', 5, 10, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Ursula Green', 31, '789 Maple St', 61000.0, 'HR Specialist', 'HR', '2016-05-15', 4, 12, 4.2, 4.3, 1, 1);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Victor Lewis', 30, '123 Oak St', 62000.0, 'Design Specialist', 'Design', '2017-09-10', 3, 11, 4.1, 4.2, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Wendy Scott', 29, '456 Oak St', 61000.0, 'Customer Service Coordinator', 'Support', '2018-01-15', 2, 12, 4.0, 4.1, 0, 1);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Xander Roberts', 34, '789 Oak St', 64000.0, 'Sales Manager', 'Sales', '2012-08-20', 8, 9, 4.6, 4.7, 2, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Yara Turner', 33, '123 Pine St', 63000.0, 'Marketing Coordinator', 'Marketing', '2013-07-15', 7, 10, 4.5, 4.6, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Zachary Wilson', 30, '456 Pine St', 62000.0, 'Finance Specialist', 'Finance', '2017-11-10', 3, 12, 4.1, 4.2, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Alice Hughes', 31, '789 Pine St', 62000.0, 'Product Manager', 'Product', '2016-04-15', 4, 9, 4.3, 4.4, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Bradley Adams', 32, '123 Birch St', 63000.0, 'Operations Manager', 'Operations', '2015-09-20', 5, 8, 4.4, 4.5, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Catherine Morgan', 34, '456 Birch St', 64000.0, 'IT Specialist', 'IT', '2012-01-15', 8, 9, 4.6, 4.7, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Daniel Rodriguez', 31, '789 Birch St', 62000.0, 'HR Specialist', 'HR', '2016-03-20', 4, 10, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Emma Wilson', 29, '123 Elm St', 61000.0, 'Marketing Specialist', 'Marketing', '2018-06-15', 2, 11, 4.0, 4.1, 0, 1);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Franklin Adams', 33, '456 Elm St', 63000.0, 'Sales Coordinator', 'Sales', '2014-07-20', 6, 9, 4.4, 4.5, 2, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Gina Clark', 31, '789 Elm St', 62000.0, 'Finance Coordinator', 'Finance', '2015-12-15', 5, 10, 4.2, 4.3, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Harry Johnson', 30, '123 Maple St', 61000.0, 'Customer Service Coordinator', 'Support', '2016-11-10', 4, 11, 4.1, 4.2, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Isabella Walker', 28, '456 Maple St', 60000.0, 'Operations Coordinator', 'Operations', '2019-02-15', 1, 12, 4.0, 4.1, 0, 1);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Jacob White', 32, '789 Maple St', 62000.0, 'Design Specialist', 'Design', '2015-08-10', 5, 10, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Kylie Moore', 31, '123 Oak St', 62000.0, 'Product Specialist', 'Product', '2016-09-15', 4, 11, 4.2, 4.3, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Leo Martin', 30, '456 Oak St', 61000.0, 'HR Coordinator', 'HR', '2017-01-15', 3, 12, 4.1, 4.2, 0, 1);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Mia Lewis', 29, '789 Oak St', 60000.0, 'Marketing Coordinator', 'Marketing', '2018-04-20', 2, 10, 4.0, 4.1, 0, 1);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Noah Taylor', 32, '123 Pine St', 62000.0, 'Design Coordinator', 'Design', '2015-06-10', 5, 11, 4.3, 4.4, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Olivia Miller', 31, '456 Pine St', 63000.0, 'Finance Manager', 'Finance', '2016-08-15', 4, 9, 4.4, 4.5, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Patrick Martinez', 34, '789 Pine St', 64000.0, 'Customer Service Specialist', 'Support', '2012-10-20', 8, 8, 4.5, 4.6, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Quinn Moore', 29, '123 Birch St', 60000.0, 'Operations Specialist', 'Operations', '2019-01-15', 1, 12, 4.0, 4.1, 0, 1);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Riley Adams', 31, '456 Birch St', 62000.0, 'Sales Specialist', 'Sales', '2016-03-10', 4, 10, 4.2, 4.3, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Sophia Lewis', 30, '789 Birch St', 61000.0, 'HR Manager', 'HR', '2017-04-20', 3, 11, 4.1, 4.2, 0, 1);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Thomas Wilson', 33, '123 Elm St', 63000.0, 'Marketing Specialist', 'Marketing', '2014-08-20', 7, 8, 4.5, 4.6, 2, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Uma Robinson', 31, '456 Elm St', 62000.0, 'Design Specialist', 'Design', '2016-11-10', 4, 10, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Vera King', 34, '789 Elm St', 64000.0, 'Finance Specialist', 'Finance', '2012-01-15', 8, 9, 4.6, 4.7, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('William Scott', 32, '123 Maple St', 63000.0, 'Customer Service Coordinator', 'Support', '2015-06-10', 5, 11, 4.4, 4.5, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Xena Lewis', 30, '456 Maple St', 62000.0, 'Sales Coordinator', 'Sales', '2017-07-20', 3, 10, 4.2, 4.3, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Yvette Turner', 29, '789 Maple St', 61000.0, 'HR Specialist', 'HR', '2018-09-15', 2, 11, 4.1, 4.2, 0, 1);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Zachary Taylor', 31, '123 Oak St', 62000.0, 'Operations Specialist', 'Operations', '2016-05-15', 4, 9, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Anna Miller', 34, '456 Oak St', 64000.0, 'Design Specialist', 'Design', '2013-11-20', 8, 8, 4.6, 4.7, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Brian Martin', 33, '789 Oak St', 63000.0, 'Finance Coordinator', 'Finance', '2014-04-10', 7, 9, 4.5, 4.6, 2, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Catherine Young', 31, '123 Pine St', 62000.0, 'Marketing Coordinator', 'Marketing', '2017-06-15', 4, 10, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('David Green', 30, '456 Pine St', 61000.0, 'Product Specialist', 'Product', '2018-01-10', 2, 11, 4.1, 4.2, 0, 1);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Eva White', 32, '789 Pine St', 62000.0, 'Sales Manager', 'Sales', '2015-05-20', 5, 9, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Frank Moore', 31, '123 Birch St', 63000.0, 'Operations Manager', 'Operations', '2016-08-10', 4, 10, 4.3, 4.4, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Grace Johnson', 29, '456 Birch St', 62000.0, 'Marketing Specialist', 'Marketing', '2018-11-10', 2, 12, 4.0, 4.1, 0, 1);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Henry Davis', 31, '789 Birch St', 62000.0, 'Finance Manager', 'Finance', '2015-02-10', 5, 10, 4.4, 4.5, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Isabelle Smith', 32, '123 Elm St', 63000.0, 'HR Specialist', 'HR', '2016-05-10', 5, 8, 4.2, 4.3, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Jack Brown', 33, '456 Elm St', 64000.0, 'Product Manager', 'Product', '2013-04-15', 8, 9, 4.5, 4.6, 2, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Kimberly Lee', 34, '789 Elm St', 64000.0, 'Customer Service Coordinator', 'Support', '2012-07-15', 8, 7, 4.7, 4.8, 3, 5);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Laura Adams', 30, '123 Maple St', 62000.0, 'Marketing Specialist', 'Marketing', '2017-10-10', 4, 10, 4.2, 4.3, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Matthew Davis', 31, '456 Maple St', 63000.0, 'Product Coordinator', 'Product', '2016-04-15', 5, 11, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Nina Clark', 32, '789 Maple St', 62000.0, 'Design Manager', 'Design', '2014-09-15', 6, 9, 4.4, 4.5, 1, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Oscar Wilson', 29, '123 Oak St', 61000.0, 'Customer Service Coordinator', 'Support', '2019-03-20', 1, 10, 4.0, 4.1, 0, 1);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Paula Davis', 34, '456 Oak St', 64000.0, 'Marketing Manager', 'Marketing', '2012-05-15', 8, 8, 4.6, 4.7, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Quincy Adams', 30, '789 Oak St', 62000.0, 'Finance Coordinator', 'Finance', '2017-03-20', 3, 11, 4.1, 4.2, 0, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Rachel Smith', 31, '123 Pine St', 62000.0, 'HR Specialist', 'HR', '2017-01-15', 4, 9, 4.2, 4.3, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Samuel Johnson', 32, '456 Pine St', 63000.0, 'Operations Manager', 'Operations', '2015-02-15', 6, 10, 4.4, 4.5, 2, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Tina Green', 30, '789 Pine St', 62000.0, 'Design Coordinator', 'Design', '2017-10-15', 3, 11, 4.1, 4.2, 0, 1);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Ulysses Wright', 31, '123 Birch St', 62000.0, 'Sales Coordinator', 'Sales', '2016-11-10', 4, 10, 4.3, 4.4, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Vera Adams', 29, '456 Birch St', 61000.0, 'Customer Service Specialist', 'Support', '2018-12-15', 2, 12, 4.0, 4.1, 0, 1);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('William Lewis', 34, '789 Birch St', 64000.0, 'IT Specialist', 'IT', '2013-02-10', 8, 7, 4.6, 4.7, 2, 4);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Xander Martin', 33, '123 Elm St', 63000.0, 'Customer Service Specialist', 'Support', '2014-11-20', 6, 8, 4.5, 4.6, 2, 3);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Yvonne White', 30, '456 Elm St', 62000.0, 'Sales Manager', 'Sales', '2017-04-20', 4, 9, 4.2, 4.3, 1, 2);
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Zachary Lee', 31, '789 Elm St', 63000.0, 'Design Manager', 'Design', '2016-03-20', 5, 9, 4.3, 4.4, 1, 2);

 * sqlite:///NewDB.sqlite3
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
Done.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.

[]

In [6]:
%%sql
SELECT * FROM EMPLOYEE;

 * sqlite:///NewDB.sqlite3
Done.

[(1, 'John Doe', 30, '123 Maple St', 71500.0, 'Software Engineer', 'IT', '2015-06-01', 5, 10, 4.5, 4.7, 1, 3),
 (3, 'Alice Johnson', 35, '789 Pine St', 65000.0, 'Business Analyst', 'Business', '2012-11-20', 8, 12, 4.3, 4.5, 1, 4),
 (4, 'Bob Brown', 45, '321 Birch St', 80000.0, 'HR Manager', 'HR', '2008-03-30', 15, 5, 4.7, 4.8, 3, 2),
 (5, 'Charlie Davis', 28, '654 Cedar St', 55000.0, 'Marketing Specialist', 'Marketing', '2017-09-12', 3, 15, 4.1, 4.3, 0, 6),
 (6, 'David Miller', 32, '123 Elm St', 108065.22100000002, 'Data Analyst', 'IT', '2016-05-15', 6, 11, 4.4, 4.6, 1, 3),
 (7, 'Eva Taylor', 29, '234 Pine St', 58000.0, 'UX Designer', 'Design', '2018-07-01', 4, 9, 4.2, 4.4, 1, 2),
 (8, 'Frank White', 38, '345 Cedar St', 127552.39200000007, 'Systems Engineer', 'IT', '2013-12-05', 9, 7, 4.6, 4.7, 2, 4),
 (9, 'Grace Lee', 26, '456 Birch St', 54000.0, 'Content Writer', 'Marketing', '2019-03-22', 2, 13, 4.0, 4.1, 0, 1),
 (10, 'Henry Walker', 41, '567 Maple St', 138181.75800000006, 'Network Administrator', 'IT', '2011-09-10', 12, 6, 4.7, 4.8, 3, 3),
 (11, 'Isabella Harris', 27, '678 Oak St', 56000.0, 'Graphic Designer', 'Design', '2017-11-15', 3, 14, 4.3, 4.5, 1, 2),
 (12, 'Jack Martin', 34, '789 Pine St', 111608.34300000001, 'Database Administrator', 'IT', '2014-06-18', 7, 10, 4.5, 4.6, 2, 3),
 (13, 'Karen Young', 45, '890 Cedar St', 85000.0, 'Finance Manager', 'Finance', '2009-02-25', 15, 5, 4.8, 4.9, 3, 4),
 (14, 'Liam Carter', 28, '901 Birch St', 57000.0, 'Marketing Coordinator', 'Marketing', '2018-04-10', 3, 12, 4.1, 4.2, 0, 2),
 (15, 'Mia Thompson', 33, '123 Maple St', 109836.78200000004, 'QA Engineer', 'IT', '2015-10-05', 6, 11, 4.4, 4.5, 1, 3),
 (16, 'Noah Roberts', 30, '234 Oak St', 104522.09900000007, 'Technical Writer', 'IT', '2016-08-20', 5, 9, 4.3, 4.4, 1, 2),
 (17, 'Olivia Lewis', 39, '345 Pine St', 70000.0, 'Operations Manager', 'Operations', '2012-03-15', 10, 8, 4.6, 4.7, 2, 4),
 (18, 'Paul Green', 27, '456 Cedar St', 55000.0, 'Customer Support', 'Support', '2017-07-30', 3, 14, 4.2, 4.3, 0, 1),
 (19, 'Quinn Scott', 42, '567 Birch St', 76000.0, 'Business Development', 'Business', '2010-05-22', 12, 6, 4.7, 4.8, 3, 3),
 (20, 'Rachel King', 31, '678 Maple St', 60000.0, 'Product Manager', 'Product', '2015-12-01', 5, 10, 4.5, 4.6, 1, 2),
 (21, 'Samuel Wright', 29, '789 Oak St', 102750.53800000006, 'Software Developer', 'IT', '2017-11-05', 4, 11, 4.3, 4.4, 1, 3),
 (22, 'Tina Hall', 35, '890 Pine St', 64000.0, 'HR Specialist', 'HR', '2014-08-25', 7, 9, 4.6, 4.7, 2, 3),
 (23, 'Uma Baker', 40, '901 Cedar St', 75000.0, 'Sales Manager', 'Sales', '2010-04-18', 10, 8, 3.3, 4.9, 3, 4),
 (24, 'Victor Phillips', 28, '123 Birch St', 57000.0, 'SEO Specialist', 'Marketing', '2018-05-10', 3, 13, 4.2, 4.3, 0, 2),
 (25, 'Wendy Campbell', 36, '234 Maple St', 65000.0, 'Accountant', 'Finance', '2014-09-20', 8, 9, 4.5, 4.6, 2, 3),
 (26, 'Xander James', 33, '345 Oak St', 63000.0, 'Technical Support', 'Support', '2015-06-15', 6, 11, 4.4, 4.5, 1, 3),
 (27, 'Yara Flores', 29, '456 Pine St', 59000.0, 'Copywriter', 'Marketing', '2016-07-10', 5, 10, 4.3, 4.4, 1, 2),
 (28, 'Zachary Morris', 40, '567 Cedar St', 77000.0, 'Logistics Manager', 'Operations', '2011-02-18', 12, 7, 4.7, 4.8, 3, 4),
 (29, 'Anna Rogers', 28, '678 Birch St', 56000.0, 'Social Media Manager', 'Marketing', '2018-06-30', 3, 12, 4.1, 4.2, 0, 2),
 (30, 'Brian Nelson', 32, '789 Maple St', 108065.22100000002, 'DevOps Engineer', 'IT', '2016-11-25', 6, 11, 4.4, 4.5, 1, 3),
 (31, 'Catherine Bryant', 30, '890 Oak St', 60000.0, 'Business Analyst', 'Business', '2016-03-20', 5, 10, 4.5, 4.6, 1, 3),
 (32, 'Daniel Foster', 34, '901 Pine St', 111608.34300000001, 'Web Developer', 'IT', '2015-12-10', 7, 9, 4.6, 4.7, 2, 3),
 (33, 'Eleanor Reed', 45, '123 Cedar St', 78000.0, 'HR Director', 'HR', '2009-01-25', 15, 6, 4.8, 4.9, 3, 4),
 (34, 'Francis Diaz', 27, '234 Birch St', 55000.0, 'Customer Success Manager', 'Support', '2017-04-15', 3, 14, 4.2, 4.3, 0, 1),
 (35, 'Gabriella Hughes', 31, '345 Maple St', 60000.0, 'Product Designer', 'Design', '2015-09-20', 5, 10, 4.5, 4.6, 1, 2),
 (36, 'Harry Alexander', 28, '456 Oak St', 100978.97700000006, 'IT Support', 'IT', '2018-03-15', 3, 12, 4.3, 4.4, 1, 3),
 (37, 'Ivy Brooks', 29, '567 Pine St', 58000.0, 'Content Strategist', 'Marketing', '2016-10-10', 4, 11, 4.4, 4.5, 1, 2),
 (38, 'Jackie Sanders', 36, '678 Cedar St', 65000.0, 'Finance Analyst', 'Finance', '2014-07-20', 8, 9, 4.6, 4.7, 2, 3),
 (39, 'Keith Ross', 33, '789 Birch St', 111608.34300000001, 'System Administrator', 'IT', '2015-04-15', 6, 10, 4.5, 4.6, 1, 3),
 (40, 'Laura Jenkins', 40, '890 Maple St', 74000.0, 'Marketing Manager', 'Marketing', '2011-06-20', 10, 8, 4.7, 4.8, 2, 4),
 (41, 'Mike Griffin', 27, '901 Oak St', 55000.0, 'Technical Support Engineer', 'Support', '2017-08-25', 3, 12, 4.2, 4.3, 0, 2),
 (42, 'Nina Wallace', 35, '123 Pine St', 113379.90400000002, 'Data Scientist', 'IT', '2014-03-10', 7, 9, 4.6, 4.7, 2, 3),
 (43, 'Oscar Daniels', 32, '234 Cedar St', 108065.22100000002, 'Backend Developer', 'IT', '2015-12-05', 6, 11, 4.4, 4.5, 1, 3),
 (44, 'Patricia Stewart', 29, '345 Birch St', 58000.0, 'Digital Marketing Specialist', 'Marketing', '2016-05-20', 4, 10, 4.3, 4.4, 1, 2),
 (45, 'Quentin Collins', 27, '456 Maple St', 97435.85500000007, 'Front-end Developer', 'IT', '2017-11-10', 3, 13, 4.2, 4.3, 1, 2),
 (46, 'Ruth Bennett', 36, '567 Oak St', 65000.0, 'Compliance Officer', 'Operations', '2014-02-15', 8, 9, 4.5, 4.6, 2, 3),
 (47, 'Steven Hamilton', 33, '678 Pine St', 111608.34300000001, 'Network Engineer', 'IT', '2015-07-20', 6, 10, 4.4, 4.5, 1, 3),
 (48, 'Tina Adams', 40, '789 Cedar St', 74000.0, 'HR Consultant', 'HR', '2011-04-10', 10, 8, 4.7, 4.8, 2, 4),
 (49, 'Uma Grant', 27, '890 Birch St', 55000.0, 'Sales Representative', 'Sales', '2017-06-15', 3, 12, 2.7, 4.3, 0, 2),
 (50, 'Victor Mitchell', 36, '901 Maple St', 64000.0, 'Operations Analyst', 'Operations', '2014-09-20', 8, 9, 4.6, 4.7, 2, 3),
 (51, 'Wendy Edwards', 33, '123 Oak St', 108065.22100000002, 'IT Project Manager', 'IT', '2015-04-25', 6, 11, 4.5, 4.6, 1, 3),
 (52, 'Xander Fox', 28, '234 Pine St', 57000.0, 'UX Researcher', 'Design', '2018-02-10', 3, 13, 4.3, 4.4, 1, 2),
 (53, 'Yara Adams', 35, '345 Cedar St', 65000.0, 'Business Consultant', 'Business', '2014-06-20', 8, 9, 4.6, 4.7, 2, 3),
 (54, 'Zachary Foster', 33, '456 Birch St', 111608.34300000001, 'Software Engineer', 'IT', '2015-10-15', 6, 10, 4.4, 4.5, 1, 3),
 (55, 'Alice Johnson', 28, '789 Elm St', 59000.0, 'Data Analyst', 'Business', '2016-08-20', 4, 11, 4.2, 4.3, 1, 2),
 (56, 'Bob Smith', 42, '123 Walnut St', 145268.0020000001, 'IT Manager', 'IT', '2010-07-15', 12, 8, 4.7, 4.8, 3, 4),
 (57, 'Carol Taylor', 30, '456 Cedar St', 63000.0, 'HR Specialist', 'HR', '2015-05-20', 5, 10, 4.5, 4.6, 1, 3),
 (58, 'David Brown', 34, '789 Oak St', 68000.0, 'Sales Manager', 'Sales', '2013-11-10', 7, 9, 3.0999999999999996, 4.7, 2, 4),
 (59, 'Eva Wilson', 29, '123 Pine St', 61000.0, 'Marketing Coordinator', 'Marketing', '2016-01-15', 4, 12, 4.3, 4.4, 1, 2),
 (60, 'Frank Garcia', 38, '456 Elm St', 75000.0, 'Finance Manager', 'Finance', '2012-09-25', 10, 8, 4.7, 4.8, 2, 3),
 (61, 'Grace Martinez', 32, '789 Walnut St', 66000.0, 'Content Writer', 'Marketing', '2014-04-10', 6, 11, 4.4, 4.5, 1, 2),
 (62, 'Henry Robinson', 31, '123 Cedar St', 65000.0, 'Product Manager', 'Business', '2015-06-20', 5, 10, 4.5, 4.6, 1, 3),
 (63, 'Isabella Clark', 27, '456 Oak St', 57000.0, 'Graphic Designer', 'Design', '2017-03-15', 3, 13, 4.2, 4.3, 0, 2),
 (64, 'Jack White', 35, '789 Pine St', 69000.0, 'Operations Manager', 'Operations', '2013-02-20', 8, 9, 4.6, 4.7, 2, 4),
 (65, 'Karen Lewis', 40, '123 Elm St', 74000.0, 'HR Director', 'HR', '2010-07-25', 12, 7, 4.8, 4.9, 3, 4),
 (66, 'Liam Harris', 28, '456 Walnut St', 59000.0, 'SEO Specialist', 'Marketing', '2016-08-30', 4, 12, 4.3, 4.4, 1, 2),
 (67, 'Mia Lee', 33, '789 Cedar St', 116923.02600000003, 'Data Scientist', 'IT', '2015-05-15', 6, 10, 4.5, 4.6, 1, 3),
 (68, 'Nathan King', 37, '123 Oak St', 72000.0, 'Logistics Coordinator', 'Operations', '2012-03-20', 9, 8, 4.7, 4.8, 2, 4),
 (69, 'Olivia Scott', 31, '456 Pine St', 64000.0, 'Sales Executive', 'Sales', '2015-10-10', 5, 11, 2.9000000000000004, 4.5, 1, 3),
 (70, 'Patrick Turner', 39, '789 Elm St', 70000.0, 'Business Development Manager', 'Business', '2012-11-25', 10, 9, 4.6, 4.7, 2, 3),
 (71, 'Quinn Rivera', 28, '123 Walnut St', 58000.0, 'Customer Service Representative', 'Support', '2016-02-15', 4, 13, 4.3, 4.4, 0, 2),
 (72, 'Rachel Martinez', 30, '456 Cedar St', 63000.0, 'Account Manager', 'Finance', '2015-07-10', 5, 10, 4.5, 4.6, 1, 3),
 (73, 'Sam Parker', 32, '789 Oak St', 116923.02600000003, 'IT Support Specialist', 'IT', '2014-09-20', 6, 11, 4.4, 4.5, 1, 3),
 (74, 'Tina Clark', 34, '123 Pine St', 67000.0, 'Public Relations Manager', 'Marketing', '2013-03-25', 7, 9, 4.6, 4.7, 2, 4),
 (75, 'Umar Green', 27, '456 Elm St', 58000.0, 'Content Strategist', 'Content', '2017-05-15', 3, 12, 4.3, 4.4, 0, 2),
 (76, 'Vanessa Young', 29, '789 Walnut St', 60000.0, 'Event Planner', 'Marketing', '2016-10-20', 4, 11, 4.4, 4.5, 1, 3),
 (77, 'Walter Hernandez', 33, '123 Cedar St', 65000.0, 'Research Analyst', 'Research', '2014-06-15', 6, 10, 4.5, 4.6, 1, 2),
 (78, 'Ximena Cooper', 31, '456 Oak St', 64000.0, 'Supply Chain Manager', 'Operations', '2015-08-20', 5, 11, 4.4, 4.5, 1, 3),
 (79, 'Yvonne Campbell', 30, '789 Pine St', 62000.0, 'Sales Consultant', 'Sales', '2015-11-10', 5, 12, 2.8, 4.4, 1, 2),
 (80, 'Zachary Long', 35, '123 Elm St', 124009.27000000005, 'Technical Writer', 'IT', '2013-02-20', 8, 9, 4.6, 4.7, 2, 3),
 (81, 'Amelia Moore', 28, '456 Walnut St', 59000.0, 'Content Manager', 'Content', '2016-01-15', 4, 12, 4.3, 4.4, 1, 2),
 (82, 'Benjamin Brown', 36, '789 Cedar St', 68000.0, 'HR Generalist', 'HR', '2012-05-20', 9, 8, 4.7, 4.8, 2, 4),
 (83, 'Charlotte Davis', 29, '123 Oak St', 61000.0, 'Marketing Analyst', 'Marketing', '2015-03-25', 4, 11, 4.4, 4.5, 1, 3),
 (84, 'Daniel Gonzalez', 38, '456 Pine St', 72000.0, 'Operations Supervisor', 'Operations', '2011-09-10', 10, 8, 4.7, 4.8, 2, 4),
 (85, 'Emma Hall', 32, '789 Elm St', 64000.0, 'Financial Analyst', 'Finance', '2014-08-20', 6, 10, 4.5, 4.6, 1, 3),
 (86, 'Frankie Allen', 33, '123 Walnut St', 118694.58700000004, 'Web Developer', 'IT', '2014-04-15', 7, 9, 4.6, 4.7, 2, 3),
 (87, 'Grace King', 29, '456 Cedar St', 60000.0, 'Brand Manager', 'Marketing', '2015-06-20', 4, 11, 4.3, 4.4, 1, 2),
 (88, 'Henry Roberts', 35, '789 Oak St', 122237.70900000005, 'Systems Analyst', 'IT', '2013-09-25', 8, 9, 4.6, 4.7, 2, 3),
 (89, 'Isabelle Turner', 30, '123 Pine St', 62000.0, 'Sales Coordinator', 'Sales', '2015-11-15', 5, 10, 2.9000000000000004, 4.5, 1, 3),
 (90, 'Jackie Clark', 37, '456 Elm St', 72000.0, 'Operations Director', 'Operations', '2012-01-10', 10, 8, 4.7, 4.8, 2, 4),
 (91, 'Kara Edwards', 31, '789 Walnut St', 63000.0, 'Content Creator', 'Content', '2015-08-20', 6, 10, 4.5, 4.6, 1, 2),
 (92, 'Liam Scott', 27, '123 Cedar St', 102750.53800000006, 'Support Engineer', 'IT', '2016-03-25', 4, 12, 4.3, 4.4, 0, 2),
 (93, 'Molly Hughes', 33, '456 Oak St', 65000.0, 'Accountant', 'Finance', '2014-12-15', 7, 9, 4.6, 4.7, 2, 3),
 (94, 'Nate Williams', 29, '789 Pine St', 61000.0, 'Product Specialist', 'Business', '2015-06-10', 5, 11, 4.4, 4.5, 1, 3),
 (95, 'Olivia Collins', 32, '123 Elm St', 66000.0, 'Financial Planner', 'Finance', '2014-05-20', 6, 10, 4.5, 4.6, 1, 2),
 (96, 'Paul Foster', 38, '456 Walnut St', 71000.0, 'Operations Analyst', 'Operations', '2011-07-15', 10, 8, 4.7, 4.8, 2, 4),
 (97, 'Quinn Howard', 30, '789 Cedar St', 63000.0, 'Sales Trainer', 'Sales', '2015-11-25', 5, 11, 2.9000000000000004, 4.5, 1, 3),
 (98, 'Rose Ward', 29, '123 Oak St', 60000.0, 'Project Manager', 'Business', '2016-04-15', 4, 12, 4.3, 4.4, 1, 2),
 (99, 'Steven Bailey', 34, '456 Pine St', 67000.0, 'Research Scientist', 'Research', '2013-03-10', 8, 9, 4.6, 4.7, 2, 3),
 (100, 'Tina Bell', 37, '789 Elm St', 125780.83100000005, 'IT Administrator', 'IT', '2012-08-20', 10, 8, 4.7, 4.8, 2, 4),
 (101, 'Uma Murphy', 31, '123 Walnut St', 113379.90400000002, 'Data Engineer', 'IT', '2015-01-15', 6, 10, 4.5, 4.6, 1, 2),
 (102, 'Victor Ramirez', 28, '456 Cedar St', 59000.0, 'Customer Success Manager', 'Support', '2016-06-20', 4, 12, 4.3, 4.4, 1, 3),
 (103, 'Wendy Adams', 33, '789 Oak St', 67000.0, 'Marketing Director', 'Marketing', '2013-11-15', 7, 9, 4.6, 4.7, 2, 4),
 (104, 'Xavier Hughes', 29, '123 Pine St', 60000.0, 'HR Specialist', 'HR', '2015-05-10', 4, 11, 4.3, 4.4, 1, 2),
 (105, 'Yasmin Lee', 30, '456 Elm St', 62000.0, 'Financial Advisor', 'Finance', '2015-03-20', 5, 10, 4.4, 4.5, 1, 3),
 (106, 'Zane Cooper', 35, '789 Walnut St', 70000.0, 'Sales Director', 'Sales', '2013-02-25', 8, 9, 3.0999999999999996, 4.7, 2, 4),
 (107, 'Aiden Green', 28, '123 Maple St', 102750.53800000006, 'Junior Developer', 'IT', '2017-09-15', 3, 15, 4.2, 4.3, 0, 2),
 (108, 'Bella Johnson', 31, '456 Oak St', 62000.0, 'Marketing Assistant', 'Marketing', '2015-02-20', 5, 10, 4.4, 4.5, 1, 2),
 (109, 'Caleb Scott', 33, '789 Elm St', 67000.0, 'Business Analyst', 'Business', '2014-07-10', 6, 8, 4.6, 4.7, 1, 3),
 (110, 'Daisy Harris', 29, '123 Cedar St', 59000.0, 'Product Designer', 'Design', '2016-01-15', 4, 12, 4.3, 4.4, 1, 2),
 (111, 'Ethan Lewis', 36, '456 Pine St', 71000.0, 'Project Coordinator', 'Operations', '2011-11-25', 9, 8, 4.7, 4.8, 2, 4),
 (112, 'Fiona Brown', 34, '789 Maple St', 68000.0, 'HR Manager', 'HR', '2012-06-15', 8, 9, 4.6, 4.7, 2, 3),
 (113, 'George White', 31, '123 Oak St', 106293.66000000002, 'Data Analyst', 'IT', '2016-04-20', 5, 11, 4.4, 4.5, 1, 2),
 (114, 'Hannah King', 29, '456 Cedar St', 62000.0, 'Content Strategist', 'Content', '2016-05-15', 4, 12, 4.3, 4.4, 1, 3),
 (115, 'Ian Martinez', 35, '789 Elm St', 70000.0, 'Sales Manager', 'Sales', '2013-01-10', 8, 9, 3.0999999999999996, 4.7, 2, 4),
 (116, 'Julia Turner', 30, '123 Pine St', 63000.0, 'Finance Analyst', 'Finance', '2015-07-15', 5, 10, 4.5, 4.6, 1, 3),
 (117, 'Kyle Roberts', 32, '456 Oak St', 64000.0, 'Product Manager', 'Business', '2014-08-20', 6, 9, 4.4, 4.5, 1, 2),
 (118, 'Lila Davis', 29, '789 Maple St', 59000.0, 'Marketing Specialist', 'Marketing', '2016-03-15', 4, 12, 4.3, 4.4, 1, 3),
 (119, 'Mason Evans', 34, '123 Cedar St', 67000.0, 'UX Designer', 'Design', '2013-09-20', 7, 8, 4.6, 4.7, 2, 4),
 (120, 'Nora Gonzalez', 30, '456 Pine St', 106293.66000000002, 'IT Support Specialist', 'IT', '2015-06-20', 5, 11, 4.4, 4.5, 1, 2),
 (121, 'Oscar Miller', 29, '789 Oak St', 62000.0, 'Research Analyst', 'Research', '2016-10-05', 4, 12, 4.3, 4.4, 1, 3),
 (122, 'Paige Adams', 33, '123 Maple St', 65000.0, 'Content Manager', 'Content', '2014-02-15', 7, 10, 4.5, 4.6, 1, 3),
 (123, 'Quincy Hill', 36, '456 Oak St', 68000.0, 'Public Relations Specialist', 'PR', '2011-09-10', 9, 8, 4.6, 4.7, 2, 4),
 (124, 'Riley Baker', 28, '789 Elm St', 104522.09900000007, 'Data Scientist', 'IT', '2017-07-15', 3, 15, 4.2, 4.3, 0, 2),
 (125, 'Sophia Evans', 31, '123 Pine St', 62000.0, 'SEO Specialist', 'Marketing', '2015-11-01', 5, 11, 4.4, 4.5, 1, 3),
 (126, 'Tyler Martinez', 35, '456 Maple St', 67000.0, 'Sales Analyst', 'Sales', '2013-08-20', 7, 9, 3.0999999999999996, 4.7, 2, 4),
 (127, 'Uma Robinson', 30, '789 Cedar St', 61000.0, 'Marketing Coordinator', 'Marketing', '2015-10-15', 5, 12, 4.3, 4.4, 1, 3),
 (128, 'Vera Long', 28, '123 Elm St', 59000.0, 'Content Developer', 'Content', '2017-01-15', 3, 15, 4.2, 4.3, 0, 2),
 (129, 'William Taylor', 33, '456 Pine St', 64000.0, 'Operations Coordinator', 'Operations', '2014-04-20', 6, 10, 4.4, 4.5, 1, 3),
 (130, 'Xander Wright', 32, '789 Maple St', 63000.0, 'Finance Manager', 'Finance', '2015-12-10', 5, 11, 4.5, 4.6, 1, 2),
 (131, 'Yara Hughes', 29, '123 Cedar St', 60000.0, 'HR Coordinator', 'HR', '2016-02-20', 4, 12, 4.3, 4.4, 1, 2),
 (132, 'Zara Wright', 31, '456 Oak St', 62000.0, 'Business Development Manager', 'Business', '2015-11-25', 5, 10, 4.4, 4.5, 1, 3),
 (133, 'Ariana Lopez', 27, '789 Elm St', 104522.09900000007, 'IT Project Manager', 'IT', '2017-06-15', 3, 12, 4.3, 4.4, 0, 2),
 (134, 'Blake Adams', 30, '123 Pine St', 63000.0, 'Marketing Director', 'Marketing', '2015-04-10', 5, 11, 4.5, 4.6, 1, 3),
 (135, 'Chloe White', 32, '456 Maple St', 62000.0, 'Content Specialist', 'Content', '2016-05-20', 4, 10, 4.4, 4.5, 1, 2),
 (136, 'Daniel Clark', 34, '789 Oak St', 66000.0, 'Research Coordinator', 'Research', '2014-09-05', 6, 9, 4.5, 4.6, 1, 3),
 (137, 'Ella Brown', 29, '123 Cedar St', 61000.0, 'Operations Assistant', 'Operations', '2016-07-20', 4, 12, 4.3, 4.4, 1, 2),
 (138, 'Finn Garcia', 37, '456 Oak St', 120466.14800000003, 'IT Analyst', 'IT', '2012-03-10', 9, 8, 4.7, 4.8, 2, 4),
 (139, 'Gwen Lewis', 30, '789 Maple St', 60000.0, 'Public Relations Coordinator', 'PR', '2015-06-15', 5, 10, 4.4, 4.5, 1, 3),
 (140, 'Holly Martinez', 33, '123 Pine St', 65000.0, 'Content Analyst', 'Content', '2014-08-20', 6, 9, 4.6, 4.7, 1, 2),
 (141, 'Isaac Turner', 29, '456 Cedar St', 62000.0, 'Business Analyst', 'Business', '2016-03-20', 4, 11, 4.3, 4.4, 1, 2),
 (142, 'Jasmine Wright', 32, '789 Elm St', 64000.0, 'Marketing Coordinator', 'Marketing', '2015-12-01', 5, 10, 4.5, 4.6, 1, 3),
 (143, 'Kurt Harris', 28, '123 Maple St', 59000.0, 'Product Manager', 'Product', '2017-04-15', 3, 12, 4.2, 4.3, 0, 2),
 (144, 'Liam Scott', 35, '456 Oak St', 67000.0, 'Operations Analyst', 'Operations', '2012-10-20', 8, 9, 4.5, 4.6, 1, 3),
 (145, 'Maya Thompson', 29, '789 Pine St', 62000.0, 'HR Specialist', 'HR', '2016-01-10', 4, 12, 4.3, 4.4, 1, 2),
 (146, 'Noah Allen', 31, '123 Cedar St', 63000.0, 'Design Specialist', 'Design', '2015-09-15', 5, 10, 4.4, 4.5, 1, 3),
 (147, 'Olivia Campbell', 28, '456 Maple St', 61000.0, 'Finance Coordinator', 'Finance', '2017-05-20', 3, 15, 4.2, 4.3, 0, 2),
 (148, 'Paul Collins', 34, '789 Elm St', 68000.0, 'Sales Specialist', 'Sales', '2012-12-15', 8, 8, 3.0999999999999996, 4.7, 2, 4),
 (149, 'Quinn Diaz', 33, '123 Pine St', 66000.0, 'Marketing Analyst', 'Marketing', '2014-11-25', 7, 9, 4.5, 4.6, 1, 3),
 (150, 'Riley Hernandez', 31, '456 Cedar St', 63000.0, 'Product Analyst', 'Product', '2015-06-20', 5, 11, 4.4, 4.5, 1, 2),
 (151, 'Samantha Wilson', 28, '789 Pine St', 60000.0, 'Operations Manager', 'Operations', '2017-02-15', 3, 12, 4.3, 4.4, 0, 2),
 (152, 'Tyler Lopez', 32, '123 Cedar St', 64000.0, 'Customer Service Manager', 'Support', '2015-08-20', 6, 10, 4.5, 4.6, 1, 3),
 (153, 'Ursula Moore', 30, '456 Maple St', 62000.0, 'Business Development Specialist', 'Business', '2016-12-10', 4, 11, 4.4, 4.5, 1, 2),
 (154, 'Victor White', 29, '789 Elm St', 104522.09900000007, 'IT Coordinator', 'IT', '2016-04-20', 4, 12, 4.3, 4.4, 1, 2),
 (155, 'Wendy Scott', 35, '123 Pine St', 65000.0, 'HR Coordinator', 'HR', '2013-09-15', 7, 9, 4.6, 4.7, 1, 3),
 (156, 'Xander Cooper', 34, '456 Cedar St', 68000.0, 'Content Manager', 'Content', '2012-11-05', 8, 8, 4.6, 4.7, 2, 4),
 (157, 'Yasmine Brooks', 30, '789 Pine St', 60000.0, 'Product Specialist', 'Product', '2015-07-10', 5, 10, 4.4, 4.5, 1, 2),
 (158, 'Zachary King', 31, '123 Maple St', 64000.0, 'Public Relations Manager', 'PR', '2014-06-15', 6, 10, 4.5, 4.6, 1, 3),
 (159, 'Alyssa Reed', 33, '456 Oak St', 63000.0, 'Business Development Manager', 'Business', '2013-12-20', 7, 9, 4.4, 4.5, 2, 4),
 (160, 'Bradley Evans', 29, '789 Cedar St', 62000.0, 'Design Coordinator', 'Design', '2016-03-25', 4, 11, 4.3, 4.4, 1, 2),
 (161, 'Charlotte Murphy', 30, '123 Oak St', 65000.0, 'Sales Specialist', 'Sales', '2015-05-10', 5, 12, 2.9000000000000004, 4.5, 1, 3),
 (162, 'Derek Collins', 32, '456 Maple St', 67000.0, 'Customer Service Manager', 'Support', '2014-04-15', 6, 10, 4.5, 4.6, 1, 2),
 (163, 'Eva Sanchez', 27, '789 Cedar St', 61000.0, 'Product Manager', 'Product', '2017-03-05', 3, 12, 4.2, 4.3, 0, 2),
 (164, 'Frankie Scott', 31, '123 Oak St', 62000.0, 'Operations Coordinator', 'Operations', '2015-10-05', 5, 11, 4.4, 4.5, 1, 2),

In [7]:
%%sql
SELECT COUNT(Name) FROM EMPLOYEE;

 * sqlite:///NewDB.sqlite3
Done.

[(1489,)]

In [8]:
%%sql
SELECT Name, Age, Address FROM EMPLOYEE;

 * sqlite:///NewDB.sqlite3
Done.

[('John Doe', 30, '123 Maple St'),
 ('Alice Johnson', 35, '789 Pine St'),
 ('Bob Brown', 45, '321 Birch St'),
 ('Charlie Davis', 28, '654 Cedar St'),
 ('David Miller', 32, '123 Elm St'),
 ('Eva Taylor', 29, '234 Pine St'),
 ('Frank White', 38, '345 Cedar St'),
 ('Grace Lee', 26, '456 Birch St'),
 ('Henry Walker', 41, '567 Maple St'),
 ('Isabella Harris', 27, '678 Oak St'),
 ('Jack Martin', 34, '789 Pine St'),
 ('Karen Young', 45, '890 Cedar St'),
 ('Liam Carter', 28, '901 Birch St'),
 ('Mia Thompson', 33, '123 Maple St'),
 ('Noah Roberts', 30, '234 Oak St'),
 ('Olivia Lewis', 39, '345 Pine St'),
 ('Paul Green', 27, '456 Cedar St'),
 ('Quinn Scott', 42, '567 Birch St'),
 ('Rachel King', 31, '678 Maple St'),
 ('Samuel Wright', 29, '789 Oak St'),
 ('Tina Hall', 35, '890 Pine St'),
 ('Uma Baker', 40, '901 Cedar St'),
 ('Victor Phillips', 28, '123 Birch St'),
 ('Wendy Campbell', 36, '234 Maple St'),
 ('Xander James', 33, '345 Oak St'),
 ('Yara Flores', 29, '456 Pine St'),
 ('Zachary Morris', 40, '567 Cedar St'),
 ('Anna Rogers', 28, '678 Birch St'),
 ('Brian Nelson', 32, '789 Maple St'),
 ('Catherine Bryant', 30, '890 Oak St'),
 ('Daniel Foster', 34, '901 Pine St'),
 ('Eleanor Reed', 45, '123 Cedar St'),
 ('Francis Diaz', 27, '234 Birch St'),
 ('Gabriella Hughes', 31, '345 Maple St'),
 ('Harry Alexander', 28, '456 Oak St'),
 ('Ivy Brooks', 29, '567 Pine St'),
 ('Jackie Sanders', 36, '678 Cedar St'),
 ('Keith Ross', 33, '789 Birch St'),
 ('Laura Jenkins', 40, '890 Maple St'),
 ('Mike Griffin', 27, '901 Oak St'),
 ('Nina Wallace', 35, '123 Pine St'),
 ('Oscar Daniels', 32, '234 Cedar St'),
 ('Patricia Stewart', 29, '345 Birch St'),
 ('Quentin Collins', 27, '456 Maple St'),
 ('Ruth Bennett', 36, '567 Oak St'),
 ('Steven Hamilton', 33, '678 Pine St'),
 ('Tina Adams', 40, '789 Cedar St'),
 ('Uma Grant', 27, '890 Birch St'),
 ('Victor Mitchell', 36, '901 Maple St'),
 ('Wendy Edwards', 33, '123 Oak St'),
 ('Xander Fox', 28, '234 Pine St'),
 ('Yara Adams', 35, '345 Cedar St'),
 ('Zachary Foster', 33, '456 Birch St'),
 ('Alice Johnson', 28, '789 Elm St'),
 ('Bob Smith', 42, '123 Walnut St'),
 ('Carol Taylor', 30, '456 Cedar St'),
 ('David Brown', 34, '789 Oak St'),
 ('Eva Wilson', 29, '123 Pine St'),
 ('Frank Garcia', 38, '456 Elm St'),
 ('Grace Martinez', 32, '789 Walnut St'),
 ('Henry Robinson', 31, '123 Cedar St'),
 ('Isabella Clark', 27, '456 Oak St'),
 ('Jack White', 35, '789 Pine St'),
 ('Karen Lewis', 40, '123 Elm St'),
 ('Liam Harris', 28, '456 Walnut St'),
 ('Mia Lee', 33, '789 Cedar St'),
 ('Nathan King', 37, '123 Oak St'),
 ('Olivia Scott', 31, '456 Pine St'),
 ('Patrick Turner', 39, '789 Elm St'),
 ('Quinn Rivera', 28, '123 Walnut St'),
 ('Rachel Martinez', 30, '456 Cedar St'),
 ('Sam Parker', 32, '789 Oak St'),
 ('Tina Clark', 34, '123 Pine St'),
 ('Umar Green', 27, '456 Elm St'),
 ('Vanessa Young', 29, '789 Walnut St'),
 ('Walter Hernandez', 33, '123 Cedar St'),
 ('Ximena Cooper', 31, '456 Oak St'),
 ('Yvonne Campbell', 30, '789 Pine St'),
 ('Zachary Long', 35, '123 Elm St'),
 ('Amelia Moore', 28, '456 Walnut St'),
 ('Benjamin Brown', 36, '789 Cedar St'),
 ('Charlotte Davis', 29, '123 Oak St'),
 ('Daniel Gonzalez', 38, '456 Pine St'),
 ('Emma Hall', 32, '789 Elm St'),
 ('Frankie Allen', 33, '123 Walnut St'),
 ('Grace King', 29, '456 Cedar St'),
 ('Henry Roberts', 35, '789 Oak St'),
 ('Isabelle Turner', 30, '123 Pine St'),
 ('Jackie Clark', 37, '456 Elm St'),
 ('Kara Edwards', 31, '789 Walnut St'),
 ('Liam Scott', 27, '123 Cedar St'),
 ('Molly Hughes', 33, '456 Oak St'),
 ('Nate Williams', 29, '789 Pine St'),
 ('Olivia Collins', 32, '123 Elm St'),
 ('Paul Foster', 38, '456 Walnut St'),
 ('Quinn Howard', 30, '789 Cedar St'),
 ('Rose Ward', 29, '123 Oak St'),
 ('Steven Bailey', 34, '456 Pine St'),
 ('Tina Bell', 37, '789 Elm St'),
 ('Uma Murphy', 31, '123 Walnut St'),
 ('Victor Ramirez', 28, '456 Cedar St'),
 ('Wendy Adams', 33, '789 Oak St'),
 ('Xavier Hughes', 29, '123 Pine St'),
 ('Yasmin Lee', 30, '456 Elm St'),
 ('Zane Cooper', 35, '789 Walnut St'),
 ('Aiden Green', 28, '123 Maple St'),
 ('Bella Johnson', 31, '456 Oak St'),
 ('Caleb Scott', 33, '789 Elm St'),
 ('Daisy Harris', 29, '123 Cedar St'),
 ('Ethan Lewis', 36, '456 Pine St'),
 ('Fiona Brown', 34, '789 Maple St'),
 ('George White', 31, '123 Oak St'),
 ('Hannah King', 29, '456 Cedar St'),
 ('Ian Martinez', 35, '789 Elm St'),
 ('Julia Turner', 30, '123 Pine St'),
 ('Kyle Roberts', 32, '456 Oak St'),
 ('Lila Davis', 29, '789 Maple St'),
 ('Mason Evans', 34, '123 Cedar St'),
 ('Nora Gonzalez', 30, '456 Pine St'),
 ('Oscar Miller', 29, '789 Oak St'),
 ('Paige Adams', 33, '123 Maple St'),
 ('Quincy Hill', 36, '456 Oak St'),
 ('Riley Baker', 28, '789 Elm St'),
 ('Sophia Evans', 31, '123 Pine St'),
 ('Tyler Martinez', 35, '456 Maple St'),
 ('Uma Robinson', 30, '789 Cedar St'),
 ('Vera Long', 28, '123 Elm St'),
 ('William Taylor', 33, '456 Pine St'),
 ('Xander Wright', 32, '789 Maple St'),
 ('Yara Hughes', 29, '123 Cedar St'),
 ('Zara Wright', 31, '456 Oak St'),
 ('Ariana Lopez', 27, '789 Elm St'),
 ('Blake Adams', 30, '123 Pine St'),
 ('Chloe White', 32, '456 Maple St'),
 ('Daniel Clark', 34, '789 Oak St'),
 ('Ella Brown', 29, '123 Cedar St'),
 ('Finn Garcia', 37, '456 Oak St'),
 ('Gwen Lewis', 30, '789 Maple St'),
 ('Holly Martinez', 33, '123 Pine St'),
 ('Isaac Turner', 29, '456 Cedar St'),
 ('Jasmine Wright', 32, '789 Elm St'),
 ('Kurt Harris', 28, '123 Maple St'),
 ('Liam Scott', 35, '456 Oak St'),
 ('Maya Thompson', 29, '789 Pine St'),
 ('Noah Allen', 31, '123 Cedar St'),
 ('Olivia Campbell', 28, '456 Maple St'),
 ('Paul Collins', 34, '789 Elm St'),
 ('Quinn Diaz', 33, '123 Pine St'),
 ('Riley Hernandez', 31, '456 Cedar St'),
 ('Samantha Wilson', 28, '789 Pine St'),
 ('Tyler Lopez', 32, '123 Cedar St'),
 ('Ursula Moore', 30, '456 Maple St'),
 ('Victor White', 29, '789 Elm St'),
 ('Wendy Scott', 35, '123 Pine St'),
 ('Xander Cooper', 34, '456 Cedar St'),
 ('Yasmine Brooks', 30, '789 Pine St'),
 ('Zachary King', 31, '123 Maple St'),
 ('Alyssa Reed', 33, '456 Oak St'),
 ('Bradley Evans', 29, '789 Cedar St'),
 ('Charlotte Murphy', 30, '123 Oak St'),
 ('Derek Collins', 32, '456 Maple St'),
 ('Eva Sanchez', 27, '789 Cedar St'),
 ('Frankie Scott', 31, '123 Oak St'),
 ('Gina Cooper', 30, '456 Pine St'),
 ('Hank Wright', 35, '789 Oak St'),
 ('Iris Lee', 29, '123 Maple St'),
 ('Jack Morris', 34, '456 Oak St'),
 ('Kelsey Davis', 32, '789 Pine St'),
 ('Leo Bennett', 31, '123 Cedar St'),
 ('Mia Gray', 29, '456 Maple St'),
 ('Nina Price', 28, '789 Cedar St'),
 ('Oscar Wright', 30, '456 Maple St'),
 ('Parker Reed', 27, '789 Pine St'),
 ('Quinn Adams', 33, '123 Cedar St'),
 ('Riley Evans', 32, '456 Pine St'),
 ('Sophia Knight', 29, '789 Oak St'),
 ('Tina Harris', 30, '123 Pine St'),
 ('Ulysses Clark', 33, '456 Oak St'),
 ('Violet Moore', 31, '789 Cedar St'),
 ('Willow Young', 28, '123 Oak St'),
 ('Xena Gray', 29, '456 Maple St'),
 ('Yara Miller', 32, '789 Oak St'),
 ('Zane Davis', 34, '123 Pine St'),
 ('Aidan Carter', 28, '123 Birch St'),
 ('Bella Martinez', 31, '456 Birch St'),
 ('Cameron Lee', 29, '789 Birch St'),
 ('Daisy Taylor', 33, '123 Elm St'),
 ('Ethan White', 30, '456 Elm St'),
 ('Fiona Green', 28, '789 Elm St'),
 ('George Harris', 32, '123 Maple St'),
 ('Holly Adams', 29, '456 Maple St'),
 ('Ian Young', 34, '789 Maple St'),
 ('Jasmine Clark', 27, '123 Oak St'),
 ('Kevin Scott', 31, '456 Oak St'),
 ('Laura Nelson', 33, '789 Oak St'),
 ('Michael Lopez', 29, '123 Birch St'),
 ('Natalie Turner', 31, '456 Birch St'),
 ('Oliver Walker', 28, '789 Birch St'),
 ('Peyton Wright', 34, '123 Elm St'),
 ('Quincy Morgan', 32, '456 Elm St'),
 ('Rachel Morris', 30, '789 Elm St'),
 ('Sam Mitchell', 27, '123 Maple St'),
 ('Taylor Hughes', 31, '456 Maple St'),
 ('Ursula Rivera', 29, '789 Maple St'),
 ('Victor Turner', 32, '123 Oak St'),
 ('Wendy Allen', 30, '456 Oak St'),
 ('Xander Brooks', 33, '789 Oak St'),
 ('Yvonne Carter', 31, '123 Birch St'),
 ('Zachary Morris', 29, '456 Birch St'),
 ('Alyssa Bailey', 34, '789 Birch St'),
 ('Brandon King', 30, '123 Elm St'),
 ('Clara Morgan', 27, '456 Elm St'),
 ('Derek Clark', 31, '789 Elm St'),
 ('Eva Lewis', 28, '123 Maple St'),
 ('Frank Turner', 34, '456 Maple St'),
 ('Grace Miller', 29, '789 Maple St'),
 ('Hannah Allen', 30, '123 Oak St'),
 ('Ian Thompson', 31, '456 Oak St'),
 ('Julia Carter', 29, '789 Oak St'),
 ('Kevin Moore', 32, '123 Pine St'),
 ('Laura Robinson', 30, '456 Pine St'),
 ('Mark Davis', 31, '789 Pine St'),
 ('Nina Evans', 29, '123 Oak St'),
 ('Oscar Taylor', 34, '456 Oak St'),
 ('Paige Miller', 32, '789 Oak St'),
 ('Quinn Wright', 30, '123 Maple St'),
 ('Ryan Clark', 29, '456 Maple St'),
 ('Samantha Turner', 31, '789 Maple St'),
 ('Thomas Allen', 28, '123 Birch St'),
 ('Uma Patel', 33, '456 Birch St'),
 ('Victor Lewis', 34, '789 Birch St'),
 ('Wendy Harris', 30, '123 Elm St'),
 ('Xander Walker', 29, '456 Elm St'),
 ('Yara White', 31, '789 Elm St'),
 ('Zachary Miller', 30, '123 Maple St'),
 ('Ariana Davis', 29, '456 Maple St'),
 ('Brandon Evans', 33, '789 Maple St'),
 ('Catherine Lopez', 31, '123 Oak St'),
 ('Daniel Martin', 32, '456 Oak St'),
 ('Emily Harris', 29, '789 Oak St'),
 ('Felix Collins', 34, '123 Pine St'),
 ('Gina Wood', 31, '456 Pine St'),
 ('Henry Green', 29, '789 Pine St'),
 ('Ivy Wright', 32, '123 Birch St'),
 ('Jack Lee', 30, '456 Birch St'),
 ('Kelly Young', 29, '789 Birch St'),
 ('Liam Clark', 31, '123 Elm St'),
 ('Megan Thompson', 30, '456 Elm St'),
 ('Nathan Evans', 33, '789 Elm St'),
 ('Olivia Martinez', 28, '123 Maple St'),
 ('Patrick Brown', 31, '456 Maple St'),
 ('Quinn Cooper', 29, '789 Maple St'),
 ('Rachel Moore', 34, '123 Oak St'),
 ('Sam Rogers', 30, '456 Oak St'),
 ('Tina Williams', 29, '789 Oak St'),
 ('Ulysses Harris', 32, '123 Pine St'),
 ('Vera Johnson', 31, '456 Pine St'),
 ('Will Scott', 30, '789 Pine St'),
 ('Xena Garcia', 33, '123 Birch St'),
 ('Yvonne Rodriguez', 30, '456 Birch St'),
 ('Zane Smith', 29, '789 Birch St'),
 ('Alyssa Wilson', 31, '123 Elm St'),
 ('Brandon Young', 32, '456 Elm St'),
 ('Cindy Brown', 30, '789 Elm St'),
 ('David Lee', 33, '123 Maple St'),
 ('Ella King', 31, '456 Maple St'),
 ('Felix Martinez', 30, '789 Maple St'),
 ('Grace Turner', 29, '123 Oak St'),
 ('Henry Roberts', 34, '456 Oak St'),
 ('Ivy Lee', 31, '789 Oak St'),
 ('James Anderson', 32, '123 Pine St'),
 ('Katherine Thompson', 30, '456 Pine St'),
 ('Liam Moore', 29, '789 Pine St'),
 ('Maya Brown', 31, '123 Birch St'),
 ('Noah Adams', 34, '456 Birch St'),
 ('Olivia Scott', 32, '789 Birch St'),
 ('Paul Lewis', 29, '123 Elm St'),
 ('Quinn Adams', 30, '456 Elm St'),
 ('Rachel Lewis', 33, '789 Elm St'),
 ('Sam Adams', 31, '123 Maple St'),
 ('Tina Evans', 28, '456 Maple St'),
 ('Ulysses Scott', 32, '789 Maple St'),
 ('Vera Lee', 31, '123 Oak St'),
 ('Will Turner', 30, '456 Oak St'),
 ('Xena Adams', 33, '789 Oak St'),
 ('Yvonne Lee', 30, '123 Maple St'),
 ('Zane Williams', 29, '456 Maple St'),
 ('Laura Robinson', 30, '456 Pine St'),
 ('Mark Davis', 31, '789 Pine St'),
 ('Nina Evans', 29, '123 Oak St'),
 ('Oscar Taylor', 34, '456 Oak St'),
 ('Paige Miller', 32, '789 Oak St'),
 ('Quinn Wright', 30, '123 Maple St'),
 ('Ryan Clark', 29, '456 Maple St'),
 ('Samantha Turner', 31, '789 Maple St'),
 ('Thomas Allen', 28, '123 Birch St'),
 ('Uma Patel', 33, '456 Birch St'),
 ('Victor Lewis', 34, '789 Birch St'),
 ('Wendy Harris', 30, '123 Elm St'),
 ('Xander Walker', 29, '456 Elm St'),
 ('Yara White', 31, '789 Elm St'),
 ('Zachary Miller', 30, '123 Maple St'),
 ('Ariana Davis', 29, '456 Maple St'),
 ('Brandon Evans', 33, '789 Maple St'),
 ('Catherine Lopez', 31, '123 Oak St'),
 ('Daniel Martin', 32, '456 Oak St'),
 ('Emily Harris', 29, '789 Oak St'),
 ('Felix Collins', 34, '123 Pine St'),
 ('Gina Wood', 31, '456 Pine St'),
 ('Henry Green', 29, '789 Pine St'),
 ('Ivy Wright', 32, '123 Birch St'),
 ('Jack Lee', 30, '456 Birch St'),
 ('Kelly Young', 29, '789 Birch St'),
 ('Liam Clark', 31, '123 Elm St'),
 ('Megan Thompson', 30, '456 Elm St'),
 ('Nathan Evans', 33, '789 Elm St'),
 ('Olivia Martinez', 28, '123 Maple St'),
 ('Patrick Brown', 31, '456 Maple St'),
 ('Quinn Cooper', 29, '789 Maple St'),
 ('Rachel Moore', 34, '123 Oak St'),
 ('Sam Rogers', 30, '456 Oak St'),
 ('Tina Williams', 29, '789 Oak St'),
 ('Ulysses Harris', 32, '123 Pine St'),
 ('Vera Johnson', 31, '456 Pine St'),
 ('Will Scott', 30, '789 Pine St'),
 ('Xena Garcia', 33, '123 Birch St'),
 ('Yvonne Rodriguez', 30, '456 Birch St'),
 ('Zane Smith', 29, '789 Birch St'),
 ('Alyssa Wilson', 31, '123 Elm St'),
 ('Brandon Young', 32, '456 Elm St'),
 ('Cindy Brown', 30, '789 Elm St'),
 ('David Lee', 33, '123 Maple St'),
 ('Ella King', 31, '456 Maple St'),
 ('Felix Martinez', 30, '789 Maple St'),
 ('Grace Turner', 29, '123 Oak St'),
 ('Henry Roberts', 34, '456 Oak St'),
 ('Ivy Lee', 31, '789 Oak St'),
 ('James Anderson', 32, '123 Pine St'),
 ('Katherine Thompson', 30, '456 Pine St'),
 ('Liam Moore', 29, '789 Pine St'),
 ('Maya Brown', 31, '123 Birch St'),
 ('Noah Adams', 34, '456 Birch St'),
 ('Olivia Scott', 32, '789 Birch St'),
 ('Paul Lewis', 29, '123 Elm St'),
 ('Quinn Adams', 30, '456 Elm St'),
 ('Rachel Lewis', 33, '789 Elm St'),
 ('Sam Adams', 31, '123 Maple St'),
 ('Tina Evans', 28, '456 Maple St'),
 ('Ulysses Scott', 32, '789 Maple St'),
 ('Vera Lee', 31, '123 Oak St'),
 ('Will Turner', 30, '456 Oak St'),
 ('Xena Adams', 33, '789 Oak St'),
 ('Yvonne Lee', 30, '123 Maple St'),
 ('Zane Williams', 29, '456 Maple St'),
 ('Aiden Gray', 34, '123 Birch St'),
 ('Becca Davis', 29, '456 Birch St'),
 ('Carlos Martinez', 31, '789 Birch St'),
 ('Diana Brown', 32, '123 Elm St'),
 ('Ethan Harris', 29, '456 Elm St'),
 ('Fiona Clark', 30, '789 Elm St'),
 ('George Wilson', 35, '123 Maple St'),
 ('Hannah Lewis', 31, '456 Maple St'),
 ('Ian Martinez', 33, '789 Maple St'),
 ('Jasmine Adams', 30, '123 Oak St'),
 ('Kevin White', 34, '456 Oak St'),
 ('Laura Green', 32, '789 Oak St'),
 ('Matthew Smith', 30, '123 Pine St'),
 ('Natalie Brown', 29, '456 Pine St'),
 ('Oscar Johnson', 31, '789 Pine St'),
 ('Paige Green', 33, '123 Birch St'),
 ('Quincy Harris', 30, '456 Birch St'),
 ('Riley Carter', 31, '789 Birch St'),
 ('Sophie Turner', 28, '123 Elm St'),
 ('Thomas King', 33, '456 Elm St'),
 ('Uma Patel', 30, '789 Elm St'),
 ('Victor Brown', 31, '123 Maple St'),
 ('Wendy Green', 32, '456 Maple St'),
 ('Xander Lee', 30, '789 Maple St'),
 ('Yara Adams', 31, '123 Oak St'),
 ('Zane Walker', 29, '456 Oak St'),
 ('Amelia Scott', 32, '789 Oak St'),
 ('Bradley Moore', 30, '123 Pine St'),
 ('Catherine Carter', 31, '456 Pine St'),
 ('Derek Taylor', 33, '789 Pine St'),
 ('Emily Evans', 30, '123 Birch St'),
 ('Franklin White', 31, '456 Birch St'),
 ('Grace Adams', 32, '789 Birch St'),
 ('Harrison Davis', 30, '123 Elm St'),
 ('Ivy Robinson', 31, '456 Elm St'),
 ('Jack Lee', 34, '789 Elm St'),
 ('Kara Scott', 30, '123 Maple St'),
 ('Liam Williams', 33, '456 Maple St'),
 ('Mia Wright', 32, '789 Maple St'),
 ('Noah Smith', 30, '123 Oak St'),
 ('Olivia Johnson', 29, '456 Oak St'),
 ('Paul Davis', 31, '789 Oak St'),
 ('Quinn Evans', 28, '123 Pine St'),
 ('Rachel Scott', 33, '456 Pine St'),
 ('Sam Taylor', 32, '789 Pine St'),
 ('Tina White', 31, '123 Birch St'),
 ('Ulysses Brown', 30, '456 Birch St'),
 ('Vera White', 29, '789 Birch St'),
 ('Will Carter', 30, '123 Elm St'),
 ('Xena Wilson', 33, '456 Elm St'),
 ('Yvonne Scott', 31, '789 Elm St'),
 ('Zane Harris', 32, '123 Maple St'),
 ('Aiden Martinez', 29, '456 Maple St'),
 ('Becca Wilson', 31, '789 Maple St'),
 ('Carlos Adams', 30, '123 Oak St'),
 ('Diana Robinson', 32, '456 Oak St'),
 ('Eric Wright', 34, '789 Oak St'),
 ('Fiona Turner', 29, '123 Pine St'),
 ('George Murphy', 31, '456 Pine St'),
 ('Hannah Carter', 32, '789 Pine St'),
 ('Ian Clark', 30, '123 Birch St'),
 ('Julia Davis', 34, '456 Birch St'),
 ('Aidan Brooks', 31, '123 Elm St'),
 ('Brianna Scott', 29, '456 Elm St'),
 ('Carl Turner', 32, '789 Elm St'),
 ('Diana Clark', 30, '123 Maple St'),
 ('Edward Hughes', 33, '456 Maple St'),
 ('Fiona Bell', 28, '789 Maple St'),
 ('George Allen', 32, '123 Oak St'),
 ('Hannah Collins', 31, '456 Oak St'),
 ('Ian Reed', 30, '789 Oak St'),
 ('Jasmine Young', 29, '123 Pine St'),
 ('Kyle Anderson', 34, '456 Pine St'),
 ('Laura Evans', 31, '789 Pine St'),
 ('Michael Green', 30, '123 Birch St'),
 ('Nora Phillips', 32, '456 Birch St'),
 ('Oliver Wright', 31, '789 Birch St'),
 ('Paige Turner', 29, '123 Elm St'),
 ('Quincy Clark', 33, '456 Elm St'),
 ('Rachel King', 30, '789 Elm St'),
 ('Steve Martinez', 34, '123 Maple St'),
 ('Tiffany Adams', 32, '456 Maple St'),
 ('Ursula Green', 31, '789 Maple St'),
 ('Victor Lewis', 30, '123 Oak St'),
 ('Wendy Scott', 29, '456 Oak St'),
 ('Xander Roberts', 34, '789 Oak St'),
 ('Yara Turner', 33, '123 Pine St'),
 ('Zachary Wilson', 30, '456 Pine St'),
 ('Alice Hughes', 31, '789 Pine St'),
 ('Bradley Adams', 32, '123 Birch St'),
 ('Catherine Morgan', 34, '456 Birch St'),
 ('Daniel Rodriguez', 31, '789 Birch St'),
 ('Emma Wilson', 29, '123 Elm St'),
 ('Franklin Adams', 33, '456 Elm St'),
 ('Gina Clark', 31, '789 Elm St'),
 ('Harry Johnson', 30, '123 Maple St'),
 ('Isabella Walker', 28, '456 Maple St'),
 ('Jacob White', 32, '789 Maple St'),
 ('Kylie Moore', 31, '123 Oak St'),
 ('Leo Martin', 30, '456 Oak St'),
 ('Mia Lewis', 29, '789 Oak St'),
 ('Noah Taylor', 32, '123 Pine St'),
 ('Olivia Miller', 31, '456 Pine St'),
 ('Patrick Martinez', 34, '789 Pine St'),
 ('Quinn Moore', 29, '123 Birch St'),
 ('Riley Adams', 31, '456 Birch St'),
 ('Sophia Lewis', 30, '789 Birch St'),
 ('Thomas Wilson', 33, '123 Elm St'),
 ('Uma Robinson', 31, '456 Elm St'),
 ('Vera King', 34, '789 Elm St'),
 ('William Scott', 32, '123 Maple St'),
 ('Xena Lewis', 30, '456 Maple St'),
 ('Yvette Turner', 29, '789 Maple St'),
 ('Zachary Taylor', 31, '123 Oak St'),
 ('Anna Miller', 34, '456 Oak St'),
 ('Brian Martin', 33, '789 Oak St'),
 ('Catherine Young', 31, '123 Pine St'),
 ('David Green', 30, '456 Pine St'),
 ('Eva White', 32, '789 Pine St'),
 ('Frank Moore', 31, '123 Birch St'),
 ('Grace Johnson', 29, '456 Birch St'),
 ('Henry Davis', 31, '789 Birch St'),
 ('Isabelle Smith', 32, '123 Elm St'),
 ('Jack Brown', 33, '456 Elm St'),
 ('Kimberly Lee', 34, '789 Elm St'),
 ('Laura Adams', 30, '123 Maple St'),
 ('Matthew Davis', 31, '456 Maple St'),
 ('Nina Clark', 32, '789 Maple St'),
 ('Oscar Wilson', 29, '123 Oak St'),
 ('Paula Davis', 34, '456 Oak St'),
 ('Quincy Adams', 30, '789 Oak St'),
 ('Rachel Smith', 31, '123 Pine St'),
 ('Samuel Johnson', 32, '456 Pine St'),
 ('Tina Green', 30, '789 Pine St'),
 ('Ulysses Wright', 31, '123 Birch St'),
 ('Vera Adams', 29, '456 Birch St'),
 ('William Lewis', 34, '789 Birch St'),
 ('Xander Martin', 33, '123 Elm St'),
 ('Yvonne White', 30, '456 Elm St'),
 ('Zachary Lee', 31, '789 Elm St'),
 ('John David', 30, None),
 ('Aiden Lee', 29, '123 Maple St'),
 ('Olivia Adams', 27, '789 Elm St'),
 ('John Doe', 30, '123 Maple St'),
 ('Alice Johnson', 35, '789 Pine St'),
 ('Bob Brown', 45, '321 Birch St'),
 ('Charlie Davis', 28, '654 Cedar St'),
 ('David Miller', 32, '123 Elm St'),
 ('Eva Taylor', 29, '234 Pine St'),
 ('Frank White', 38, '345 Cedar St'),
 ('Grace Lee', 26, '456 Birch St'),
 ('Henry Walker', 41, '567 Maple St'),
 ('Isabella Harris', 27, '678 Oak St'),
 ('Jack Martin', 34, '789 Pine St'),
 ('Karen Young', 45, '890 Cedar St'),
 ('Liam Carter', 28, '901 Birch St'),
 ('Mia Thompson', 33, '123 Maple St'),
 ('Noah Roberts', 30, '234 Oak St'),
 ('Olivia Lewis', 39, '345 Pine St'),
 ('Paul Green', 27, '456 Cedar St'),
 ('Quinn Scott', 42, '567 Birch St'),
 ('Rachel King', 31, '678 Maple St'),
 ('Samuel Wright', 29, '789 Oak St'),
 ('Tina Hall', 35, '890 Pine St'),
 ('Uma Baker', 40, '901 Cedar St'),
 ('Victor Phillips', 28, '123 Birch St'),
 ('Wendy Campbell', 36, '234 Maple St'),
 ('Xander James', 33, '345 Oak St'),
 ('Yara Flores', 29, '456 Pine St'),
 ('Zachary Morris', 40, '567 Cedar St'),
 ('Anna Rogers', 28, '678 Birch St'),
 ('Brian Nelson', 32, '789 Maple St'),
 ('Catherine Bryant', 30, '890 Oak St'),

In [9]:
%%sql
SELECT * FROM employee WHERE Name = 'Zachary Lee';

 * sqlite:///NewDB.sqlite3
Done.

[(495, 'Zachary Lee', 31, '789 Elm St', 63000.0, 'Design Manager', 'Design', '2016-03-20', 5, 9, 4.3, 4.4, 1, 2),
 (993, 'Zachary Lee', 31, '789 Elm St', 63000.0, 'Design Manager', 'Design', '2016-03-20', 5, 9, 4.3, 4.4, 1, 2),
 (1491, 'Zachary Lee', 31, '789 Elm St', 63000.0, 'Design Manager', 'Design', '2016-03-20', 5, 9, 4.3, 4.4, 1, 2)]

Retrieve the details of employees who have a salary greater than 60000.

In [10]:
%%sql
SELECT  Name, Salary FROM employee WHERE Salary > 60000;

 * sqlite:///NewDB.sqlite3
Done.

[('John Doe', 71500.0),
 ('Alice Johnson', 65000.0),
 ('Bob Brown', 80000.0),
 ('David Miller', 108065.22100000002),
 ('Frank White', 127552.39200000007),
 ('Henry Walker', 138181.75800000006),
 ('Jack Martin', 111608.34300000001),
 ('Karen Young', 85000.0),
 ('Mia Thompson', 109836.78200000004),
 ('Noah Roberts', 104522.09900000007),
 ('Olivia Lewis', 70000.0),
 ('Quinn Scott', 76000.0),
 ('Samuel Wright', 102750.53800000006),
 ('Tina Hall', 64000.0),
 ('Uma Baker', 75000.0),
 ('Wendy Campbell', 65000.0),
 ('Xander James', 63000.0),
 ('Zachary Morris', 77000.0),
 ('Brian Nelson', 108065.22100000002),
 ('Daniel Foster', 111608.34300000001),
 ('Eleanor Reed', 78000.0),
 ('Harry Alexander', 100978.97700000006),
 ('Jackie Sanders', 65000.0),
 ('Keith Ross', 111608.34300000001),
 ('Laura Jenkins', 74000.0),
 ('Nina Wallace', 113379.90400000002),
 ('Oscar Daniels', 108065.22100000002),
 ('Quentin Collins', 97435.85500000007),
 ('Ruth Bennett', 65000.0),
 ('Steven Hamilton', 111608.34300000001),
 ('Tina Adams', 74000.0),
 ('Victor Mitchell', 64000.0),
 ('Wendy Edwards', 108065.22100000002),
 ('Yara Adams', 65000.0),
 ('Zachary Foster', 111608.34300000001),
 ('Bob Smith', 145268.0020000001),
 ('Carol Taylor', 63000.0),
 ('David Brown', 68000.0),
 ('Eva Wilson', 61000.0),
 ('Frank Garcia', 75000.0),
 ('Grace Martinez', 66000.0),
 ('Henry Robinson', 65000.0),
 ('Jack White', 69000.0),
 ('Karen Lewis', 74000.0),
 ('Mia Lee', 116923.02600000003),
 ('Nathan King', 72000.0),
 ('Olivia Scott', 64000.0),
 ('Patrick Turner', 70000.0),
 ('Rachel Martinez', 63000.0),
 ('Sam Parker', 116923.02600000003),
 ('Tina Clark', 67000.0),
 ('Walter Hernandez', 65000.0),
 ('Ximena Cooper', 64000.0),
 ('Yvonne Campbell', 62000.0),
 ('Zachary Long', 124009.27000000005),
 ('Benjamin Brown', 68000.0),
 ('Charlotte Davis', 61000.0),
 ('Daniel Gonzalez', 72000.0),
 ('Emma Hall', 64000.0),
 ('Frankie Allen', 118694.58700000004),
 ('Henry Roberts', 122237.70900000005),
 ('Isabelle Turner', 62000.0),
 ('Jackie Clark', 72000.0),
 ('Kara Edwards', 63000.0),
 ('Liam Scott', 102750.53800000006),
 ('Molly Hughes', 65000.0),
 ('Nate Williams', 61000.0),
 ('Olivia Collins', 66000.0),
 ('Paul Foster', 71000.0),
 ('Quinn Howard', 63000.0),
 ('Steven Bailey', 67000.0),
 ('Tina Bell', 125780.83100000005),
 ('Uma Murphy', 113379.90400000002),
 ('Wendy Adams', 67000.0),
 ('Yasmin Lee', 62000.0),
 ('Zane Cooper', 70000.0),
 ('Aiden Green', 102750.53800000006),
 ('Bella Johnson', 62000.0),
 ('Caleb Scott', 67000.0),
 ('Ethan Lewis', 71000.0),
 ('Fiona Brown', 68000.0),
 ('George White', 106293.66000000002),
 ('Hannah King', 62000.0),
 ('Ian Martinez', 70000.0),
 ('Julia Turner', 63000.0),
 ('Kyle Roberts', 64000.0),
 ('Mason Evans', 67000.0),
 ('Nora Gonzalez', 106293.66000000002),
 ('Oscar Miller', 62000.0),
 ('Paige Adams', 65000.0),
 ('Quincy Hill', 68000.0),
 ('Riley Baker', 104522.09900000007),
 ('Sophia Evans', 62000.0),
 ('Tyler Martinez', 67000.0),
 ('Uma Robinson', 61000.0),
 ('William Taylor', 64000.0),
 ('Xander Wright', 63000.0),
 ('Zara Wright', 62000.0),
 ('Ariana Lopez', 104522.09900000007),
 ('Blake Adams', 63000.0),
 ('Chloe White', 62000.0),
 ('Daniel Clark', 66000.0),
 ('Ella Brown', 61000.0),
 ('Finn Garcia', 120466.14800000003),
 ('Holly Martinez', 65000.0),
 ('Isaac Turner', 62000.0),
 ('Jasmine Wright', 64000.0),
 ('Liam Scott', 67000.0),
 ('Maya Thompson', 62000.0),
 ('Noah Allen', 63000.0),
 ('Olivia Campbell', 61000.0),
 ('Paul Collins', 68000.0),
 ('Quinn Diaz', 66000.0),
 ('Riley Hernandez', 63000.0),
 ('Tyler Lopez', 64000.0),
 ('Ursula Moore', 62000.0),
 ('Victor White', 104522.09900000007),
 ('Wendy Scott', 65000.0),
 ('Xander Cooper', 68000.0),
 ('Zachary King', 64000.0),
 ('Alyssa Reed', 63000.0),
 ('Bradley Evans', 62000.0),
 ('Charlotte Murphy', 65000.0),
 ('Derek Collins', 67000.0),
 ('Eva Sanchez', 61000.0),
 ('Frankie Scott', 62000.0),
 ('Hank Wright', 67000.0),
 ('Iris Lee', 62000.0),
 ('Jack Morris', 67000.0),
 ('Kelsey Davis', 63000.0),
 ('Leo Bennett', 65000.0),
 ('Mia Gray', 61000.0),
 ('Oscar Wright', 63000.0),
 ('Quinn Adams', 64000.0),
 ('Riley Evans', 109836.78200000004),
 ('Sophia Knight', 63000.0),
 ('Tina Harris', 62000.0),
 ('Ulysses Clark', 65000.0),
 ('Xena Gray', 61000.0),
 ('Yara Miller', 64000.0),
 ('Zane Davis', 67000.0),
 ('Bella Martinez', 62000.0),
 ('Cameron Lee', 61000.0),
 ('Daisy Taylor', 64000.0),
 ('Ethan White', 111608.34300000001),
 ('George Harris', 65000.0),
 ('Holly Adams', 62000.0),
 ('Ian Young', 68000.0),
 ('Jasmine Clark', 61000.0),
 ('Kevin Scott', 63000.0),
 ('Laura Nelson', 64000.0),
 ('Michael Lopez', 62000.0),
 ('Oliver Walker', 108065.22100000002),
 ('Peyton Wright', 64000.0),
 ('Quincy Morgan', 63000.0),
 ('Rachel Morris', 62000.0),
 ('Taylor Hughes', 62000.0),
 ('Ursula Rivera', 61000.0),
 ('Victor Turner', 65000.0),
 ('Wendy Allen', 63000.0),
 ('Xander Brooks', 109836.78200000004),
 ('Yvonne Carter', 61000.0),
 ('Alyssa Bailey', 62000.0),
 ('Brandon King', 64000.0),
 ('Clara Morgan', 106293.66000000002),
 ('Derek Clark', 62000.0),
 ('Eva Lewis', 61000.0),
 ('Frank Turner', 65000.0),
 ('Grace Miller', 62000.0),
 ('Hannah Allen', 63000.0),
 ('Ian Thompson', 62000.0),
 ('Kevin Moore', 64000.0),
 ('Laura Robinson', 62000.0),
 ('Mark Davis', 64000.0),
 ('Nina Evans', 61000.0),
 ('Oscar Taylor', 67000.0),
 ('Paige Miller', 65000.0),
 ('Quinn Wright', 62000.0),
 ('Ryan Clark', 106293.66000000002),
 ('Samantha Turner', 64000.0),
 ('Thomas Allen', 61000.0),
 ('Uma Patel', 62000.0),
 ('Victor Lewis', 63000.0),
 ('Wendy Harris', 64000.0),
 ('Yara White', 62000.0),
 ('Zachary Miller', 63000.0),
 ('Ariana Davis', 61000.0),
 ('Brandon Evans', 64000.0),
 ('Catherine Lopez', 109836.78200000004),
 ('Daniel Martin', 63000.0),
 ('Emily Harris', 61000.0),
 ('Felix Collins', 65000.0),
 ('Gina Wood', 62000.0),
 ('Ivy Wright', 62000.0),
 ('Jack Lee', 63000.0),
 ('Kelly Young', 108065.22100000002),
 ('Liam Clark', 62000.0),
 ('Megan Thompson', 61000.0),
 ('Nathan Evans', 62000.0),
 ('Patrick Brown', 62000.0),
 ('Quinn Cooper', 61000.0),
 ('Rachel Moore', 65000.0),
 ('Sam Rogers', 111608.34300000001),
 ('Ulysses Harris', 64000.0),
 ('Vera Johnson', 62000.0),
 ('Will Scott', 63000.0),
 ('Xena Garcia', 64000.0),
 ('Yvonne Rodriguez', 62000.0),
 ('Alyssa Wilson', 62000.0),
 ('Brandon Young', 63000.0),
 ('Cindy Brown', 61000.0),
 ('David Lee', 62000.0),
 ('Ella King', 113379.90400000002),
 ('Felix Martinez', 62000.0),
 ('Grace Turner', 61000.0),
 ('Henry Roberts', 67000.0),
 ('Ivy Lee', 63000.0),
 ('James Anderson', 62000.0),
 ('Katherine Thompson', 61000.0),
 ('Maya Brown', 62000.0),
 ('Noah Adams', 64000.0),
 ('Olivia Scott', 63000.0),
 ('Quinn Adams', 62000.0),
 ('Rachel Lewis', 63000.0),
 ('Sam Adams', 108065.22100000002),
 ('Tina Evans', 62000.0),
 ('Ulysses Scott', 63000.0),
 ('Vera Lee', 62000.0),
 ('Will Turner', 61000.0),
 ('Xena Adams', 64000.0),
 ('Yvonne Lee', 62000.0),
 ('Laura Robinson', 62000.0),
 ('Mark Davis', 64000.0),
 ('Nina Evans', 61000.0),
 ('Oscar Taylor', 67000.0),
 ('Paige Miller', 65000.0),
 ('Quinn Wright', 62000.0),
 ('Ryan Clark', 106293.66000000002),
 ('Samantha Turner', 64000.0),
 ('Thomas Allen', 61000.0),
 ('Uma Patel', 62000.0),
 ('Victor Lewis', 63000.0),
 ('Wendy Harris', 64000.0),
 ('Yara White', 62000.0),
 ('Zachary Miller', 63000.0),
 ('Ariana Davis', 61000.0),
 ('Brandon Evans', 64000.0),
 ('Catherine Lopez', 109836.78200000004),
 ('Daniel Martin', 63000.0),
 ('Emily Harris', 61000.0),
 ('Felix Collins', 65000.0),
 ('Gina Wood', 62000.0),
 ('Ivy Wright', 62000.0),
 ('Jack Lee', 63000.0),
 ('Kelly Young', 108065.22100000002),
 ('Liam Clark', 62000.0),
 ('Megan Thompson', 61000.0),
 ('Nathan Evans', 62000.0),
 ('Patrick Brown', 62000.0),
 ('Quinn Cooper', 61000.0),
 ('Rachel Moore', 65000.0),
 ('Sam Rogers', 111608.34300000001),
 ('Ulysses Harris', 64000.0),
 ('Vera Johnson', 62000.0),
 ('Will Scott', 63000.0),
 ('Xena Garcia', 64000.0),
 ('Yvonne Rodriguez', 62000.0),
 ('Alyssa Wilson', 62000.0),
 ('Brandon Young', 63000.0),
 ('Cindy Brown', 61000.0),
 ('David Lee', 62000.0),
 ('Ella King', 113379.90400000002),
 ('Felix Martinez', 62000.0),
 ('Grace Turner', 61000.0),
 ('Henry Roberts', 67000.0),
 ('Ivy Lee', 63000.0),
 ('James Anderson', 62000.0),
 ('Katherine Thompson', 61000.0),
 ('Maya Brown', 62000.0),
 ('Noah Adams', 64000.0),
 ('Olivia Scott', 63000.0),
 ('Quinn Adams', 62000.0),
 ('Rachel Lewis', 63000.0),
 ('Sam Adams', 108065.22100000002),
 ('Tina Evans', 62000.0),
 ('Ulysses Scott', 63000.0),
 ('Vera Lee', 62000.0),
 ('Will Turner', 61000.0),
 ('Xena Adams', 64000.0),
 ('Yvonne Lee', 62000.0),
 ('Aiden Gray', 65000.0),
 ('Becca Davis', 106293.66000000002),
 ('Carlos Martinez', 62000.0),
 ('Diana Brown', 63000.0),
 ('Ethan Harris', 61000.0),
 ('Fiona Clark', 62000.0),
 ('George Wilson', 66000.0),
 ('Hannah Lewis', 62000.0),
 ('Ian Martinez', 64000.0),
 ('Jasmine Adams', 61000.0),
 ('Kevin White', 65000.0),
 ('Laura Green', 63000.0),
 ('Matthew Smith', 62000.0),
 ('Oscar Johnson', 109836.78200000004),
 ('Paige Green', 63000.0),
 ('Quincy Harris', 61000.0),
 ('Riley Carter', 62000.0),
 ('Thomas King', 64000.0),
 ('Uma Patel', 62000.0),
 ('Victor Brown', 111608.34300000001),
 ('Wendy Green', 62000.0),
 ('Xander Lee', 61000.0),
 ('Yara Adams', 62000.0),
 ('Amelia Scott', 63000.0),
 ('Bradley Moore', 62000.0),
 ('Catherine Carter', 61000.0),
 ('Derek Taylor', 62000.0),
 ('Emily Evans', 61000.0),
 ('Franklin White', 62000.0),
 ('Grace Adams', 63000.0),
 ('Harrison Davis', 62000.0),
 ('Ivy Robinson', 61000.0),
 ('Jack Lee', 64000.0),
 ('Kara Scott', 62000.0),
 ('Liam Williams', 63000.0),
 ('Mia Wright', 62000.0),
 ('Noah Smith', 61000.0),
 ('Paul Davis', 62000.0),
 ('Quinn Evans', 108065.22100000002),
 ('Rachel Scott', 64000.0),
 ('Sam Taylor', 62000.0),
 ('Tina White', 63000.0),
 ('Ulysses Brown', 62000.0),
 ('Vera White', 61000.0),
 ('Will Carter', 62000.0),
 ('Xena Wilson', 64000.0),
 ('Yvonne Scott', 62000.0),
 ('Zane Harris', 63000.0),
 ('Becca Wilson', 62000.0),
 ('Carlos Adams', 61000.0),
 ('Diana Robinson', 62000.0),
 ('Eric Wright', 63000.0),
 ('George Murphy', 62000.0),
 ('Hannah Carter', 62000.0),
 ('Ian Clark', 61000.0),
 ('Julia Davis', 64000.0),
 ('Aidan Brooks', 63000.0),
 ('Brianna Scott', 62000.0),
 ('Carl Turner', 64000.0),
 ('Diana Clark', 62000.0),
 ('Edward Hughes', 63000.0),
 ('Fiona Bell', 61000.0),
 ('George Allen', 62000.0),
 ('Hannah Collins', 63000.0),
 ('Ian Reed', 61000.0),
 ('Jasmine Young', 62000.0),
 ('Kyle Anderson', 64000.0),
 ('Laura Evans', 62000.0),
 ('Michael Green', 61000.0),
 ('Nora Phillips', 63000.0),
 ('Oliver Wright', 62000.0),
 ('Quincy Clark', 63000.0),
 ('Rachel King', 62000.0),
 ('Steve Martinez', 64000.0),
 ('Tiffany Adams', 62000.0),
 ('Ursula Green', 61000.0),
 ('Victor Lewis', 62000.0),
 ('Wendy Scott', 61000.0),
 ('Xander Roberts', 64000.0),
 ('Yara Turner', 63000.0),
 ('Zachary Wilson', 62000.0),
 ('Alice Hughes', 62000.0),
 ('Bradley Adams', 63000.0),
 ('Catherine Morgan', 113379.90400000002),
 ('Daniel Rodriguez', 62000.0),
 ('Emma Wilson', 61000.0),
 ('Franklin Adams', 63000.0),
 ('Gina Clark', 62000.0),
 ('Harry Johnson', 61000.0),
 ('Jacob White', 62000.0),
 ('Kylie Moore', 62000.0),
 ('Leo Martin', 61000.0),
 ('Noah Taylor', 62000.0),
 ('Olivia Miller', 63000.0),
 ('Patrick Martinez', 64000.0),
 ('Riley Adams', 62000.0),
 ('Sophia Lewis', 61000.0),
 ('Thomas Wilson', 63000.0),
 ('Uma Robinson', 62000.0),
 ('Vera King', 64000.0),
 ('William Scott', 63000.0),
 ('Xena Lewis', 62000.0),
 ('Yvette Turner', 61000.0),
 ('Zachary Taylor', 62000.0),
 ('Anna Miller', 64000.0),
 ('Brian Martin', 63000.0),
 ('Catherine Young', 62000.0),
 ('David Green', 61000.0),
 ('Eva White', 62000.0),
 ('Frank Moore', 63000.0),
 ('Grace Johnson', 62000.0),
 ('Henry Davis', 62000.0),
 ('Isabelle Smith', 63000.0),
 ('Jack Brown', 64000.0),
 ('Kimberly Lee', 64000.0),
 ('Laura Adams', 62000.0),
 ('Matthew Davis', 63000.0),
 ('Nina Clark', 62000.0),
 ('Oscar Wilson', 61000.0),
 ('Paula Davis', 64000.0),
 ('Quincy Adams', 62000.0),
 ('Rachel Smith', 62000.0),
 ('Samuel Johnson', 63000.0),
 ('Tina Green', 62000.0),
 ('Ulysses Wright', 62000.0),
 ('Vera Adams', 61000.0),
 ('William Lewis', 113379.90400000002),
 ('Xander Martin', 63000.0),
 ('Yvonne White', 62000.0),
 ('Zachary Lee', 63000.0),
 ('John David', 66000.0),
 ('Aiden Lee', 66000.0),
 ('Olivia Adams', 64900.00000000001),
 ('John Doe', 71500.0),
 ('Alice Johnson', 65000.0),
 ('Bob Brown', 80000.0),
 ('David Miller', 67100.0),
 ('Frank White', 79200.0),
 ('Henry Walker', 85800.0),
 ('Jack Martin', 69300.0),
 ('Karen Young', 85000.0),
 ('Mia Thompson', 68200.0),
 ('Noah Roberts', 64900.00000000001),
 ('Olivia Lewis', 70000.0),
 ('Quinn Scott', 76000.0),
 ('Samuel Wright', 63800.00000000001),
 ('Tina Hall', 64000.0),
 ('Uma Baker', 75000.0),
 ('Wendy Campbell', 65000.0),
 ('Xander James', 63000.0),
 ('Zachary Morris', 77000.0),
 ('Brian Nelson', 67100.0),
 ('Daniel Foster', 69300.0),
 ('Eleanor Reed', 78000.0),
 ('Harry Alexander', 62700.00000000001),
 ('Jackie Sanders', 65000.0),
 ('Keith Ross', 69300.0),
 ('Laura Jenkins', 74000.0),
 ('Nina Wallace', 70400.0),
 ('Oscar Daniels', 67100.0),
 ('Quentin Collins', 60500.00000000001),
 ('Ruth Bennett', 65000.0),
 ('Steven Hamilton', 69300.0),
 ('Tina Adams', 74000.0),
 ('Victor Mitchell', 64000.0),
 ('Wendy Edwards', 67100.0),
 ('Yara Adams', 65000.0),
 ('Zachary Foster', 69300.0),
 ('Bob Smith', 90200.00000000001),
 ('Carol Taylor', 63000.0),
 ('David Brown', 68000.0),
 ('Eva Wilson', 61000.0),
 ('Frank Garcia', 75000.0),
 ('Grace Martinez', 66000.0),
 ('Henry Robinson', 65000.0),
 ('Jack White', 69000.0),
 ('Karen Lewis', 74000.0),
 ('Mia Lee', 72600.0),
 ('Nathan King', 72000.0),
 ('Olivia Scott', 64000.0),
 ('Patrick Turner', 70000.0),
 ('Rachel Martinez', 63000.0),
 ('Sam Parker', 72600.0),
 ('Tina Clark', 67000.0),
 ('Walter Hernandez', 65000.0),
 ('Ximena Cooper', 64000.0),
 ('Yvonne Campbell', 62000.0),
 ('Zachary Long', 77000.0),
 ('Benjamin Brown', 68000.0),
 ('Charlotte Davis', 61000.0),
 ('Daniel Gonzalez', 72000.0),
 ('Emma Hall', 64000.0),
 ('Frankie Allen', 73700.0),
 ('Henry Roberts', 75900.0),
 ('Isabelle Turner', 62000.0),
 ('Jackie Clark', 72000.0),
 ('Kara Edwards', 63000.0),
 ('Liam Scott', 63800.00000000001),
 ('Molly Hughes', 65000.0),
 ('Nate Williams', 61000.0),
 ('Olivia Collins', 66000.0),
 ('Paul Foster', 71000.0),
 ('Quinn Howard', 63000.0),
 ('Steven Bailey', 67000.0),
 ('Tina Bell', 78100.0),
 ('Uma Murphy', 70400.0),
 ('Wendy Adams', 67000.0),
 ('Yasmin Lee', 62000.0),
 ('Zane Cooper', 70000.0),
 ('Aiden Green', 63800.00000000001),
 ('Bella Johnson', 62000.0),
 ('Caleb Scott', 67000.0),
 ('Ethan Lewis', 71000.0),
 ('Fiona Brown', 68000.0),
 ('George White', 66000.0),
 ('Hannah King', 62000.0),
 ('Ian Martinez', 70000.0),
 ('Julia Turner', 63000.0),
 ('Kyle Roberts', 64000.0),
 ('Mason Evans', 67000.0),
 ('Nora Gonzalez', 66000.0),
 ('Oscar Miller', 62000.0),
 ('Paige Adams', 65000.0),
 ('Quincy Hill', 68000.0),
 ('Riley Baker', 64900.00000000001),
 ('Sophia Evans', 62000.0),
 ('Tyler Martinez', 67000.0),
 ('Uma Robinson', 61000.0),
 ('William Taylor', 64000.0),
 ('Xander Wright', 63000.0),
 ('Zara Wright', 62000.0),
 ('Ariana Lopez', 64900.00000000001),
 ('Blake Adams', 63000.0),
 ('Chloe White', 62000.0),
 ('Daniel Clark', 66000.0),
 ('Ella Brown', 61000.0),
 ('Finn Garcia', 74800.0),
 ('Holly Martinez', 65000.0),
 ('Isaac Turner', 62000.0),
 ('Jasmine Wright', 64000.0),
 ('Liam Scott', 67000.0),
 ('Maya Thompson', 62000.0),
 ('Noah Allen', 63000.0),
 ('Olivia Campbell', 61000.0),
 ('Paul Collins', 68000.0),
 ('Quinn Diaz', 66000.0),
 ('Riley Hernandez', 63000.0),
 ('Tyler Lopez', 64000.0),
 ('Ursula Moore', 62000.0),
 ('Victor White', 64900.00000000001),
 ('Wendy Scott', 65000.0),
 ('Xander Cooper', 68000.0),
 ('Zachary King', 64000.0),
 ('Alyssa Reed', 63000.0),
 ('Bradley Evans', 62000.0),
 ('Charlotte Murphy', 65000.0),
 ('Derek Collins', 67000.0),
 ('Eva Sanchez', 61000.0),
 ('Frankie Scott', 62000.0),
 ('Hank Wright', 67000.0),
 ('Iris Lee', 62000.0),
 ('Jack Morris', 67000.0),
 ('Kelsey Davis', 63000.0),
 ('Leo Bennett', 65000.0),
 ('Mia Gray', 61000.0),
 ('Oscar Wright', 63000.0),
 ('Quinn Adams', 64000.0),
 ('Riley Evans', 68200.0),
 ('Sophia Knight', 63000.0),
 ('Tina Harris', 62000.0),
 ('Ulysses Clark', 65000.0),
 ('Xena Gray', 61000.0),
 ('Yara Miller', 64000.0),
 ('Zane Davis', 67000.0),
 ('Bella Martinez', 62000.0),
 ('Cameron Lee', 61000.0),
 ('Daisy Taylor', 64000.0),
 ('Ethan White', 69300.0),
 ('George Harris', 65000.0),
 ('Holly Adams', 62000.0),
 ('Ian Young', 68000.0),
 ('Jasmine Clark', 61000.0),
 ('Kevin Scott', 63000.0),
 ('Laura Nelson', 64000.0),
 ('Michael Lopez', 62000.0),
 ('Oliver Walker', 67100.0),
 ('Peyton Wright', 64000.0),
 ('Quincy Morgan', 63000.0),
 ('Rachel Morris', 62000.0),
 ('Taylor Hughes', 62000.0),
 ('Ursula Rivera', 61000.0),
 ('Victor Turner', 65000.0),
 ('Wendy Allen', 63000.0),
 ('Xander Brooks', 68200.0),
 ('Yvonne Carter', 61000.0),
 ('Alyssa Bailey', 62000.0),
 ('Brandon King', 64000.0),
 ('Clara Morgan', 66000.0),
 ('Derek Clark', 62000.0),
 ('Eva Lewis', 61000.0),
 ('Frank Turner', 65000.0),
 ('Grace Miller', 62000.0),
 ('Hannah Allen', 63000.0),
 ('Ian Thompson', 62000.0),
 ('Kevin Moore', 64000.0),
 ('Laura Robinson', 62000.0),
 ('Mark Davis', 64000.0),
 ('Nina Evans', 61000.0),
 ('Oscar Taylor', 67000.0),
 ('Paige Miller', 65000.0),
 ('Quinn Wright', 62000.0),
 ('Ryan Clark', 66000.0),
 ('Samantha Turner', 64000.0),
 ('Thomas Allen', 61000.0),
 ('Uma Patel', 62000.0),
 ('Victor Lewis', 63000.0),
 ('Wendy Harris', 64000.0),
 ('Yara White', 62000.0),
 ('Zachary Miller', 63000.0),
 ('Ariana Davis', 61000.0),
 ('Brandon Evans', 64000.0),
 ('Catherine Lopez', 68200.0),
 ('Daniel Martin', 63000.0),
 ('Emily Harris', 61000.0),
 ('Felix Collins', 65000.0),
 ('Gina Wood', 62000.0),
 ('Ivy Wright', 62000.0),
 ('Jack Lee', 63000.0),
 ('Kelly Young', 67100.0),
 ('Liam Clark', 62000.0),
 ('Megan Thompson', 61000.0),
 ('Nathan Evans', 62000.0),
 ('Patrick Brown', 62000.0),
 ('Quinn Cooper', 61000.0),
 ('Rachel Moore', 65000.0),
 ('Sam Rogers', 69300.0),
 ('Ulysses Harris', 64000.0),
 ('Vera Johnson', 62000.0),
 ('Will Scott', 63000.0),
 ('Xena Garcia', 64000.0),
 ('Yvonne Rodriguez', 62000.0),
 ('Alyssa Wilson', 62000.0),
 ('Brandon Young', 63000.0),
 ('Cindy Brown', 61000.0),
 ('David Lee', 62000.0),
 ('Ella King', 70400.0),
 ('Felix Martinez', 62000.0),
 ('Grace Turner', 61000.0),
 ('Henry Roberts', 67000.0),
 ('Ivy Lee', 63000.0),
 ('James Anderson', 62000.0),
 ('Katherine Thompson', 61000.0),
 ('Maya Brown', 62000.0),
 ('Noah Adams', 64000.0),
 ('Olivia Scott', 63000.0),
 ('Quinn Adams', 62000.0),
 ('Rachel Lewis', 63000.0),
 ('Sam Adams', 67100.0),
 ('Tina Evans', 62000.0),
 ('Ulysses Scott', 63000.0),
 ('Vera Lee', 62000.0),
 ('Will Turner', 61000.0),
 ('Xena Adams', 64000.0),
 ('Yvonne Lee', 62000.0),
 ('Laura Robinson', 62000.0),
 ('Mark Davis', 64000.0),
 ('Nina Evans', 61000.0),
 ('Oscar Taylor', 67000.0),
 ('Paige Miller', 65000.0),
 ('Quinn Wright', 62000.0),
 ('Ryan Clark', 66000.0),
 ('Samantha Turner', 64000.0),
 ('Thomas Allen', 61000.0),
 ('Uma Patel', 62000.0),
 ('Victor Lewis', 63000.0),
 ('Wendy Harris', 64000.0),
 ('Yara White', 62000.0),
 ('Zachary Miller', 63000.0),
 ('Ariana Davis', 61000.0),
 ('Brandon Evans', 64000.0),
 ('Catherine Lopez', 68200.0),
 ('Daniel Martin', 63000.0),
 ('Emily Harris', 61000.0),
 ('Felix Collins', 65000.0),
 ('Gina Wood', 62000.0),
 ('Ivy Wright', 62000.0),
 ('Jack Lee', 63000.0),
 ('Kelly Young', 67100.0),
 ('Liam Clark', 62000.0),
 ('Megan Thompson', 61000.0),
 ('Nathan Evans', 62000.0),
 ('Patrick Brown', 62000.0),
 ('Quinn Cooper', 61000.0),
 ('Rachel Moore', 65000.0),
 ('Sam Rogers', 69300.0),
 ('Ulysses Harris', 64000.0),
 ('Vera Johnson', 62000.0),
 ('Will Scott', 63000.0),
 ('Xena Garcia', 64000.0),
 ('Yvonne Rodriguez', 62000.0),
 ('Alyssa Wilson', 62000.0),
 ('Brandon Young', 63000.0),

Names of employees who are working in the 'IT' department.

In [11]:
%%sql
SELECT Name, Department FROM employee WHERE Department = 'IT';

 * sqlite:///NewDB.sqlite3
Done.

[('John Doe', 'IT'),
 ('David Miller', 'IT'),
 ('Frank White', 'IT'),
 ('Henry Walker', 'IT'),
 ('Jack Martin', 'IT'),
 ('Mia Thompson', 'IT'),
 ('Noah Roberts', 'IT'),
 ('Samuel Wright', 'IT'),
 ('Brian Nelson', 'IT'),
 ('Daniel Foster', 'IT'),
 ('Harry Alexander', 'IT'),
 ('Keith Ross', 'IT'),
 ('Nina Wallace', 'IT'),
 ('Oscar Daniels', 'IT'),
 ('Quentin Collins', 'IT'),
 ('Steven Hamilton', 'IT'),
 ('Wendy Edwards', 'IT'),
 ('Zachary Foster', 'IT'),
 ('Bob Smith', 'IT'),
 ('Mia Lee', 'IT'),
 ('Sam Parker', 'IT'),
 ('Zachary Long', 'IT'),
 ('Frankie Allen', 'IT'),
 ('Henry Roberts', 'IT'),
 ('Liam Scott', 'IT'),
 ('Tina Bell', 'IT'),
 ('Uma Murphy', 'IT'),
 ('Aiden Green', 'IT'),
 ('George White', 'IT'),
 ('Nora Gonzalez', 'IT'),
 ('Riley Baker', 'IT'),
 ('Ariana Lopez', 'IT'),
 ('Finn Garcia', 'IT'),
 ('Victor White', 'IT'),
 ('Riley Evans', 'IT'),
 ('Ethan White', 'IT'),
 ('Oliver Walker', 'IT'),
 ('Xander Brooks', 'IT'),
 ('Clara Morgan', 'IT'),
 ('Ryan Clark', 'IT'),
 ('Catherine Lopez', 'IT'),
 ('Kelly Young', 'IT'),
 ('Sam Rogers', 'IT'),
 ('Ella King', 'IT'),
 ('Sam Adams', 'IT'),
 ('Ryan Clark', 'IT'),
 ('Catherine Lopez', 'IT'),
 ('Kelly Young', 'IT'),
 ('Sam Rogers', 'IT'),
 ('Ella King', 'IT'),
 ('Sam Adams', 'IT'),
 ('Becca Davis', 'IT'),
 ('Oscar Johnson', 'IT'),
 ('Victor Brown', 'IT'),
 ('Quinn Evans', 'IT'),
 ('Catherine Morgan', 'IT'),
 ('William Lewis', 'IT'),
 ('John David', 'IT'),
 ('Aiden Lee', 'IT'),
 ('Olivia Adams', 'IT'),
 ('John Doe', 'IT'),
 ('David Miller', 'IT'),
 ('Frank White', 'IT'),
 ('Henry Walker', 'IT'),
 ('Jack Martin', 'IT'),
 ('Mia Thompson', 'IT'),
 ('Noah Roberts', 'IT'),
 ('Samuel Wright', 'IT'),
 ('Brian Nelson', 'IT'),
 ('Daniel Foster', 'IT'),
 ('Harry Alexander', 'IT'),
 ('Keith Ross', 'IT'),
 ('Nina Wallace', 'IT'),
 ('Oscar Daniels', 'IT'),
 ('Quentin Collins', 'IT'),
 ('Steven Hamilton', 'IT'),
 ('Wendy Edwards', 'IT'),
 ('Zachary Foster', 'IT'),
 ('Bob Smith', 'IT'),
 ('Mia Lee', 'IT'),
 ('Sam Parker', 'IT'),
 ('Zachary Long', 'IT'),
 ('Frankie Allen', 'IT'),
 ('Henry Roberts', 'IT'),
 ('Liam Scott', 'IT'),
 ('Tina Bell', 'IT'),
 ('Uma Murphy', 'IT'),
 ('Aiden Green', 'IT'),
 ('George White', 'IT'),
 ('Nora Gonzalez', 'IT'),
 ('Riley Baker', 'IT'),
 ('Ariana Lopez', 'IT'),
 ('Finn Garcia', 'IT'),
 ('Victor White', 'IT'),
 ('Riley Evans', 'IT'),
 ('Ethan White', 'IT'),
 ('Oliver Walker', 'IT'),
 ('Xander Brooks', 'IT'),
 ('Clara Morgan', 'IT'),
 ('Ryan Clark', 'IT'),
 ('Catherine Lopez', 'IT'),
 ('Kelly Young', 'IT'),
 ('Sam Rogers', 'IT'),
 ('Ella King', 'IT'),
 ('Sam Adams', 'IT'),
 ('Ryan Clark', 'IT'),
 ('Catherine Lopez', 'IT'),
 ('Kelly Young', 'IT'),
 ('Sam Rogers', 'IT'),
 ('Ella King', 'IT'),
 ('Sam Adams', 'IT'),
 ('Becca Davis', 'IT'),
 ('Oscar Johnson', 'IT'),
 ('Victor Brown', 'IT'),
 ('Quinn Evans', 'IT'),
 ('Catherine Morgan', 'IT'),
 ('William Lewis', 'IT'),
 ('John David', 'IT'),
 ('Aiden Lee', 'IT'),
 ('Olivia Adams', 'IT'),
 ('John Doe', 'IT'),
 ('Jane Smith', 'IT'),
 ('David Miller', 'IT'),
 ('Frank White', 'IT'),
 ('Henry Walker', 'IT'),
 ('Jack Martin', 'IT'),
 ('Mia Thompson', 'IT'),
 ('Noah Roberts', 'IT'),
 ('Samuel Wright', 'IT'),
 ('Brian Nelson', 'IT'),
 ('Daniel Foster', 'IT'),
 ('Harry Alexander', 'IT'),
 ('Keith Ross', 'IT'),
 ('Nina Wallace', 'IT'),
 ('Oscar Daniels', 'IT'),
 ('Quentin Collins', 'IT'),
 ('Steven Hamilton', 'IT'),
 ('Wendy Edwards', 'IT'),
 ('Zachary Foster', 'IT'),
 ('Bob Smith', 'IT'),
 ('Mia Lee', 'IT'),
 ('Sam Parker', 'IT'),
 ('Zachary Long', 'IT'),
 ('Frankie Allen', 'IT'),
 ('Henry Roberts', 'IT'),
 ('Liam Scott', 'IT'),
 ('Tina Bell', 'IT'),
 ('Uma Murphy', 'IT'),
 ('Aiden Green', 'IT'),
 ('George White', 'IT'),
 ('Nora Gonzalez', 'IT'),
 ('Riley Baker', 'IT'),
 ('Ariana Lopez', 'IT'),
 ('Finn Garcia', 'IT'),
 ('Victor White', 'IT'),
 ('Riley Evans', 'IT'),
 ('Ethan White', 'IT'),
 ('Oliver Walker', 'IT'),
 ('Xander Brooks', 'IT'),
 ('Clara Morgan', 'IT'),
 ('Ryan Clark', 'IT'),
 ('Catherine Lopez', 'IT'),
 ('Kelly Young', 'IT'),
 ('Sam Rogers', 'IT'),
 ('Ella King', 'IT'),
 ('Sam Adams', 'IT'),
 ('Ryan Clark', 'IT'),
 ('Catherine Lopez', 'IT'),
 ('Kelly Young', 'IT'),
 ('Sam Rogers', 'IT'),
 ('Ella King', 'IT'),
 ('Sam Adams', 'IT'),
 ('Becca Davis', 'IT'),
 ('Oscar Johnson', 'IT'),
 ('Victor Brown', 'IT'),
 ('Quinn Evans', 'IT'),
 ('Catherine Morgan', 'IT'),
 ('William Lewis', 'IT')]

In [12]:
# Count the number of employees in the 'Marketing' department.

%%sql
SELECT COUNT(*) FROM employee WHERE Department = 'Marketing';

 * sqlite:///NewDB.sqlite3
Done.

[(204,)]

In [13]:
# Retrieve the average salary of employees.

%%sql
SELECT AVG(Salary) FROM employee;

 * sqlite:///NewDB.sqlite3
Done.

[(64861.169216924114,)]

In [14]:
#highest salary from the employee table.

%%sql
SELECT MAX(Salary) FROM employee;

 * sqlite:///NewDB.sqlite3
Done.

[(145268.0020000001,)]

In [15]:
#highest salary from the employee table.

%%sql
SELECT Name, Position,  MAX(Salary) FROM employee;

 * sqlite:///NewDB.sqlite3
Done.

[('Bob Smith', 'IT Manager', 145268.0020000001)]

In [16]:
# Names of employees who are working in the 'IT' department and Salary greater than 70000

%%sql
SELECT Name, Department, Salary FROM employee WHERE Department = 'IT' AND Salary > 70000;

 * sqlite:///NewDB.sqlite3
Done.

[('John Doe', 'IT', 71500.0),
 ('David Miller', 'IT', 108065.22100000002),
 ('Frank White', 'IT', 127552.39200000007),
 ('Henry Walker', 'IT', 138181.75800000006),
 ('Jack Martin', 'IT', 111608.34300000001),
 ('Mia Thompson', 'IT', 109836.78200000004),
 ('Noah Roberts', 'IT', 104522.09900000007),
 ('Samuel Wright', 'IT', 102750.53800000006),
 ('Brian Nelson', 'IT', 108065.22100000002),
 ('Daniel Foster', 'IT', 111608.34300000001),
 ('Harry Alexander', 'IT', 100978.97700000006),
 ('Keith Ross', 'IT', 111608.34300000001),
 ('Nina Wallace', 'IT', 113379.90400000002),
 ('Oscar Daniels', 'IT', 108065.22100000002),
 ('Quentin Collins', 'IT', 97435.85500000007),
 ('Steven Hamilton', 'IT', 111608.34300000001),
 ('Wendy Edwards', 'IT', 108065.22100000002),
 ('Zachary Foster', 'IT', 111608.34300000001),
 ('Bob Smith', 'IT', 145268.0020000001),
 ('Mia Lee', 'IT', 116923.02600000003),
 ('Sam Parker', 'IT', 116923.02600000003),
 ('Zachary Long', 'IT', 124009.27000000005),
 ('Frankie Allen', 'IT', 118694.58700000004),
 ('Henry Roberts', 'IT', 122237.70900000005),
 ('Liam Scott', 'IT', 102750.53800000006),
 ('Tina Bell', 'IT', 125780.83100000005),
 ('Uma Murphy', 'IT', 113379.90400000002),
 ('Aiden Green', 'IT', 102750.53800000006),
 ('George White', 'IT', 106293.66000000002),
 ('Nora Gonzalez', 'IT', 106293.66000000002),
 ('Riley Baker', 'IT', 104522.09900000007),
 ('Ariana Lopez', 'IT', 104522.09900000007),
 ('Finn Garcia', 'IT', 120466.14800000003),
 ('Victor White', 'IT', 104522.09900000007),
 ('Riley Evans', 'IT', 109836.78200000004),
 ('Ethan White', 'IT', 111608.34300000001),
 ('Oliver Walker', 'IT', 108065.22100000002),
 ('Xander Brooks', 'IT', 109836.78200000004),
 ('Clara Morgan', 'IT', 106293.66000000002),
 ('Ryan Clark', 'IT', 106293.66000000002),
 ('Catherine Lopez', 'IT', 109836.78200000004),
 ('Kelly Young', 'IT', 108065.22100000002),
 ('Sam Rogers', 'IT', 111608.34300000001),
 ('Ella King', 'IT', 113379.90400000002),
 ('Sam Adams', 'IT', 108065.22100000002),
 ('Ryan Clark', 'IT', 106293.66000000002),
 ('Catherine Lopez', 'IT', 109836.78200000004),
 ('Kelly Young', 'IT', 108065.22100000002),
 ('Sam Rogers', 'IT', 111608.34300000001),
 ('Ella King', 'IT', 113379.90400000002),
 ('Sam Adams', 'IT', 108065.22100000002),
 ('Becca Davis', 'IT', 106293.66000000002),
 ('Oscar Johnson', 'IT', 109836.78200000004),
 ('Victor Brown', 'IT', 111608.34300000001),
 ('Quinn Evans', 'IT', 108065.22100000002),
 ('Catherine Morgan', 'IT', 113379.90400000002),
 ('William Lewis', 'IT', 113379.90400000002),
 ('John Doe', 'IT', 71500.0),
 ('Frank White', 'IT', 79200.0),
 ('Henry Walker', 'IT', 85800.0),
 ('Nina Wallace', 'IT', 70400.0),
 ('Bob Smith', 'IT', 90200.00000000001),
 ('Mia Lee', 'IT', 72600.0),
 ('Sam Parker', 'IT', 72600.0),
 ('Zachary Long', 'IT', 77000.0),
 ('Frankie Allen', 'IT', 73700.0),
 ('Henry Roberts', 'IT', 75900.0),
 ('Tina Bell', 'IT', 78100.0),
 ('Uma Murphy', 'IT', 70400.0),
 ('Finn Garcia', 'IT', 74800.0),
 ('Ella King', 'IT', 70400.0),
 ('Ella King', 'IT', 70400.0),
 ('Catherine Morgan', 'IT', 70400.0),
 ('William Lewis', 'IT', 70400.0),
 ('Jane Smith', 'IT', 75000.0),
 ('Frank White', 'IT', 72000.0),
 ('Henry Walker', 'IT', 78000.0),
 ('Bob Smith', 'IT', 82000.0),
 ('Tina Bell', 'IT', 71000.0)]

In [17]:
# Update the salary of 'John Doe' to 65000.

%%sql
UPDATE employee SET Salary = 65000 WHERE Name = 'John Doe';

 * sqlite:///NewDB.sqlite3
3 rows affected.

[]

In [18]:
# Salary of John Doe

%%sql
SELECT Salary FROM employee WHERE Name = 'John Doe';

 * sqlite:///NewDB.sqlite3
Done.

[(65000.0,), (65000.0,), (65000.0,)]

In [19]:
# Display the employee record with the name 'Jane Smith'.

%%sql
SELECT * FROM employee WHERE Name = 'Jane Smith';

 * sqlite:///NewDB.sqlite3
Done.

[(998, 'Jane Smith', 40, '456 Oak St', 75000.0, 'Project Manager', 'IT', '2010-08-15', 10, 8, 4.8, 4.9, 2, 5)]

In [20]:
# Delete the employee record with the name 'Jane Smith'.

%%sql
DELETE FROM employee WHERE Name = 'Jane Smith';

 * sqlite:///NewDB.sqlite3
1 rows affected.

[]

In [21]:
# Display the employee record with the name 'Jane Smith'.

%%sql
SELECT * FROM employee WHERE Name = 'Jane Smith';

 * sqlite:///NewDB.sqlite3
Done.

[]

In [22]:
# Retrieve the names and positions of employees who joined after '2016-01-01' and Salary > 62000.

%%sql
SELECT Name, Date_of_Joining,Position, Salary FROM employee WHERE Date_of_Joining > '2016-01-01' and Salary > 62000;

 * sqlite:///NewDB.sqlite3
Done.

[('David Miller', '2016-05-15', 'Data Analyst', 108065.22100000002),
 ('Noah Roberts', '2016-08-20', 'Technical Writer', 104522.09900000007),
 ('Samuel Wright', '2017-11-05', 'Software Developer', 102750.53800000006),
 ('Brian Nelson', '2016-11-25', 'DevOps Engineer', 108065.22100000002),
 ('Harry Alexander', '2018-03-15', 'IT Support', 100978.97700000006),
 ('Quentin Collins', '2017-11-10', 'Front-end Developer', 97435.85500000007),
 ('Liam Scott', '2016-03-25', 'Support Engineer', 102750.53800000006),
 ('Aiden Green', '2017-09-15', 'Junior Developer', 102750.53800000006),
 ('George White', '2016-04-20', 'Data Analyst', 106293.66000000002),
 ('Riley Baker', '2017-07-15', 'Data Scientist', 104522.09900000007),
 ('Ariana Lopez', '2017-06-15', 'IT Project Manager', 104522.09900000007),
 ('Victor White', '2016-04-20', 'IT Coordinator', 104522.09900000007),
 ('Sophia Knight', '2016-02-15', 'Sales Manager', 63000.0),
 ('Ethan White', '2016-02-10', 'IT Specialist', 111608.34300000001),
 ('Oliver Walker', '2017-04-20', 'IT Coordinator', 108065.22100000002),
 ('Wendy Allen', '2016-03-15', 'Product Manager', 63000.0),
 ('Clara Morgan', '2018-05-10', 'IT Coordinator', 106293.66000000002),
 ('Ryan Clark', '2017-04-20', 'IT Specialist', 106293.66000000002),
 ('Zachary Miller', '2016-06-10', 'Sales Coordinator', 63000.0),
 ('Jack Lee', '2016-09-10', 'Customer Service Manager', 63000.0),
 ('Kelly Young', '2017-06-20', 'IT Coordinator', 108065.22100000002),
 ('Sam Rogers', '2016-03-15', 'IT Specialist', 111608.34300000001),
 ('Will Scott', '2017-01-20', 'Design Manager', 63000.0),
 ('Sam Adams', '2016-07-20', 'IT Coordinator', 108065.22100000002),
 ('Ryan Clark', '2017-04-20', 'IT Specialist', 106293.66000000002),
 ('Zachary Miller', '2016-06-10', 'Sales Coordinator', 63000.0),
 ('Jack Lee', '2016-09-10', 'Customer Service Manager', 63000.0),
 ('Kelly Young', '2017-06-20', 'IT Coordinator', 108065.22100000002),
 ('Sam Rogers', '2016-03-15', 'IT Specialist', 111608.34300000001),
 ('Will Scott', '2017-01-20', 'Design Manager', 63000.0),
 ('Sam Adams', '2016-07-20', 'IT Coordinator', 108065.22100000002),
 ('Becca Davis', '2018-09-10', 'IT Specialist', 106293.66000000002),
 ('Oscar Johnson', '2016-09-10', 'IT Coordinator', 109836.78200000004),
 ('Quinn Evans', '2019-01-15', 'IT Specialist', 108065.22100000002),
 ('Hannah Collins', '2016-03-15', 'Customer Service Specialist', 63000.0),
 ('Olivia Miller', '2016-08-15', 'Finance Manager', 63000.0),
 ('Frank Moore', '2016-08-10', 'Operations Manager', 63000.0),
 ('Isabelle Smith', '2016-05-10', 'HR Specialist', 63000.0),
 ('Matthew Davis', '2016-04-15', 'Product Coordinator', 63000.0),
 ('Zachary Lee', '2016-03-20', 'Design Manager', 63000.0),
 ('John David', '2023-05-08', 'Software Engineer', 66000.0),
 ('Aiden Lee', '2019-08-20', 'Software Engineer', 66000.0),
 ('Olivia Adams', '2020-02-15', 'Data Analyst', 64900.00000000001),
 ('David Miller', '2016-05-15', 'Data Analyst', 67100.0),
 ('Noah Roberts', '2016-08-20', 'Technical Writer', 64900.00000000001),
 ('Samuel Wright', '2017-11-05', 'Software Developer', 63800.00000000001),
 ('Brian Nelson', '2016-11-25', 'DevOps Engineer', 67100.0),
 ('Harry Alexander', '2018-03-15', 'IT Support', 62700.00000000001),
 ('Liam Scott', '2016-03-25', 'Support Engineer', 63800.00000000001),
 ('Aiden Green', '2017-09-15', 'Junior Developer', 63800.00000000001),
 ('George White', '2016-04-20', 'Data Analyst', 66000.0),
 ('Riley Baker', '2017-07-15', 'Data Scientist', 64900.00000000001),
 ('Ariana Lopez', '2017-06-15', 'IT Project Manager', 64900.00000000001),
 ('Victor White', '2016-04-20', 'IT Coordinator', 64900.00000000001),
 ('Sophia Knight', '2016-02-15', 'Sales Manager', 63000.0),
 ('Ethan White', '2016-02-10', 'IT Specialist', 69300.0),
 ('Oliver Walker', '2017-04-20', 'IT Coordinator', 67100.0),
 ('Wendy Allen', '2016-03-15', 'Product Manager', 63000.0),
 ('Clara Morgan', '2018-05-10', 'IT Coordinator', 66000.0),
 ('Ryan Clark', '2017-04-20', 'IT Specialist', 66000.0),
 ('Zachary Miller', '2016-06-10', 'Sales Coordinator', 63000.0),
 ('Jack Lee', '2016-09-10', 'Customer Service Manager', 63000.0),
 ('Kelly Young', '2017-06-20', 'IT Coordinator', 67100.0),
 ('Sam Rogers', '2016-03-15', 'IT Specialist', 69300.0),
 ('Will Scott', '2017-01-20', 'Design Manager', 63000.0),
 ('Sam Adams', '2016-07-20', 'IT Coordinator', 67100.0),
 ('Ryan Clark', '2017-04-20', 'IT Specialist', 66000.0),
 ('Zachary Miller', '2016-06-10', 'Sales Coordinator', 63000.0),
 ('Jack Lee', '2016-09-10', 'Customer Service Manager', 63000.0),
 ('Kelly Young', '2017-06-20', 'IT Coordinator', 67100.0),
 ('Sam Rogers', '2016-03-15', 'IT Specialist', 69300.0),
 ('Will Scott', '2017-01-20', 'Design Manager', 63000.0),
 ('Sam Adams', '2016-07-20', 'IT Coordinator', 67100.0),
 ('Becca Davis', '2018-09-10', 'IT Specialist', 66000.0),
 ('Oscar Johnson', '2016-09-10', 'IT Coordinator', 68200.0),
 ('Quinn Evans', '2019-01-15', 'IT Specialist', 67100.0),
 ('Hannah Collins', '2016-03-15', 'Customer Service Specialist', 63000.0),
 ('Olivia Miller', '2016-08-15', 'Finance Manager', 63000.0),
 ('Frank Moore', '2016-08-10', 'Operations Manager', 63000.0),
 ('Isabelle Smith', '2016-05-10', 'HR Specialist', 63000.0),
 ('Matthew Davis', '2016-04-15', 'Product Coordinator', 63000.0),
 ('Zachary Lee', '2016-03-20', 'Design Manager', 63000.0),
 ('Sophia Knight', '2016-02-15', 'Sales Manager', 63000.0),
 ('Ethan White', '2016-02-10', 'IT Specialist', 63000.0),
 ('Wendy Allen', '2016-03-15', 'Product Manager', 63000.0),
 ('Zachary Miller', '2016-06-10', 'Sales Coordinator', 63000.0),
 ('Jack Lee', '2016-09-10', 'Customer Service Manager', 63000.0),
 ('Sam Rogers', '2016-03-15', 'IT Specialist', 63000.0),
 ('Will Scott', '2017-01-20', 'Design Manager', 63000.0),
 ('Zachary Miller', '2016-06-10', 'Sales Coordinator', 63000.0),
 ('Jack Lee', '2016-09-10', 'Customer Service Manager', 63000.0),
 ('Sam Rogers', '2016-03-15', 'IT Specialist', 63000.0),
 ('Will Scott', '2017-01-20', 'Design Manager', 63000.0),
 ('Hannah Collins', '2016-03-15', 'Customer Service Specialist', 63000.0),
 ('Olivia Miller', '2016-08-15', 'Finance Manager', 63000.0),
 ('Frank Moore', '2016-08-10', 'Operations Manager', 63000.0),
 ('Isabelle Smith', '2016-05-10', 'HR Specialist', 63000.0),
 ('Matthew Davis', '2016-04-15', 'Product Coordinator', 63000.0),
 ('Zachary Lee', '2016-03-20', 'Design Manager', 63000.0)]

In [23]:
# Names of employees with more than 5 years of experience and in IT dept and Age greater than 40

%%sql
SELECT Name, Age, Department
FROM employee
WHERE Department = 'IT' AND Date('now') - Date(Date_of_Joining) > 5 AND Age > 40;

 * sqlite:///NewDB.sqlite3
Done.

[('Henry Walker', 41, 'IT'),
 ('Bob Smith', 42, 'IT'),
 ('Henry Walker', 41, 'IT'),
 ('Bob Smith', 42, 'IT'),
 ('Henry Walker', 41, 'IT'),
 ('Bob Smith', 42, 'IT')]

In [24]:
# Sort employees by name and Display name and Dept

%%sql
SELECT Name, Department
FROM employee
ORDER BY Name;

 * sqlite:///NewDB.sqlite3
Done.

[('Aidan Brooks', 'Support'),
 ('Aidan Brooks', 'Support'),
 ('Aidan Brooks', 'Support'),
 ('Aidan Carter', 'Business'),
 ('Aidan Carter', 'Business'),
 ('Aidan Carter', 'Business'),
 ('Aiden Gray', 'Project'),
 ('Aiden Gray', 'Project'),
 ('Aiden Gray', 'Project'),
 ('Aiden Green', 'IT'),
 ('Aiden Green', 'IT'),
 ('Aiden Green', 'IT'),
 ('Aiden Lee', 'IT'),
 ('Aiden Lee', 'IT'),
 ('Aiden Martinez', 'Sales'),
 ('Aiden Martinez', 'Sales'),
 ('Aiden Martinez', 'Sales'),
 ('Alice Hughes', 'Product'),
 ('Alice Hughes', 'Product'),
 ('Alice Hughes', 'Product'),
 ('Alice Johnson', 'Business'),
 ('Alice Johnson', 'Business'),
 ('Alice Johnson', 'Business'),
 ('Alice Johnson', 'Business'),
 ('Alice Johnson', 'Business'),
 ('Alice Johnson', 'Business'),
 ('Alyssa Bailey', 'Support'),
 ('Alyssa Bailey', 'Support'),
 ('Alyssa Bailey', 'Support'),
 ('Alyssa Reed', 'Business'),
 ('Alyssa Reed', 'Business'),
 ('Alyssa Reed', 'Business'),
 ('Alyssa Wilson', 'Finance'),
 ('Alyssa Wilson', 'Finance'),
 ('Alyssa Wilson', 'Finance'),
 ('Alyssa Wilson', 'Finance'),
 ('Alyssa Wilson', 'Finance'),
 ('Alyssa Wilson', 'Finance'),
 ('Amelia Moore', 'Content'),
 ('Amelia Moore', 'Content'),
 ('Amelia Moore', 'Content'),
 ('Amelia Scott', 'Marketing'),
 ('Amelia Scott', 'Marketing'),
 ('Amelia Scott', 'Marketing'),
 ('Anna Miller', 'Design'),
 ('Anna Miller', 'Design'),
 ('Anna Miller', 'Design'),
 ('Anna Rogers', 'Marketing'),
 ('Anna Rogers', 'Marketing'),
 ('Anna Rogers', 'Marketing'),
 ('Ariana Davis', 'Support'),
 ('Ariana Davis', 'Support'),
 ('Ariana Davis', 'Support'),
 ('Ariana Davis', 'Support'),
 ('Ariana Davis', 'Support'),
 ('Ariana Davis', 'Support'),
 ('Ariana Lopez', 'IT'),
 ('Ariana Lopez', 'IT'),
 ('Ariana Lopez', 'IT'),
 ('Becca Davis', 'IT'),
 ('Becca Davis', 'IT'),
 ('Becca Davis', 'IT'),
 ('Becca Wilson', 'Product'),
 ('Becca Wilson', 'Product'),
 ('Becca Wilson', 'Product'),
 ('Bella Johnson', 'Marketing'),
 ('Bella Johnson', 'Marketing'),
 ('Bella Johnson', 'Marketing'),
 ('Bella Martinez', 'Sales'),
 ('Bella Martinez', 'Sales'),
 ('Bella Martinez', 'Sales'),
 ('Benjamin Brown', 'HR'),
 ('Benjamin Brown', 'HR'),
 ('Benjamin Brown', 'HR'),
 ('Blake Adams', 'Marketing'),
 ('Blake Adams', 'Marketing'),
 ('Blake Adams', 'Marketing'),
 ('Bob Brown', 'HR'),
 ('Bob Brown', 'HR'),
 ('Bob Brown', 'HR'),
 ('Bob Smith', 'IT'),
 ('Bob Smith', 'IT'),
 ('Bob Smith', 'IT'),
 ('Bradley Adams', 'Operations'),
 ('Bradley Adams', 'Operations'),
 ('Bradley Adams', 'Operations'),
 ('Bradley Evans', 'Design'),
 ('Bradley Evans', 'Design'),
 ('Bradley Evans', 'Design'),
 ('Bradley Moore', 'Operations'),
 ('Bradley Moore', 'Operations'),
 ('Bradley Moore', 'Operations'),
 ('Brandon Evans', 'Product'),
 ('Brandon Evans', 'Product'),
 ('Brandon Evans', 'Product'),
 ('Brandon Evans', 'Product'),
 ('Brandon Evans', 'Product'),
 ('Brandon Evans', 'Product'),
 ('Brandon King', 'Design'),
 ('Brandon King', 'Design'),
 ('Brandon King', 'Design'),
 ('Brandon Young', 'Marketing'),
 ('Brandon Young', 'Marketing'),
 ('Brandon Young', 'Marketing'),
 ('Brandon Young', 'Marketing'),
 ('Brandon Young', 'Marketing'),
 ('Brandon Young', 'Marketing'),
 ('Brian Martin', 'Finance'),
 ('Brian Martin', 'Finance'),
 ('Brian Martin', 'Finance'),
 ('Brian Nelson', 'IT'),
 ('Brian Nelson', 'IT'),
 ('Brian Nelson', 'IT'),
 ('Brianna Scott', 'Sales'),
 ('Brianna Scott', 'Sales'),
 ('Brianna Scott', 'Sales'),
 ('Caleb Scott', 'Business'),
 ('Caleb Scott', 'Business'),
 ('Caleb Scott', 'Business'),
 ('Cameron Lee', 'Product'),
 ('Cameron Lee', 'Product'),
 ('Cameron Lee', 'Product'),
 ('Carl Turner', 'Finance'),
 ('Carl Turner', 'Finance'),
 ('Carl Turner', 'Finance'),
 ('Carlos Adams', 'Finance'),
 ('Carlos Adams', 'Finance'),
 ('Carlos Adams', 'Finance'),
 ('Carlos Martinez', 'HR'),
 ('Carlos Martinez', 'HR'),
 ('Carlos Martinez', 'HR'),
 ('Carol Taylor', 'HR'),
 ('Carol Taylor', 'HR'),
 ('Carol Taylor', 'HR'),
 ('Catherine Bryant', 'Business'),
 ('Catherine Bryant', 'Business'),
 ('Catherine Bryant', 'Business'),
 ('Catherine Carter', 'Product'),
 ('Catherine Carter', 'Product'),
 ('Catherine Carter', 'Product'),
 ('Catherine Lopez', 'IT'),
 ('Catherine Lopez', 'IT'),
 ('Catherine Lopez', 'IT'),
 ('Catherine Lopez', 'IT'),
 ('Catherine Lopez', 'IT'),
 ('Catherine Lopez', 'IT'),
 ('Catherine Morgan', 'IT'),
 ('Catherine Morgan', 'IT'),
 ('Catherine Morgan', 'IT'),
 ('Catherine Young', 'Marketing'),
 ('Catherine Young', 'Marketing'),
 ('Catherine Young', 'Marketing'),
 ('Charlie Davis', 'Marketing'),
 ('Charlie Davis', 'Marketing'),
 ('Charlie Davis', 'Marketing'),
 ('Charlotte Davis', 'Marketing'),
 ('Charlotte Davis', 'Marketing'),
 ('Charlotte Davis', 'Marketing'),
 ('Charlotte Murphy', 'Sales'),
 ('Charlotte Murphy', 'Sales'),
 ('Charlotte Murphy', 'Sales'),
 ('Chloe White', 'Content'),
 ('Chloe White', 'Content'),
 ('Chloe White', 'Content'),
 ('Cindy Brown', 'Design'),
 ('Cindy Brown', 'Design'),
 ('Cindy Brown', 'Design'),
 ('Cindy Brown', 'Design'),
 ('Cindy Brown', 'Design'),
 ('Cindy Brown', 'Design'),
 ('Clara Morgan', 'IT'),
 ('Clara Morgan', 'IT'),
 ('Clara Morgan', 'IT'),
 ('Daisy Harris', 'Design'),
 ('Daisy Harris', 'Design'),
 ('Daisy Harris', 'Design'),
 ('Daisy Taylor', 'Marketing'),
 ('Daisy Taylor', 'Marketing'),
 ('Daisy Taylor', 'Marketing'),
 ('Daniel Clark', 'Research'),
 ('Daniel Clark', 'Research'),
 ('Daniel Clark', 'Research'),
 ('Daniel Foster', 'IT'),
 ('Daniel Foster', 'IT'),
 ('Daniel Foster', 'IT'),
 ('Daniel Gonzalez', 'Operations'),
 ('Daniel Gonzalez', 'Operations'),
 ('Daniel Gonzalez', 'Operations'),
 ('Daniel Martin', 'Design'),
 ('Daniel Martin', 'Design'),
 ('Daniel Martin', 'Design'),
 ('Daniel Martin', 'Design'),
 ('Daniel Martin', 'Design'),
 ('Daniel Martin', 'Design'),
 ('Daniel Rodriguez', 'HR'),
 ('Daniel Rodriguez', 'HR'),
 ('Daniel Rodriguez', 'HR'),
 ('David Brown', 'Sales'),
 ('David Brown', 'Sales'),
 ('David Brown', 'Sales'),
 ('David Green', 'Product'),
 ('David Green', 'Product'),
 ('David Green', 'Product'),
 ('David Lee', 'Sales'),
 ('David Lee', 'Sales'),
 ('David Lee', 'Sales'),
 ('David Lee', 'Sales'),
 ('David Lee', 'Sales'),
 ('David Lee', 'Sales'),
 ('David Miller', 'IT'),
 ('David Miller', 'IT'),
 ('David Miller', 'IT'),
 ('Derek Clark', 'HR'),
 ('Derek Clark', 'HR'),
 ('Derek Clark', 'HR'),
 ('Derek Collins', 'Support'),
 ('Derek Collins', 'Support'),
 ('Derek Collins', 'Support'),
 ('Derek Taylor', 'Design'),
 ('Derek Taylor', 'Design'),
 ('Derek Taylor', 'Design'),
 ('Diana Brown', 'Finance'),
 ('Diana Brown', 'Finance'),
 ('Diana Brown', 'Finance'),
 ('Diana Clark', 'Marketing'),
 ('Diana Clark', 'Marketing'),
 ('Diana Clark', 'Marketing'),
 ('Diana Robinson', 'HR'),
 ('Diana Robinson', 'HR'),
 ('Diana Robinson', 'HR'),
 ('Edward Hughes', 'HR'),
 ('Edward Hughes', 'HR'),
 ('Edward Hughes', 'HR'),
 ('Eleanor Reed', 'HR'),
 ('Eleanor Reed', 'HR'),
 ('Eleanor Reed', 'HR'),
 ('Ella Brown', 'Operations'),
 ('Ella Brown', 'Operations'),
 ('Ella Brown', 'Operations'),
 ('Ella King', 'IT'),
 ('Ella King', 'IT'),
 ('Ella King', 'IT'),
 ('Ella King', 'IT'),
 ('Ella King', 'IT'),
 ('Ella King', 'IT'),
 ('Emily Evans', 'Support'),
 ('Emily Evans', 'Support'),
 ('Emily Evans', 'Support'),
 ('Emily Harris', 'HR'),
 ('Emily Harris', 'HR'),
 ('Emily Harris', 'HR'),
 ('Emily Harris', 'HR'),
 ('Emily Harris', 'HR'),
 ('Emily Harris', 'HR'),
 ('Emma Hall', 'Finance'),
 ('Emma Hall', 'Finance'),
 ('Emma Hall', 'Finance'),
 ('Emma Wilson', 'Marketing'),
 ('Emma Wilson', 'Marketing'),
 ('Emma Wilson', 'Marketing'),
 ('Eric Wright', 'Marketing'),
 ('Eric Wright', 'Marketing'),
 ('Eric Wright', 'Marketing'),
 ('Ethan Harris', 'Operations'),
 ('Ethan Harris', 'Operations'),
 ('Ethan Harris', 'Operations'),
 ('Ethan Lewis', 'Operations'),
 ('Ethan Lewis', 'Operations'),
 ('Ethan Lewis', 'Operations'),
 ('Ethan White', 'IT'),
 ('Ethan White', 'IT'),
 ('Ethan White', 'IT'),
 ('Eva Lewis', 'Marketing'),
 ('Eva Lewis', 'Marketing'),
 ('Eva Lewis', 'Marketing'),
 ('Eva Sanchez', 'Product'),
 ('Eva Sanchez', 'Product'),
 ('Eva Sanchez', 'Product'),
 ('Eva Taylor', 'Design'),
 ('Eva Taylor', 'Design'),
 ('Eva Taylor', 'Design'),
 ('Eva White', 'Sales'),
 ('Eva White', 'Sales'),
 ('Eva White', 'Sales'),
 ('Eva Wilson', 'Marketing'),
 ('Eva Wilson', 'Marketing'),
 ('Eva Wilson', 'Marketing'),
 ('Felix Collins', 'Operations'),
 ('Felix Collins', 'Operations'),
 ('Felix Collins', 'Operations'),
 ('Felix Collins', 'Operations'),
 ('Felix Collins', 'Operations'),
 ('Felix Collins', 'Operations'),
 ('Felix Martinez', 'Business'),
 ('Felix Martinez', 'Business'),
 ('Felix Martinez', 'Business'),
 ('Felix Martinez', 'Business'),
 ('Felix Martinez', 'Business'),
 ('Felix Martinez', 'Business'),
 ('Finn Garcia', 'IT'),
 ('Finn Garcia', 'IT'),
 ('Finn Garcia', 'IT'),
 ('Fiona Bell', 'Design'),
 ('Fiona Bell', 'Design'),
 ('Fiona Bell', 'Design'),
 ('Fiona Brown', 'HR'),
 ('Fiona Brown', 'HR'),
 ('Fiona Brown', 'HR'),
 ('Fiona Clark', 'Sales'),
 ('Fiona Clark', 'Sales'),
 ('Fiona Clark', 'Sales'),
 ('Fiona Green', 'Support'),
 ('Fiona Green', 'Support'),
 ('Fiona Green', 'Support'),
 ('Fiona Turner', 'Sales'),
 ('Fiona Turner', 'Sales'),
 ('Fiona Turner', 'Sales'),
 ('Francis Diaz', 'Support'),
 ('Francis Diaz', 'Support'),
 ('Francis Diaz', 'Support'),
 ('Frank Garcia', 'Finance'),
 ('Frank Garcia', 'Finance'),
 ('Frank Garcia', 'Finance'),
 ('Frank Moore', 'Operations'),
 ('Frank Moore', 'Operations'),
 ('Frank Moore', 'Operations'),
 ('Frank Turner', 'Operations'),
 ('Frank Turner', 'Operations'),
 ('Frank Turner', 'Operations'),
 ('Frank White', 'IT'),
 ('Frank White', 'IT'),
 ('Frank White', 'IT'),
 ('Frankie Allen', 'IT'),
 ('Frankie Allen', 'IT'),
 ('Frankie Allen', 'IT'),
 ('Frankie Scott', 'Operations'),
 ('Frankie Scott', 'Operations'),
 ('Frankie Scott', 'Operations'),
 ('Franklin Adams', 'Sales'),
 ('Franklin Adams', 'Sales'),
 ('Franklin Adams', 'Sales'),
 ('Franklin White', 'Marketing'),
 ('Franklin White', 'Marketing'),
 ('Franklin White', 'Marketing'),
 ('Gabriella Hughes', 'Design'),
 ('Gabriella Hughes', 'Design'),
 ('Gabriella Hughes', 'Design'),
 ('George Allen', 'Product'),
 ('George Allen', 'Product'),
 ('George Allen', 'Product'),
 ('George Harris', 'Business'),
 ('George Harris', 'Business'),
 ('George Harris', 'Business'),
 ('George Murphy', 'Design'),
 ('George Murphy', 'Design'),
 ('George Murphy', 'Design'),
 ('George White', 'IT'),
 ('George White', 'IT'),
 ('George White', 'IT'),
 ('George Wilson', 'Design'),
 ('George Wilson', 'Design'),
 ('George Wilson', 'Design'),
 ('Gina Clark', 'Finance'),
 ('Gina Clark', 'Finance'),
 ('Gina Clark', 'Finance'),
 ('Gina Cooper', 'Marketing'),
 ('Gina Cooper', 'Marketing'),
 ('Gina Cooper', 'Marketing'),
 ('Gina Wood', 'Product'),
 ('Gina Wood', 'Product'),
 ('Gina Wood', 'Product'),
 ('Gina Wood', 'Product'),
 ('Gina Wood', 'Product'),
 ('Gina Wood', 'Product'),
 ('Grace Adams', 'Finance'),
 ('Grace Adams', 'Finance'),
 ('Grace Adams', 'Finance'),
 ('Grace Johnson', 'Marketing'),
 ('Grace Johnson', 'Marketing'),
 ('Grace Johnson', 'Marketing'),
 ('Grace King', 'Marketing'),
 ('Grace King', 'Marketing'),
 ('Grace King', 'Marketing'),
 ('Grace Lee', 'Marketing'),
 ('Grace Lee', 'Marketing'),
 ('Grace Lee', 'Marketing'),
 ('Grace Martinez', 'Marketing'),
 ('Grace Martinez', 'Marketing'),
 ('Grace Martinez', 'Marketing'),
 ('Grace Miller', 'Product'),
 ('Grace Miller', 'Product'),
 ('Grace Miller', 'Product'),
 ('Grace Turner', 'HR'),
 ('Grace Turner', 'HR'),
 ('Grace Turner', 'HR'),
 ('Grace Turner', 'HR'),
 ('Grace Turner', 'HR'),
 ('Grace Turner', 'HR'),
 ('Gwen Lewis', 'PR'),
 ('Gwen Lewis', 'PR'),
 ('Gwen Lewis', 'PR'),
 ('Hank Wright', 'Research'),
 ('Hank Wright', 'Research'),
 ('Hank Wright', 'Research'),
 ('Hannah Allen', 'Finance'),
 ('Hannah Allen', 'Finance'),
 ('Hannah Allen', 'Finance'),
 ('Hannah Carter', 'Product'),
 ('Hannah Carter', 'Product'),
 ('Hannah Carter', 'Product'),
 ('Hannah Collins', 'Support'),
 ('Hannah Collins', 'Support'),
 ('Hannah Collins', 'Support'),
 ('Hannah King', 'Content'),
 ('Hannah King', 'Content'),
 ('Hannah King', 'Content'),
 ('Hannah Lewis', 'Support'),
 ('Hannah Lewis', 'Support'),
 ('Hannah Lewis', 'Support'),
 ('Harrison Davis', 'HR'),
 ('Harrison Davis', 'HR'),
 ('Harrison Davis', 'HR'),
 ('Harry Alexander', 'IT'),
 ('Harry Alexander', 'IT'),
 ('Harry Alexander', 'IT'),
 ('Harry Johnson', 'Support'),
 ('Harry Johnson', 'Support'),
 ('Harry Johnson', 'Support'),
 ('Henry Davis', 'Finance'),
 ('Henry Davis', 'Finance'),
 ('Henry Davis', 'Finance'),
 ('Henry Green', 'Marketing'),
 ('Henry Green', 'Marketing'),
 ('Henry Green', 'Marketing'),
 ('Henry Green', 'Marketing'),
 ('Henry Green', 'Marketing'),
 ('Henry Green', 'Marketing'),
 ('Henry Roberts', 'IT'),
 ('Henry Roberts', 'Marketing'),
 ('Henry Roberts', 'Marketing'),
 ('Henry Roberts', 'IT'),
 ('Henry Roberts', 'Marketing'),
 ('Henry Roberts', 'Marketing'),
 ('Henry Roberts', 'IT'),
 ('Henry Roberts', 'Marketing'),
 ('Henry Roberts', 'Marketing'),
 ('Henry Robinson', 'Business'),
 ('Henry Robinson', 'Business'),
 ('Henry Robinson', 'Business'),
 ('Henry Walker', 'IT'),
 ('Henry Walker', 'IT'),
 ('Henry Walker', 'IT'),
 ('Holly Adams', 'Product'),
 ('Holly Adams', 'Product'),
 ('Holly Adams', 'Product'),
 ('Holly Martinez', 'Content'),
 ('Holly Martinez', 'Content'),
 ('Holly Martinez', 'Content'),
 ('Ian Clark', 'Operations'),
 ('Ian Clark', 'Operations'),
 ('Ian Clark', 'Operations'),
 ('Ian Martinez', 'Sales'),
 ('Ian Martinez', 'Product'),
 ('Ian Martinez', 'Sales'),
 ('Ian Martinez', 'Product'),
 ('Ian Martinez', 'Sales'),
 ('Ian Martinez', 'Product'),
 ('Ian Reed', 'Sales'),
 ('Ian Reed', 'Sales'),
 ('Ian Reed', 'Sales'),
 ('Ian Thompson', 'Marketing'),
 ('Ian Thompson', 'Marketing'),
 ('Ian Thompson', 'Marketing'),
 ('Ian Young', 'Operations'),
 ('Ian Young', 'Operations'),
 ('Ian Young', 'Operations'),
 ('Iris Lee', 'Business'),
 ('Iris Lee', 'Business'),
 ('Iris Lee', 'Business'),
 ('Isaac Turner', 'Business'),
 ('Isaac Turner', 'Business'),
 ('Isaac Turner', 'Business'),
 ('Isabella Clark', 'Design'),
 ('Isabella Clark', 'Design'),
 ('Isabella Clark', 'Design'),
 ('Isabella Harris', 'Design'),
 ('Isabella Harris', 'Design'),
 ('Isabella Harris', 'Design'),
 ('Isabella Walker', 'Operations'),
 ('Isabella Walker', 'Operations'),
 ('Isabella Walker', 'Operations'),
 ('Isabelle Smith', 'HR'),
 ('Isabelle Smith', 'HR'),
 ('Isabelle Smith', 'HR'),
 ('Isabelle Turner', 'Sales'),
 ('Isabelle Turner', 'Sales'),
 ('Isabelle Turner', 'Sales'),
 ('Ivy Brooks', 'Marketing'),
 ('Ivy Brooks', 'Marketing'),
 ('Ivy Brooks', 'Marketing'),
 ('Ivy Lee', 'Product'),
 ('Ivy Lee', 'Product'),
 ('Ivy Lee', 'Product'),
 ('Ivy Lee', 'Product'),
 ('Ivy Lee', 'Product'),
 ('Ivy Lee', 'Product'),
 ('Ivy Robinson', 'Sales'),
 ('Ivy Robinson', 'Sales'),
 ('Ivy Robinson', 'Sales'),
 ('Ivy Wright', 'Sales'),
 ('Ivy Wright', 'Sales'),
 ('Ivy Wright', 'Sales'),
 ('Ivy Wright', 'Sales'),
 ('Ivy Wright', 'Sales'),
 ('Ivy Wright', 'Sales'),
 ('Jack Brown', 'Product'),
 ('Jack Brown', 'Product'),
 ('Jack Brown', 'Product'),
 ('Jack Lee', 'Support'),
 ('Jack Lee', 'Support'),
 ('Jack Lee', 'Design'),
 ('Jack Lee', 'Support'),
 ('Jack Lee', 'Support'),
 ('Jack Lee', 'Design'),
 ('Jack Lee', 'Support'),
 ('Jack Lee', 'Support'),
 ('Jack Lee', 'Design'),
 ('Jack Martin', 'IT'),
 ('Jack Martin', 'IT'),
 ('Jack Martin', 'IT'),
 ('Jack Morris', 'Operations'),
 ('Jack Morris', 'Operations'),
 ('Jack Morris', 'Operations'),
 ('Jack White', 'Operations'),
 ('Jack White', 'Operations'),
 ('Jack White', 'Operations'),
 ('Jackie Clark', 'Operations'),
 ('Jackie Clark', 'Operations'),
 ('Jackie Clark', 'Operations'),
 ('Jackie Sanders', 'Finance'),
 ('Jackie Sanders', 'Finance'),
 ('Jackie Sanders', 'Finance'),
 ('Jacob White', 'Design'),
 ('Jacob White', 'Design'),
 ('Jacob White', 'Design'),
 ('James Anderson', 'Design'),
 ('James Anderson', 'Design'),
 ('James Anderson', 'Design'),
 ('James Anderson', 'Design'),
 ('James Anderson', 'Design'),
 ('James Anderson', 'Design'),
 ('Jasmine Adams', 'Marketing'),
 ('Jasmine Adams', 'Marketing'),
 ('Jasmine Adams', 'Marketing'),
 ('Jasmine Clark', 'Marketing'),
 ('Jasmine Clark', 'Marketing'),
 ('Jasmine Clark', 'Marketing'),
 ('Jasmine Wright', 'Marketing'),
 ('Jasmine Wright', 'Marketing'),
 ('Jasmine Wright', 'Marketing'),
 ('Jasmine Young', 'Operations'),
 ('Jasmine Young', 'Operations'),
 ('Jasmine Young', 'Operations'),
 ('John David', 'IT'),
 ('John David', 'IT'),
 ('John Doe', 'IT'),
 ('John Doe', 'IT'),
 ('John Doe', 'IT'),
 ('Julia Carter', 'Operations'),
 ('Julia Carter', 'Operations'),
 ('Julia Carter', 'Operations'),
 ('Julia Davis', 'Marketing'),
 ('Julia Davis', 'Marketing'),
 ('Julia Davis', 'Marketing'),
 ('Julia Turner', 'Finance'),
 ('Julia Turner', 'Finance'),
 ('Julia Turner', 'Finance'),
 ('Kara Edwards', 'Content'),
 ('Kara Edwards', 'Content'),
 ('Kara Edwards', 'Content'),
 ('Kara Scott', 'Operations'),
 ('Kara Scott', 'Operations'),
 ('Kara Scott', 'Operations'),
 ('Karen Lewis', 'HR'),
 ('Karen Lewis', 'HR'),
 ('Karen Lewis', 'HR'),
 ('Karen Young', 'Finance'),
 ('Karen Young', 'Finance'),
 ('Karen Young', 'Finance'),
 ('Katherine Thompson', 'Sales'),
 ('Katherine Thompson', 'Sales'),
 ('Katherine Thompson', 'Sales'),
 ('Katherine Thompson', 'Sales'),
 ('Katherine Thompson', 'Sales'),
 ('Katherine Thompson', 'Sales'),
 ('Keith Ross', 'IT'),
 ('Keith Ross', 'IT'),
 ('Keith Ross', 'IT'),
 ('Kelly Young', 'IT'),
 ('Kelly Young', 'IT'),
 ('Kelly Young', 'IT'),
 ('Kelly Young', 'IT'),
 ('Kelly Young', 'IT'),
 ('Kelly Young', 'IT'),
 ('Kelsey Davis', 'Finance'),
 ('Kelsey Davis', 'Finance'),
 ('Kelsey Davis', 'Finance'),
 ('Kevin Moore', 'Design'),
 ('Kevin Moore', 'Design'),
 ('Kevin Moore', 'Design'),
 ('Kevin Scott', 'HR'),
 ('Kevin Scott', 'HR'),
 ('Kevin Scott', 'HR'),
 ('Kevin White', 'Business'),
 ('Kevin White', 'Business'),
 ('Kevin White', 'Business'),
 ('Kimberly Lee', 'Support'),
 ('Kimberly Lee', 'Support'),
 ('Kimberly Lee', 'Support'),
 ('Kurt Harris', 'Product'),
 ('Kurt Harris', 'Product'),
 ('Kurt Harris', 'Product'),
 ('Kyle Anderson', 'Marketing'),
 ('Kyle Anderson', 'Marketing'),
 ('Kyle Anderson', 'Marketing'),
 ('Kyle Roberts', 'Business'),
 ('Kyle Roberts', 'Business'),
 ('Kyle Roberts', 'Business'),
 ('Kylie Moore', 'Product'),
 ('Kylie Moore', 'Product'),
 ('Kylie Moore', 'Product'),
 ('Laura Adams', 'Marketing'),
 ('Laura Adams', 'Marketing'),
 ('Laura Adams', 'Marketing'),
 ('Laura Evans', 'Design'),
 ('Laura Evans', 'Design'),
 ('Laura Evans', 'Design'),
 ('Laura Green', 'Design'),
 ('Laura Green', 'Design'),
 ('Laura Green', 'Design'),
 ('Laura Jenkins', 'Marketing'),
 ('Laura Jenkins', 'Marketing'),
 ('Laura Jenkins', 'Marketing'),
 ('Laura Nelson', 'Design'),
 ('Laura Nelson', 'Design'),
 ('Laura Nelson', 'Design'),
 ('Laura Robinson', 'Business'),
 ('Laura Robinson', 'Business'),
 ('Laura Robinson', 'Business'),
 ('Laura Robinson', 'Business'),
 ('Laura Robinson', 'Business'),
 ('Laura Robinson', 'Business'),
 ('Leo Bennett', 'PR'),
 ('Leo Bennett', 'PR'),
 ('Leo Bennett', 'PR'),
 ('Leo Martin', 'HR'),
 ('Leo Martin', 'HR'),
 ('Leo Martin', 'HR'),
 ('Liam Carter', 'Marketing'),
 ('Liam Carter', 'Marketing'),
 ('Liam Carter', 'Marketing'),
 ('Liam Clark', 'Operations'),
 ('Liam Clark', 'Operations'),
 ('Liam Clark', 'Operations'),
 ('Liam Clark', 'Operations'),
 ('Liam Clark', 'Operations'),
 ('Liam Clark', 'Operations'),
 ('Liam Harris', 'Marketing'),
 ('Liam Harris', 'Marketing'),
 ('Liam Harris', 'Marketing'),
 ('Liam Moore', 'Support'),
 ('Liam Moore', 'Support'),
 ('Liam Moore', 'Support'),
 ('Liam Moore', 'Support'),
 ('Liam Moore', 'Support'),
 ('Liam Moore', 'Support'),
 ('Liam Scott', 'IT'),
 ('Liam Scott', 'Operations'),
 ('Liam Scott', 'IT'),
 ('Liam Scott', 'Operations'),
 ('Liam Scott', 'IT'),
 ('Liam Scott', 'Operations'),
 ('Liam Williams', 'Product'),
 ('Liam Williams', 'Product'),

In [25]:
# Sort employees by name and Display name and Dept

%%sql
SELECT Name, Department
FROM employee
ORDER BY Name
Limit 10;

 * sqlite:///NewDB.sqlite3
Done.

[('Aidan Brooks', 'Support'),
 ('Aidan Brooks', 'Support'),
 ('Aidan Brooks', 'Support'),
 ('Aidan Carter', 'Business'),
 ('Aidan Carter', 'Business'),
 ('Aidan Carter', 'Business'),
 ('Aiden Gray', 'Project'),
 ('Aiden Gray', 'Project'),
 ('Aiden Gray', 'Project'),
 ('Aiden Green', 'IT')]

In [26]:
# Sort employees by name and Display name and Dept

%%sql
SELECT Name, Department
FROM employee
ORDER BY Name DESC
Limit 10 ;

 * sqlite:///NewDB.sqlite3
Done.

[('Zara Wright', 'Business'),
 ('Zara Wright', 'Business'),
 ('Zara Wright', 'Business'),
 ('Zane Williams', 'Design'),
 ('Zane Williams', 'Design'),
 ('Zane Williams', 'Design'),
 ('Zane Williams', 'Design'),
 ('Zane Williams', 'Design'),
 ('Zane Williams', 'Design'),
 ('Zane Walker', 'HR')]

In [27]:
#  Names of employees who have not received any promotions.

%%sql

SELECT Name FROM employee WHERE Number_of_Promotions = 0;

 * sqlite:///NewDB.sqlite3
Done.

[('Charlie Davis',),
 ('Grace Lee',),
 ('Liam Carter',),
 ('Paul Green',),
 ('Victor Phillips',),
 ('Anna Rogers',),
 ('Francis Diaz',),
 ('Mike Griffin',),
 ('Uma Grant',),
 ('Isabella Clark',),
 ('Quinn Rivera',),
 ('Umar Green',),
 ('Liam Scott',),
 ('Aiden Green',),
 ('Riley Baker',),
 ('Vera Long',),
 ('Ariana Lopez',),
 ('Kurt Harris',),
 ('Olivia Campbell',),
 ('Samantha Wilson',),
 ('Eva Sanchez',),
 ('Mia Gray',),
 ('Nina Price',),
 ('Parker Reed',),
 ('Willow Young',),
 ('Aidan Carter',),
 ('Jasmine Clark',),
 ('Michael Lopez',),
 ('Oliver Walker',),
 ('Sam Mitchell',),
 ('Ursula Rivera',),
 ('Zachary Morris',),
 ('Clara Morgan',),
 ('Eva Lewis',),
 ('Julia Carter',),
 ('Nina Evans',),
 ('Ryan Clark',),
 ('Thomas Allen',),
 ('Xander Walker',),
 ('Ariana Davis',),
 ('Emily Harris',),
 ('Henry Green',),
 ('Kelly Young',),
 ('Megan Thompson',),
 ('Olivia Martinez',),
 ('Quinn Cooper',),
 ('Tina Williams',),
 ('Zane Smith',),
 ('Cindy Brown',),
 ('Grace Turner',),
 ('Katherine Thompson',),
 ('Liam Moore',),
 ('Paul Lewis',),
 ('Tina Evans',),
 ('Will Turner',),
 ('Zane Williams',),
 ('Nina Evans',),
 ('Ryan Clark',),
 ('Thomas Allen',),
 ('Xander Walker',),
 ('Ariana Davis',),
 ('Emily Harris',),
 ('Henry Green',),
 ('Kelly Young',),
 ('Megan Thompson',),
 ('Olivia Martinez',),
 ('Quinn Cooper',),
 ('Tina Williams',),
 ('Zane Smith',),
 ('Cindy Brown',),
 ('Grace Turner',),
 ('Katherine Thompson',),
 ('Liam Moore',),
 ('Paul Lewis',),
 ('Tina Evans',),
 ('Will Turner',),
 ('Zane Williams',),
 ('Becca Davis',),
 ('Ethan Harris',),
 ('Jasmine Adams',),
 ('Natalie Brown',),
 ('Quincy Harris',),
 ('Sophie Turner',),
 ('Xander Lee',),
 ('Zane Walker',),
 ('Catherine Carter',),
 ('Olivia Johnson',),
 ('Quinn Evans',),
 ('Vera White',),
 ('Aiden Martinez',),
 ('Carlos Adams',),
 ('Fiona Turner',),
 ('Ian Clark',),
 ('Brianna Scott',),
 ('Fiona Bell',),
 ('Ian Reed',),
 ('Jasmine Young',),
 ('Michael Green',),
 ('Paige Turner',),
 ('Victor Lewis',),
 ('Wendy Scott',),
 ('Zachary Wilson',),
 ('Emma Wilson',),
 ('Isabella Walker',),
 ('Leo Martin',),
 ('Mia Lewis',),
 ('Quinn Moore',),
 ('Sophia Lewis',),
 ('Xena Lewis',),
 ('Yvette Turner',),
 ('David Green',),
 ('Grace Johnson',),
 ('Oscar Wilson',),
 ('Quincy Adams',),
 ('Tina Green',),
 ('Vera Adams',),
 ('John David',),
 ('Olivia Adams',),
 ('Charlie Davis',),
 ('Grace Lee',),
 ('Liam Carter',),
 ('Paul Green',),
 ('Victor Phillips',),
 ('Anna Rogers',),
 ('Francis Diaz',),
 ('Mike Griffin',),
 ('Uma Grant',),
 ('Isabella Clark',),
 ('Quinn Rivera',),
 ('Umar Green',),
 ('Liam Scott',),
 ('Aiden Green',),
 ('Riley Baker',),
 ('Vera Long',),
 ('Ariana Lopez',),
 ('Kurt Harris',),
 ('Olivia Campbell',),
 ('Samantha Wilson',),
 ('Eva Sanchez',),
 ('Mia Gray',),
 ('Nina Price',),
 ('Parker Reed',),
 ('Willow Young',),
 ('Aidan Carter',),
 ('Jasmine Clark',),
 ('Michael Lopez',),
 ('Oliver Walker',),
 ('Sam Mitchell',),
 ('Ursula Rivera',),
 ('Zachary Morris',),
 ('Clara Morgan',),
 ('Eva Lewis',),
 ('Julia Carter',),
 ('Nina Evans',),
 ('Ryan Clark',),
 ('Thomas Allen',),
 ('Xander Walker',),
 ('Ariana Davis',),
 ('Emily Harris',),
 ('Henry Green',),
 ('Kelly Young',),
 ('Megan Thompson',),
 ('Olivia Martinez',),
 ('Quinn Cooper',),
 ('Tina Williams',),
 ('Zane Smith',),
 ('Cindy Brown',),
 ('Grace Turner',),
 ('Katherine Thompson',),
 ('Liam Moore',),
 ('Paul Lewis',),
 ('Tina Evans',),
 ('Will Turner',),
 ('Zane Williams',),
 ('Nina Evans',),
 ('Ryan Clark',),
 ('Thomas Allen',),
 ('Xander Walker',),
 ('Ariana Davis',),
 ('Emily Harris',),
 ('Henry Green',),
 ('Kelly Young',),
 ('Megan Thompson',),
 ('Olivia Martinez',),
 ('Quinn Cooper',),
 ('Tina Williams',),
 ('Zane Smith',),
 ('Cindy Brown',),
 ('Grace Turner',),
 ('Katherine Thompson',),
 ('Liam Moore',),
 ('Paul Lewis',),
 ('Tina Evans',),
 ('Will Turner',),
 ('Zane Williams',),
 ('Becca Davis',),
 ('Ethan Harris',),
 ('Jasmine Adams',),
 ('Natalie Brown',),
 ('Quincy Harris',),
 ('Sophie Turner',),
 ('Xander Lee',),
 ('Zane Walker',),
 ('Catherine Carter',),
 ('Olivia Johnson',),
 ('Quinn Evans',),
 ('Vera White',),
 ('Aiden Martinez',),
 ('Carlos Adams',),
 ('Fiona Turner',),
 ('Ian Clark',),
 ('Brianna Scott',),
 ('Fiona Bell',),
 ('Ian Reed',),
 ('Jasmine Young',),
 ('Michael Green',),
 ('Paige Turner',),
 ('Victor Lewis',),
 ('Wendy Scott',),
 ('Zachary Wilson',),
 ('Emma Wilson',),
 ('Isabella Walker',),
 ('Leo Martin',),
 ('Mia Lewis',),
 ('Quinn Moore',),
 ('Sophia Lewis',),
 ('Xena Lewis',),
 ('Yvette Turner',),
 ('David Green',),
 ('Grace Johnson',),
 ('Oscar Wilson',),
 ('Quincy Adams',),
 ('Tina Green',),
 ('Vera Adams',),
 ('John David',),
 ('Olivia Adams',),
 ('Charlie Davis',),
 ('Grace Lee',),
 ('Liam Carter',),
 ('Paul Green',),
 ('Victor Phillips',),
 ('Anna Rogers',),
 ('Francis Diaz',),
 ('Mike Griffin',),
 ('Uma Grant',),
 ('Isabella Clark',),
 ('Quinn Rivera',),
 ('Umar Green',),
 ('Liam Scott',),
 ('Aiden Green',),
 ('Riley Baker',),
 ('Vera Long',),
 ('Ariana Lopez',),
 ('Kurt Harris',),
 ('Olivia Campbell',),
 ('Samantha Wilson',),
 ('Eva Sanchez',),
 ('Mia Gray',),
 ('Nina Price',),
 ('Parker Reed',),
 ('Willow Young',),
 ('Aidan Carter',),
 ('Jasmine Clark',),
 ('Michael Lopez',),
 ('Oliver Walker',),
 ('Sam Mitchell',),
 ('Ursula Rivera',),
 ('Zachary Morris',),
 ('Clara Morgan',),
 ('Eva Lewis',),
 ('Julia Carter',),
 ('Nina Evans',),
 ('Ryan Clark',),
 ('Thomas Allen',),
 ('Xander Walker',),
 ('Ariana Davis',),
 ('Emily Harris',),
 ('Henry Green',),
 ('Kelly Young',),
 ('Megan Thompson',),
 ('Olivia Martinez',),
 ('Quinn Cooper',),
 ('Tina Williams',),
 ('Zane Smith',),
 ('Cindy Brown',),
 ('Grace Turner',),
 ('Katherine Thompson',),
 ('Liam Moore',),
 ('Paul Lewis',),
 ('Tina Evans',),
 ('Will Turner',),
 ('Zane Williams',),
 ('Nina Evans',),
 ('Ryan Clark',),
 ('Thomas Allen',),
 ('Xander Walker',),
 ('Ariana Davis',),
 ('Emily Harris',),
 ('Henry Green',),
 ('Kelly Young',),
 ('Megan Thompson',),
 ('Olivia Martinez',),
 ('Quinn Cooper',),
 ('Tina Williams',),
 ('Zane Smith',),
 ('Cindy Brown',),
 ('Grace Turner',),
 ('Katherine Thompson',),
 ('Liam Moore',),
 ('Paul Lewis',),
 ('Tina Evans',),
 ('Will Turner',),
 ('Zane Williams',),
 ('Becca Davis',),
 ('Ethan Harris',),
 ('Jasmine Adams',),
 ('Natalie Brown',),
 ('Quincy Harris',),
 ('Sophie Turner',),
 ('Xander Lee',),
 ('Zane Walker',),
 ('Catherine Carter',),
 ('Olivia Johnson',),
 ('Quinn Evans',),
 ('Vera White',),
 ('Aiden Martinez',),
 ('Carlos Adams',),
 ('Fiona Turner',),
 ('Ian Clark',),
 ('Brianna Scott',),
 ('Fiona Bell',),
 ('Ian Reed',),
 ('Jasmine Young',),
 ('Michael Green',),
 ('Paige Turner',),
 ('Victor Lewis',),
 ('Wendy Scott',),
 ('Zachary Wilson',),
 ('Emma Wilson',),
 ('Isabella Walker',),
 ('Leo Martin',),
 ('Mia Lewis',),
 ('Quinn Moore',),
 ('Sophia Lewis',),
 ('Xena Lewis',),
 ('Yvette Turner',),
 ('David Green',),
 ('Grace Johnson',),
 ('Oscar Wilson',),
 ('Quincy Adams',),
 ('Tina Green',),
 ('Vera Adams',)]

In [28]:
# SELECT Name FROM employee WHERE Number_of_Promotions = 0 and Salary less than average salary
%%sql
SELECT Name
FROM employee
WHERE Number_of_Promotions = 0
  AND Salary < (SELECT AVG(Salary) FROM employee)
LIMIT 10;

 * sqlite:///NewDB.sqlite3
Done.

[('Charlie Davis',),
 ('Grace Lee',),
 ('Liam Carter',),
 ('Paul Green',),
 ('Victor Phillips',),
 ('Anna Rogers',),
 ('Francis Diaz',),
 ('Mike Griffin',),
 ('Uma Grant',),
 ('Isabella Clark',)]

In [29]:
# The names and performance ratings of employees with a performance rating greater than 4.5.

%%sql
SELECT Name, Performance_Rating
FROM employee
WHERE Performance_Rating > 4.5
LIMIT 10;

 * sqlite:///NewDB.sqlite3
Done.

[('Bob Brown', 4.7),
 ('Frank White', 4.6),
 ('Henry Walker', 4.7),
 ('Karen Young', 4.8),
 ('Olivia Lewis', 4.6),
 ('Quinn Scott', 4.7),
 ('Tina Hall', 4.6),
 ('Zachary Morris', 4.7),
 ('Daniel Foster', 4.6),
 ('Eleanor Reed', 4.8)]

In [30]:
# Total number of leaves taken by all employees.

%%sql
SELECT SUM(Number_of_Leaves) FROM employee;

 * sqlite:///NewDB.sqlite3
Done.

[(15256,)]

In [31]:
# The names of employees who have taken between 8 and 10 leaves.

%%sql
SELECT Name
FROM employee
WHERE Number_of_Leaves BETWEEN 8 AND 10
LIMIT 5;

 * sqlite:///NewDB.sqlite3
Done.

[('John Doe',),
 ('Eva Taylor',),
 ('Jack Martin',),
 ('Noah Roberts',),
 ('Olivia Lewis',)]

In [32]:
# The names and salaries of employees who are either in the 'HR' or 'Finance' department.

%%sql
SELECT Name, Salary
FROM employee
WHERE Department IN ('HR', 'Finance')
LIMIT 10;

 * sqlite:///NewDB.sqlite3
Done.

[('Bob Brown', 80000.0),
 ('Karen Young', 85000.0),
 ('Tina Hall', 64000.0),
 ('Wendy Campbell', 65000.0),
 ('Eleanor Reed', 78000.0),
 ('Jackie Sanders', 65000.0),
 ('Tina Adams', 74000.0),
 ('Carol Taylor', 63000.0),
 ('Frank Garcia', 75000.0),
 ('Karen Lewis', 74000.0)]

In [33]:
# Names of employees whose names start with the letter 'J'.

%%sql
SELECT Name
FROM employee
WHERE Name LIKE 'J%'

 * sqlite:///NewDB.sqlite3
Done.

[('John Doe',),
 ('Jack Martin',),
 ('Jackie Sanders',),
 ('Jack White',),
 ('Jackie Clark',),
 ('Julia Turner',),
 ('Jasmine Wright',),
 ('Jack Morris',),
 ('Jasmine Clark',),
 ('Julia Carter',),
 ('Jack Lee',),
 ('James Anderson',),
 ('Jack Lee',),
 ('James Anderson',),
 ('Jasmine Adams',),
 ('Jack Lee',),
 ('Julia Davis',),
 ('Jasmine Young',),
 ('Jacob White',),
 ('Jack Brown',),
 ('John David',),
 ('John Doe',),
 ('Jack Martin',),
 ('Jackie Sanders',),
 ('Jack White',),
 ('Jackie Clark',),
 ('Julia Turner',),
 ('Jasmine Wright',),
 ('Jack Morris',),
 ('Jasmine Clark',),
 ('Julia Carter',),
 ('Jack Lee',),
 ('James Anderson',),
 ('Jack Lee',),
 ('James Anderson',),
 ('Jasmine Adams',),
 ('Jack Lee',),
 ('Julia Davis',),
 ('Jasmine Young',),
 ('Jacob White',),
 ('Jack Brown',),
 ('John David',),
 ('John Doe',),
 ('Jack Martin',),
 ('Jackie Sanders',),
 ('Jack White',),
 ('Jackie Clark',),
 ('Julia Turner',),
 ('Jasmine Wright',),
 ('Jack Morris',),
 ('Jasmine Clark',),
 ('Julia Carter',),
 ('Jack Lee',),
 ('James Anderson',),
 ('Jack Lee',),
 ('James Anderson',),
 ('Jasmine Adams',),
 ('Jack Lee',),
 ('Julia Davis',),
 ('Jasmine Young',),
 ('Jacob White',),
 ('Jack Brown',)]

In [34]:
# The names of employees who have more than 3 years of experience but less than 5.

%%sql
SELECT Name, Date_of_Joining
FROM employee
WHERE Date('now') - Date(Date_of_Joining) BETWEEN 2 AND 5

 * sqlite:///NewDB.sqlite3
Done.

[('Grace Lee', '2019-03-22'),
 ('Sophie Turner', '2019-01-15'),
 ('Quinn Evans', '2019-01-15'),
 ('Fiona Bell', '2019-01-15'),
 ('Paige Turner', '2019-03-10'),
 ('Isabella Walker', '2019-02-15'),
 ('Quinn Moore', '2019-01-15'),
 ('Oscar Wilson', '2019-03-20'),
 ('Aiden Lee', '2019-08-20'),
 ('Olivia Adams', '2020-02-15'),
 ('Grace Lee', '2019-03-22'),
 ('Sophie Turner', '2019-01-15'),
 ('Quinn Evans', '2019-01-15'),
 ('Fiona Bell', '2019-01-15'),
 ('Paige Turner', '2019-03-10'),
 ('Isabella Walker', '2019-02-15'),
 ('Quinn Moore', '2019-01-15'),
 ('Oscar Wilson', '2019-03-20'),
 ('Aiden Lee', '2019-08-20'),
 ('Olivia Adams', '2020-02-15'),
 ('Grace Lee', '2019-03-22'),
 ('Sophie Turner', '2019-01-15'),
 ('Quinn Evans', '2019-01-15'),
 ('Fiona Bell', '2019-01-15'),
 ('Paige Turner', '2019-03-10'),
 ('Isabella Walker', '2019-02-15'),
 ('Quinn Moore', '2019-01-15'),
 ('Oscar Wilson', '2019-03-20')]

In [35]:
# The names of employees who have more than 15 years and five months

%%sql
SELECT Name, Date_of_Joining
FROM employee
WHERE Date('now') - Date(Date_of_Joining) > 15.41

 * sqlite:///NewDB.sqlite3
Done.

[('Bob Brown', '2008-03-30'),
 ('Bob Brown', '2008-03-30'),
 ('Bob Brown', '2008-03-30')]

In [36]:
# Names of employees who have taken more than the average number of leaves.

%%sql
SELECT Name
FROM employee
WHERE Number_of_Leaves > (SELECT AVG(Number_of_Leaves) FROM employee)

 * sqlite:///NewDB.sqlite3
Done.

[('Alice Johnson',),
 ('Charlie Davis',),
 ('David Miller',),
 ('Grace Lee',),
 ('Isabella Harris',),
 ('Liam Carter',),
 ('Mia Thompson',),
 ('Paul Green',),
 ('Samuel Wright',),
 ('Victor Phillips',),
 ('Xander James',),
 ('Anna Rogers',),
 ('Brian Nelson',),
 ('Francis Diaz',),
 ('Harry Alexander',),
 ('Ivy Brooks',),
 ('Mike Griffin',),
 ('Oscar Daniels',),
 ('Quentin Collins',),
 ('Uma Grant',),
 ('Wendy Edwards',),
 ('Xander Fox',),
 ('Alice Johnson',),
 ('Eva Wilson',),
 ('Grace Martinez',),
 ('Isabella Clark',),
 ('Liam Harris',),
 ('Olivia Scott',),
 ('Quinn Rivera',),
 ('Sam Parker',),
 ('Umar Green',),
 ('Vanessa Young',),
 ('Ximena Cooper',),
 ('Yvonne Campbell',),
 ('Amelia Moore',),
 ('Charlotte Davis',),
 ('Grace King',),
 ('Liam Scott',),
 ('Nate Williams',),
 ('Quinn Howard',),
 ('Rose Ward',),
 ('Victor Ramirez',),
 ('Xavier Hughes',),
 ('Aiden Green',),
 ('Daisy Harris',),
 ('George White',),
 ('Hannah King',),
 ('Lila Davis',),
 ('Nora Gonzalez',),
 ('Oscar Miller',),
 ('Riley Baker',),
 ('Sophia Evans',),
 ('Uma Robinson',),
 ('Vera Long',),
 ('Xander Wright',),
 ('Yara Hughes',),
 ('Ariana Lopez',),
 ('Blake Adams',),
 ('Ella Brown',),
 ('Isaac Turner',),
 ('Kurt Harris',),
 ('Maya Thompson',),
 ('Olivia Campbell',),
 ('Riley Hernandez',),
 ('Samantha Wilson',),
 ('Ursula Moore',),
 ('Victor White',),
 ('Bradley Evans',),
 ('Charlotte Murphy',),
 ('Eva Sanchez',),
 ('Frankie Scott',),
 ('Leo Bennett',),
 ('Mia Gray',),
 ('Nina Price',),
 ('Parker Reed',),
 ('Riley Evans',),
 ('Sophia Knight',),
 ('Tina Harris',),
 ('Willow Young',),
 ('Xena Gray',),
 ('Bella Martinez',),
 ('Cameron Lee',),
 ('Fiona Green',),
 ('Holly Adams',),
 ('Kevin Scott',),
 ('Natalie Turner',),
 ('Oliver Walker',),
 ('Quincy Morgan',),
 ('Rachel Morris',),
 ('Sam Mitchell',),
 ('Taylor Hughes',),
 ('Ursula Rivera',),
 ('Wendy Allen',),
 ('Zachary Morris',),
 ('Clara Morgan',),
 ('Derek Clark',),
 ('Eva Lewis',),
 ('Grace Miller',),
 ('Ian Thompson',),
 ('Julia Carter',),
 ('Laura Robinson',),
 ('Nina Evans',),
 ('Quinn Wright',),
 ('Ryan Clark',),
 ('Thomas Allen',),
 ('Xander Walker',),
 ('Zachary Miller',),
 ('Ariana Davis',),
 ('Emily Harris',),
 ('Gina Wood',),
 ('Henry Green',),
 ('Jack Lee',),
 ('Kelly Young',),
 ('Liam Clark',),
 ('Megan Thompson',),
 ('Olivia Martinez',),
 ('Patrick Brown',),
 ('Quinn Cooper',),
 ('Sam Rogers',),
 ('Tina Williams',),
 ('Will Scott',),
 ('Yvonne Rodriguez',),
 ('Zane Smith',),
 ('Cindy Brown',),
 ('Felix Martinez',),
 ('Grace Turner',),
 ('Katherine Thompson',),
 ('Liam Moore',),
 ('Paul Lewis',),
 ('Sam Adams',),
 ('Tina Evans',),
 ('Vera Lee',),
 ('Will Turner',),
 ('Zane Williams',),
 ('Laura Robinson',),
 ('Nina Evans',),
 ('Quinn Wright',),
 ('Ryan Clark',),
 ('Thomas Allen',),
 ('Xander Walker',),
 ('Zachary Miller',),
 ('Ariana Davis',),
 ('Emily Harris',),
 ('Gina Wood',),
 ('Henry Green',),
 ('Jack Lee',),
 ('Kelly Young',),
 ('Liam Clark',),
 ('Megan Thompson',),
 ('Olivia Martinez',),
 ('Patrick Brown',),
 ('Quinn Cooper',),
 ('Sam Rogers',),
 ('Tina Williams',),
 ('Will Scott',),
 ('Yvonne Rodriguez',),
 ('Zane Smith',),
 ('Cindy Brown',),
 ('Felix Martinez',),
 ('Grace Turner',),
 ('Katherine Thompson',),
 ('Liam Moore',),
 ('Paul Lewis',),
 ('Sam Adams',),
 ('Tina Evans',),
 ('Vera Lee',),
 ('Will Turner',),
 ('Zane Williams',),
 ('Becca Davis',),
 ('Ethan Harris',),
 ('Jasmine Adams',),
 ('Matthew Smith',),
 ('Natalie Brown',),
 ('Oscar Johnson',),
 ('Quincy Harris',),
 ('Uma Patel',),
 ('Xander Lee',),
 ('Zane Walker',),
 ('Bradley Moore',),
 ('Catherine Carter',),
 ('Emily Evans',),
 ('Kara Scott',),
 ('Noah Smith',),
 ('Olivia Johnson',),
 ('Quinn Evans',),
 ('Vera White',),
 ('Will Carter',),
 ('Aiden Martinez',),
 ('Carlos Adams',),
 ('Fiona Turner',),
 ('Ian Clark',),
 ('Brianna Scott',),
 ('Diana Clark',),
 ('Fiona Bell',),
 ('Hannah Collins',),
 ('Jasmine Young',),
 ('Michael Green',),
 ('Paige Turner',),
 ('Rachel King',),
 ('Ursula Green',),
 ('Victor Lewis',),
 ('Wendy Scott',),
 ('Zachary Wilson',),
 ('Emma Wilson',),
 ('Harry Johnson',),
 ('Isabella Walker',),
 ('Kylie Moore',),
 ('Leo Martin',),
 ('Noah Taylor',),
 ('Quinn Moore',),
 ('Sophia Lewis',),
 ('William Scott',),
 ('Yvette Turner',),
 ('David Green',),
 ('Grace Johnson',),
 ('Matthew Davis',),
 ('Quincy Adams',),
 ('Tina Green',),
 ('Vera Adams',),
 ('Alice Johnson',),
 ('Charlie Davis',),
 ('David Miller',),
 ('Grace Lee',),
 ('Isabella Harris',),
 ('Liam Carter',),
 ('Mia Thompson',),
 ('Paul Green',),
 ('Samuel Wright',),
 ('Victor Phillips',),
 ('Xander James',),
 ('Anna Rogers',),
 ('Brian Nelson',),
 ('Francis Diaz',),
 ('Harry Alexander',),
 ('Ivy Brooks',),
 ('Mike Griffin',),
 ('Oscar Daniels',),
 ('Quentin Collins',),
 ('Uma Grant',),
 ('Wendy Edwards',),
 ('Xander Fox',),
 ('Alice Johnson',),
 ('Eva Wilson',),
 ('Grace Martinez',),
 ('Isabella Clark',),
 ('Liam Harris',),
 ('Olivia Scott',),
 ('Quinn Rivera',),
 ('Sam Parker',),
 ('Umar Green',),
 ('Vanessa Young',),
 ('Ximena Cooper',),
 ('Yvonne Campbell',),
 ('Amelia Moore',),
 ('Charlotte Davis',),
 ('Grace King',),
 ('Liam Scott',),
 ('Nate Williams',),
 ('Quinn Howard',),
 ('Rose Ward',),
 ('Victor Ramirez',),
 ('Xavier Hughes',),
 ('Aiden Green',),
 ('Daisy Harris',),
 ('George White',),
 ('Hannah King',),
 ('Lila Davis',),
 ('Nora Gonzalez',),
 ('Oscar Miller',),
 ('Riley Baker',),
 ('Sophia Evans',),
 ('Uma Robinson',),
 ('Vera Long',),
 ('Xander Wright',),
 ('Yara Hughes',),
 ('Ariana Lopez',),
 ('Blake Adams',),
 ('Ella Brown',),
 ('Isaac Turner',),
 ('Kurt Harris',),
 ('Maya Thompson',),
 ('Olivia Campbell',),
 ('Riley Hernandez',),
 ('Samantha Wilson',),
 ('Ursula Moore',),
 ('Victor White',),
 ('Bradley Evans',),
 ('Charlotte Murphy',),
 ('Eva Sanchez',),
 ('Frankie Scott',),
 ('Leo Bennett',),
 ('Mia Gray',),
 ('Nina Price',),
 ('Parker Reed',),
 ('Riley Evans',),
 ('Sophia Knight',),
 ('Tina Harris',),
 ('Willow Young',),
 ('Xena Gray',),
 ('Bella Martinez',),
 ('Cameron Lee',),
 ('Fiona Green',),
 ('Holly Adams',),
 ('Kevin Scott',),
 ('Natalie Turner',),
 ('Oliver Walker',),
 ('Quincy Morgan',),
 ('Rachel Morris',),
 ('Sam Mitchell',),
 ('Taylor Hughes',),
 ('Ursula Rivera',),
 ('Wendy Allen',),
 ('Zachary Morris',),
 ('Clara Morgan',),
 ('Derek Clark',),
 ('Eva Lewis',),
 ('Grace Miller',),
 ('Ian Thompson',),
 ('Julia Carter',),
 ('Laura Robinson',),
 ('Nina Evans',),
 ('Quinn Wright',),
 ('Ryan Clark',),
 ('Thomas Allen',),
 ('Xander Walker',),
 ('Zachary Miller',),
 ('Ariana Davis',),
 ('Emily Harris',),
 ('Gina Wood',),
 ('Henry Green',),
 ('Jack Lee',),
 ('Kelly Young',),
 ('Liam Clark',),
 ('Megan Thompson',),
 ('Olivia Martinez',),
 ('Patrick Brown',),
 ('Quinn Cooper',),
 ('Sam Rogers',),
 ('Tina Williams',),
 ('Will Scott',),
 ('Yvonne Rodriguez',),
 ('Zane Smith',),
 ('Cindy Brown',),
 ('Felix Martinez',),
 ('Grace Turner',),
 ('Katherine Thompson',),
 ('Liam Moore',),
 ('Paul Lewis',),
 ('Sam Adams',),
 ('Tina Evans',),
 ('Vera Lee',),
 ('Will Turner',),
 ('Zane Williams',),
 ('Laura Robinson',),
 ('Nina Evans',),
 ('Quinn Wright',),
 ('Ryan Clark',),
 ('Thomas Allen',),
 ('Xander Walker',),
 ('Zachary Miller',),
 ('Ariana Davis',),
 ('Emily Harris',),
 ('Gina Wood',),
 ('Henry Green',),
 ('Jack Lee',),
 ('Kelly Young',),
 ('Liam Clark',),
 ('Megan Thompson',),
 ('Olivia Martinez',),
 ('Patrick Brown',),
 ('Quinn Cooper',),
 ('Sam Rogers',),
 ('Tina Williams',),
 ('Will Scott',),
 ('Yvonne Rodriguez',),
 ('Zane Smith',),
 ('Cindy Brown',),
 ('Felix Martinez',),
 ('Grace Turner',),
 ('Katherine Thompson',),
 ('Liam Moore',),
 ('Paul Lewis',),
 ('Sam Adams',),
 ('Tina Evans',),
 ('Vera Lee',),
 ('Will Turner',),
 ('Zane Williams',),
 ('Becca Davis',),
 ('Ethan Harris',),
 ('Jasmine Adams',),
 ('Matthew Smith',),
 ('Natalie Brown',),
 ('Oscar Johnson',),
 ('Quincy Harris',),
 ('Uma Patel',),
 ('Xander Lee',),
 ('Zane Walker',),
 ('Bradley Moore',),
 ('Catherine Carter',),
 ('Emily Evans',),
 ('Kara Scott',),
 ('Noah Smith',),
 ('Olivia Johnson',),
 ('Quinn Evans',),
 ('Vera White',),
 ('Will Carter',),
 ('Aiden Martinez',),
 ('Carlos Adams',),
 ('Fiona Turner',),
 ('Ian Clark',),
 ('Brianna Scott',),
 ('Diana Clark',),
 ('Fiona Bell',),
 ('Hannah Collins',),
 ('Jasmine Young',),
 ('Michael Green',),
 ('Paige Turner',),
 ('Rachel King',),
 ('Ursula Green',),
 ('Victor Lewis',),
 ('Wendy Scott',),
 ('Zachary Wilson',),
 ('Emma Wilson',),
 ('Harry Johnson',),
 ('Isabella Walker',),
 ('Kylie Moore',),
 ('Leo Martin',),
 ('Noah Taylor',),
 ('Quinn Moore',),
 ('Sophia Lewis',),
 ('William Scott',),
 ('Yvette Turner',),
 ('David Green',),
 ('Grace Johnson',),
 ('Matthew Davis',),
 ('Quincy Adams',),
 ('Tina Green',),
 ('Vera Adams',),
 ('Alice Johnson',),
 ('Charlie Davis',),
 ('David Miller',),
 ('Grace Lee',),
 ('Isabella Harris',),
 ('Liam Carter',),
 ('Mia Thompson',),
 ('Paul Green',),
 ('Samuel Wright',),
 ('Victor Phillips',),
 ('Xander James',),
 ('Anna Rogers',),
 ('Brian Nelson',),
 ('Francis Diaz',),
 ('Harry Alexander',),
 ('Ivy Brooks',),
 ('Mike Griffin',),
 ('Oscar Daniels',),
 ('Quentin Collins',),
 ('Uma Grant',),
 ('Wendy Edwards',),
 ('Xander Fox',),
 ('Alice Johnson',),
 ('Eva Wilson',),
 ('Grace Martinez',),
 ('Isabella Clark',),
 ('Liam Harris',),
 ('Olivia Scott',),
 ('Quinn Rivera',),
 ('Sam Parker',),
 ('Umar Green',),
 ('Vanessa Young',),
 ('Ximena Cooper',),
 ('Yvonne Campbell',),
 ('Amelia Moore',),
 ('Charlotte Davis',),
 ('Grace King',),
 ('Liam Scott',),
 ('Nate Williams',),
 ('Quinn Howard',),
 ('Rose Ward',),
 ('Victor Ramirez',),
 ('Xavier Hughes',),
 ('Aiden Green',),
 ('Daisy Harris',),
 ('George White',),
 ('Hannah King',),
 ('Lila Davis',),
 ('Nora Gonzalez',),
 ('Oscar Miller',),
 ('Riley Baker',),
 ('Sophia Evans',),
 ('Uma Robinson',),
 ('Vera Long',),
 ('Xander Wright',),
 ('Yara Hughes',),
 ('Ariana Lopez',),
 ('Blake Adams',),
 ('Ella Brown',),
 ('Isaac Turner',),
 ('Kurt Harris',),
 ('Maya Thompson',),
 ('Olivia Campbell',),
 ('Riley Hernandez',),
 ('Samantha Wilson',),
 ('Ursula Moore',),
 ('Victor White',),
 ('Bradley Evans',),
 ('Charlotte Murphy',),
 ('Eva Sanchez',),
 ('Frankie Scott',),
 ('Leo Bennett',),
 ('Mia Gray',),
 ('Nina Price',),
 ('Parker Reed',),
 ('Riley Evans',),
 ('Sophia Knight',),
 ('Tina Harris',),
 ('Willow Young',),
 ('Xena Gray',),
 ('Bella Martinez',),
 ('Cameron Lee',),
 ('Fiona Green',),
 ('Holly Adams',),
 ('Kevin Scott',),
 ('Natalie Turner',),
 ('Oliver Walker',),
 ('Quincy Morgan',),
 ('Rachel Morris',),
 ('Sam Mitchell',),
 ('Taylor Hughes',),
 ('Ursula Rivera',),
 ('Wendy Allen',),
 ('Zachary Morris',),
 ('Clara Morgan',),
 ('Derek Clark',),
 ('Eva Lewis',),
 ('Grace Miller',),
 ('Ian Thompson',),
 ('Julia Carter',),
 ('Laura Robinson',),
 ('Nina Evans',),
 ('Quinn Wright',),
 ('Ryan Clark',),
 ('Thomas Allen',),
 ('Xander Walker',),
 ('Zachary Miller',),
 ('Ariana Davis',),
 ('Emily Harris',),
 ('Gina Wood',),
 ('Henry Green',),
 ('Jack Lee',),
 ('Kelly Young',),
 ('Liam Clark',),
 ('Megan Thompson',),
 ('Olivia Martinez',),
 ('Patrick Brown',),
 ('Quinn Cooper',),
 ('Sam Rogers',),
 ('Tina Williams',),
 ('Will Scott',),
 ('Yvonne Rodriguez',),
 ('Zane Smith',),
 ('Cindy Brown',),
 ('Felix Martinez',),
 ('Grace Turner',),
 ('Katherine Thompson',),
 ('Liam Moore',),
 ('Paul Lewis',),
 ('Sam Adams',),
 ('Tina Evans',),
 ('Vera Lee',),
 ('Will Turner',),
 ('Zane Williams',),
 ('Laura Robinson',),
 ('Nina Evans',),
 ('Quinn Wright',),
 ('Ryan Clark',),
 ('Thomas Allen',),
 ('Xander Walker',),
 ('Zachary Miller',),
 ('Ariana Davis',),
 ('Emily Harris',),
 ('Gina Wood',),
 ('Henry Green',),
 ('Jack Lee',),
 ('Kelly Young',),
 ('Liam Clark',),
 ('Megan Thompson',),
 ('Olivia Martinez',),
 ('Patrick Brown',),
 ('Quinn Cooper',),
 ('Sam Rogers',),
 ('Tina Williams',),
 ('Will Scott',),
 ('Yvonne Rodriguez',),
 ('Zane Smith',),
 ('Cindy Brown',),
 ('Felix Martinez',),
 ('Grace Turner',),
 ('Katherine Thompson',),
 ('Liam Moore',),
 ('Paul Lewis',),
 ('Sam Adams',),
 ('Tina Evans',),
 ('Vera Lee',),
 ('Will Turner',),
 ('Zane Williams',),
 ('Becca Davis',),
 ('Ethan Harris',),
 ('Jasmine Adams',),
 ('Matthew Smith',),
 ('Natalie Brown',),
 ('Oscar Johnson',),
 ('Quincy Harris',),
 ('Uma Patel',),
 ('Xander Lee',),
 ('Zane Walker',),
 ('Bradley Moore',),
 ('Catherine Carter',),
 ('Emily Evans',),
 ('Kara Scott',),
 ('Noah Smith',),
 ('Olivia Johnson',),
 ('Quinn Evans',),
 ('Vera White',),
 ('Will Carter',),
 ('Aiden Martinez',),
 ('Carlos Adams',),
 ('Fiona Turner',),
 ('Ian Clark',),
 ('Brianna Scott',),
 ('Diana Clark',),
 ('Fiona Bell',),
 ('Hannah Collins',),
 ('Jasmine Young',),
 ('Michael Green',),
 ('Paige Turner',),
 ('Rachel King',),
 ('Ursula Green',),
 ('Victor Lewis',),
 ('Wendy Scott',),
 ('Zachary Wilson',),
 ('Emma Wilson',),
 ('Harry Johnson',),
 ('Isabella Walker',),
 ('Kylie Moore',),
 ('Leo Martin',),
 ('Noah Taylor',),
 ('Quinn Moore',),
 ('Sophia Lewis',),
 ('William Scott',),
 ('Yvette Turner',),
 ('David Green',),
 ('Grace Johnson',),
 ('Matthew Davis',),
 ('Quincy Adams',),
 ('Tina Green',),
 ('Vera Adams',)]

In [37]:
# The names and total salary of employees grouped by department.

%%sql
SELECT Department, SUM(Salary) as "Total Salary"
FROM employee
GROUP BY Department;

 * sqlite:///NewDB.sqlite3
Done.

[('Business', 5844000.0),
 ('Content', 1866000.0),
 ('Design', 9105000.0),
 ('Finance', 8022000.0),
 ('HR', 9480000.0),
 ('IT', 14214280.964000002),
 ('Marketing', 12669000.0),
 ('Operations', 10167000.0),
 ('PR', 771000.0),
 ('Product', 7461000.0),
 ('Project', 195000.0),
 ('Research', 1182000.0),
 ('Sales', 7944000.0),
 ('Support', 7575000.0)]

In [38]:
%%sql
SELECT NAME, Salary FROM employee WHERE Department = 'IT' AND SALARY >96000;

 * sqlite:///NewDB.sqlite3
Done.

[('David Miller', 108065.22100000002),
 ('Frank White', 127552.39200000007),
 ('Henry Walker', 138181.75800000006),
 ('Jack Martin', 111608.34300000001),
 ('Mia Thompson', 109836.78200000004),
 ('Noah Roberts', 104522.09900000007),
 ('Samuel Wright', 102750.53800000006),
 ('Brian Nelson', 108065.22100000002),
 ('Daniel Foster', 111608.34300000001),
 ('Harry Alexander', 100978.97700000006),
 ('Keith Ross', 111608.34300000001),
 ('Nina Wallace', 113379.90400000002),
 ('Oscar Daniels', 108065.22100000002),
 ('Quentin Collins', 97435.85500000007),
 ('Steven Hamilton', 111608.34300000001),
 ('Wendy Edwards', 108065.22100000002),
 ('Zachary Foster', 111608.34300000001),
 ('Bob Smith', 145268.0020000001),
 ('Mia Lee', 116923.02600000003),
 ('Sam Parker', 116923.02600000003),
 ('Zachary Long', 124009.27000000005),
 ('Frankie Allen', 118694.58700000004),
 ('Henry Roberts', 122237.70900000005),
 ('Liam Scott', 102750.53800000006),
 ('Tina Bell', 125780.83100000005),
 ('Uma Murphy', 113379.90400000002),
 ('Aiden Green', 102750.53800000006),
 ('George White', 106293.66000000002),
 ('Nora Gonzalez', 106293.66000000002),
 ('Riley Baker', 104522.09900000007),
 ('Ariana Lopez', 104522.09900000007),
 ('Finn Garcia', 120466.14800000003),
 ('Victor White', 104522.09900000007),
 ('Riley Evans', 109836.78200000004),
 ('Ethan White', 111608.34300000001),
 ('Oliver Walker', 108065.22100000002),
 ('Xander Brooks', 109836.78200000004),
 ('Clara Morgan', 106293.66000000002),
 ('Ryan Clark', 106293.66000000002),
 ('Catherine Lopez', 109836.78200000004),
 ('Kelly Young', 108065.22100000002),
 ('Sam Rogers', 111608.34300000001),
 ('Ella King', 113379.90400000002),
 ('Sam Adams', 108065.22100000002),
 ('Ryan Clark', 106293.66000000002),
 ('Catherine Lopez', 109836.78200000004),
 ('Kelly Young', 108065.22100000002),
 ('Sam Rogers', 111608.34300000001),
 ('Ella King', 113379.90400000002),
 ('Sam Adams', 108065.22100000002),
 ('Becca Davis', 106293.66000000002),
 ('Oscar Johnson', 109836.78200000004),
 ('Victor Brown', 111608.34300000001),
 ('Quinn Evans', 108065.22100000002),
 ('Catherine Morgan', 113379.90400000002),
 ('William Lewis', 113379.90400000002)]

In [39]:
#  Update the salary of all employees in the 'IT' department by increasing it by 10%.

%%sql
UPDATE employee
SET Salary = Salary * 1.10
WHERE Department = 'IT';

 * sqlite:///NewDB.sqlite3
177 rows affected.

[]

In [40]:
%%sql
SELECT NAME, Salary FROM employee WHERE Department = 'IT' AND SALARY >110000;

 * sqlite:///NewDB.sqlite3
Done.

[('David Miller', 118871.74310000004),
 ('Frank White', 140307.6312000001),
 ('Henry Walker', 151999.9338000001),
 ('Jack Martin', 122769.17730000002),
 ('Mia Thompson', 120820.46020000005),
 ('Noah Roberts', 114974.30890000009),
 ('Samuel Wright', 113025.59180000007),
 ('Brian Nelson', 118871.74310000004),
 ('Daniel Foster', 122769.17730000002),
 ('Harry Alexander', 111076.87470000007),
 ('Keith Ross', 122769.17730000002),
 ('Nina Wallace', 124717.89440000003),
 ('Oscar Daniels', 118871.74310000004),
 ('Steven Hamilton', 122769.17730000002),
 ('Wendy Edwards', 118871.74310000004),
 ('Zachary Foster', 122769.17730000002),
 ('Bob Smith', 159794.80220000012),
 ('Mia Lee', 128615.32860000004),
 ('Sam Parker', 128615.32860000004),
 ('Zachary Long', 136410.19700000007),
 ('Frankie Allen', 130564.04570000006),
 ('Henry Roberts', 134461.47990000006),
 ('Liam Scott', 113025.59180000007),
 ('Tina Bell', 138358.91410000005),
 ('Uma Murphy', 124717.89440000003),
 ('Aiden Green', 113025.59180000007),
 ('George White', 116923.02600000003),
 ('Nora Gonzalez', 116923.02600000003),
 ('Riley Baker', 114974.30890000009),
 ('Ariana Lopez', 114974.30890000009),
 ('Finn Garcia', 132512.76280000005),
 ('Victor White', 114974.30890000009),
 ('Riley Evans', 120820.46020000005),
 ('Ethan White', 122769.17730000002),
 ('Oliver Walker', 118871.74310000004),
 ('Xander Brooks', 120820.46020000005),
 ('Clara Morgan', 116923.02600000003),
 ('Ryan Clark', 116923.02600000003),
 ('Catherine Lopez', 120820.46020000005),
 ('Kelly Young', 118871.74310000004),
 ('Sam Rogers', 122769.17730000002),
 ('Ella King', 124717.89440000003),
 ('Sam Adams', 118871.74310000004),
 ('Ryan Clark', 116923.02600000003),
 ('Catherine Lopez', 120820.46020000005),
 ('Kelly Young', 118871.74310000004),
 ('Sam Rogers', 122769.17730000002),
 ('Ella King', 124717.89440000003),
 ('Sam Adams', 118871.74310000004),
 ('Becca Davis', 116923.02600000003),
 ('Oscar Johnson', 120820.46020000005),
 ('Victor Brown', 122769.17730000002),
 ('Quinn Evans', 118871.74310000004),
 ('Catherine Morgan', 124717.89440000003),
 ('William Lewis', 124717.89440000003)]

In [41]:
#  Names of employees who joined in the year 2017.

%%sql
SELECT Name, strftime('%m', Date_of_Joining) , strftime('%Y', Date_of_Joining)
FROM employee
WHERE strftime('%Y', Date_of_Joining) = '2017'

 * sqlite:///NewDB.sqlite3
Done.

[('Charlie Davis', '09', '2017'),
 ('Isabella Harris', '11', '2017'),
 ('Paul Green', '07', '2017'),
 ('Samuel Wright', '11', '2017'),
 ('Francis Diaz', '04', '2017'),
 ('Mike Griffin', '08', '2017'),
 ('Quentin Collins', '11', '2017'),
 ('Uma Grant', '06', '2017'),
 ('Isabella Clark', '03', '2017'),
 ('Umar Green', '05', '2017'),
 ('Aiden Green', '09', '2017'),
 ('Riley Baker', '07', '2017'),
 ('Vera Long', '01', '2017'),
 ('Ariana Lopez', '06', '2017'),
 ('Kurt Harris', '04', '2017'),
 ('Olivia Campbell', '05', '2017'),
 ('Samantha Wilson', '02', '2017'),
 ('Eva Sanchez', '03', '2017'),
 ('Mia Gray', '02', '2017'),
 ('Nina Price', '01', '2017'),
 ('Parker Reed', '07', '2017'),
 ('Willow Young', '06', '2017'),
 ('Cameron Lee', '04', '2017'),
 ('Fiona Green', '05', '2017'),
 ('Oliver Walker', '04', '2017'),
 ('Ursula Rivera', '01', '2017'),
 ('Zachary Morris', '03', '2017'),
 ('Eva Lewis', '07', '2017'),
 ('Julia Carter', '03', '2017'),
 ('Nina Evans', '03', '2017'),
 ('Ryan Clark', '04', '2017'),
 ('Xander Walker', '03', '2017'),
 ('Ariana Davis', '05', '2017'),
 ('Emily Harris', '08', '2017'),
 ('Kelly Young', '06', '2017'),
 ('Quinn Cooper', '07', '2017'),
 ('Tina Williams', '04', '2017'),
 ('Will Scott', '01', '2017'),
 ('Zane Smith', '08', '2017'),
 ('Grace Turner', '01', '2017'),
 ('Liam Moore', '02', '2017'),
 ('Paul Lewis', '03', '2017'),
 ('Tina Evans', '05', '2017'),
 ('Will Turner', '05', '2017'),
 ('Zane Williams', '06', '2017'),
 ('Nina Evans', '03', '2017'),
 ('Ryan Clark', '04', '2017'),
 ('Xander Walker', '03', '2017'),
 ('Ariana Davis', '05', '2017'),
 ('Emily Harris', '08', '2017'),
 ('Kelly Young', '06', '2017'),
 ('Quinn Cooper', '07', '2017'),
 ('Tina Williams', '04', '2017'),
 ('Will Scott', '01', '2017'),
 ('Zane Smith', '08', '2017'),
 ('Grace Turner', '01', '2017'),
 ('Liam Moore', '02', '2017'),
 ('Paul Lewis', '03', '2017'),
 ('Tina Evans', '05', '2017'),
 ('Will Turner', '05', '2017'),
 ('Zane Williams', '06', '2017'),
 ('Ethan Harris', '02', '2017'),
 ('Jasmine Adams', '06', '2017'),
 ('Quincy Harris', '11', '2017'),
 ('Xander Lee', '01', '2017'),
 ('Zane Walker', '08', '2017'),
 ('Catherine Carter', '03', '2017'),
 ('Ulysses Brown', '01', '2017'),
 ('Carlos Adams', '07', '2017'),
 ('Ian Clark', '06', '2017'),
 ('Ian Reed', '02', '2017'),
 ('Michael Green', '10', '2017'),
 ('Victor Lewis', '09', '2017'),
 ('Zachary Wilson', '11', '2017'),
 ('Leo Martin', '01', '2017'),
 ('Sophia Lewis', '04', '2017'),
 ('Xena Lewis', '07', '2017'),
 ('Catherine Young', '06', '2017'),
 ('Laura Adams', '10', '2017'),
 ('Quincy Adams', '03', '2017'),
 ('Rachel Smith', '01', '2017'),
 ('Tina Green', '10', '2017'),
 ('Yvonne White', '04', '2017'),
 ('Charlie Davis', '09', '2017'),
 ('Isabella Harris', '11', '2017'),
 ('Paul Green', '07', '2017'),
 ('Samuel Wright', '11', '2017'),
 ('Francis Diaz', '04', '2017'),
 ('Mike Griffin', '08', '2017'),
 ('Quentin Collins', '11', '2017'),
 ('Uma Grant', '06', '2017'),
 ('Isabella Clark', '03', '2017'),
 ('Umar Green', '05', '2017'),
 ('Aiden Green', '09', '2017'),
 ('Riley Baker', '07', '2017'),
 ('Vera Long', '01', '2017'),
 ('Ariana Lopez', '06', '2017'),
 ('Kurt Harris', '04', '2017'),
 ('Olivia Campbell', '05', '2017'),
 ('Samantha Wilson', '02', '2017'),
 ('Eva Sanchez', '03', '2017'),
 ('Mia Gray', '02', '2017'),
 ('Nina Price', '01', '2017'),
 ('Parker Reed', '07', '2017'),
 ('Willow Young', '06', '2017'),
 ('Cameron Lee', '04', '2017'),
 ('Fiona Green', '05', '2017'),
 ('Oliver Walker', '04', '2017'),
 ('Ursula Rivera', '01', '2017'),
 ('Zachary Morris', '03', '2017'),
 ('Eva Lewis', '07', '2017'),
 ('Julia Carter', '03', '2017'),
 ('Nina Evans', '03', '2017'),
 ('Ryan Clark', '04', '2017'),
 ('Xander Walker', '03', '2017'),
 ('Ariana Davis', '05', '2017'),
 ('Emily Harris', '08', '2017'),
 ('Kelly Young', '06', '2017'),
 ('Quinn Cooper', '07', '2017'),
 ('Tina Williams', '04', '2017'),
 ('Will Scott', '01', '2017'),
 ('Zane Smith', '08', '2017'),
 ('Grace Turner', '01', '2017'),
 ('Liam Moore', '02', '2017'),
 ('Paul Lewis', '03', '2017'),
 ('Tina Evans', '05', '2017'),
 ('Will Turner', '05', '2017'),
 ('Zane Williams', '06', '2017'),
 ('Nina Evans', '03', '2017'),
 ('Ryan Clark', '04', '2017'),
 ('Xander Walker', '03', '2017'),
 ('Ariana Davis', '05', '2017'),
 ('Emily Harris', '08', '2017'),
 ('Kelly Young', '06', '2017'),
 ('Quinn Cooper', '07', '2017'),
 ('Tina Williams', '04', '2017'),
 ('Will Scott', '01', '2017'),
 ('Zane Smith', '08', '2017'),
 ('Grace Turner', '01', '2017'),
 ('Liam Moore', '02', '2017'),
 ('Paul Lewis', '03', '2017'),
 ('Tina Evans', '05', '2017'),
 ('Will Turner', '05', '2017'),
 ('Zane Williams', '06', '2017'),
 ('Ethan Harris', '02', '2017'),
 ('Jasmine Adams', '06', '2017'),
 ('Quincy Harris', '11', '2017'),
 ('Xander Lee', '01', '2017'),
 ('Zane Walker', '08', '2017'),
 ('Catherine Carter', '03', '2017'),
 ('Ulysses Brown', '01', '2017'),
 ('Carlos Adams', '07', '2017'),
 ('Ian Clark', '06', '2017'),
 ('Ian Reed', '02', '2017'),
 ('Michael Green', '10', '2017'),
 ('Victor Lewis', '09', '2017'),
 ('Zachary Wilson', '11', '2017'),
 ('Leo Martin', '01', '2017'),
 ('Sophia Lewis', '04', '2017'),
 ('Xena Lewis', '07', '2017'),
 ('Catherine Young', '06', '2017'),
 ('Laura Adams', '10', '2017'),
 ('Quincy Adams', '03', '2017'),
 ('Rachel Smith', '01', '2017'),
 ('Tina Green', '10', '2017'),
 ('Yvonne White', '04', '2017'),
 ('Charlie Davis', '09', '2017'),
 ('Isabella Harris', '11', '2017'),
 ('Paul Green', '07', '2017'),
 ('Samuel Wright', '11', '2017'),
 ('Francis Diaz', '04', '2017'),
 ('Mike Griffin', '08', '2017'),
 ('Quentin Collins', '11', '2017'),
 ('Uma Grant', '06', '2017'),
 ('Isabella Clark', '03', '2017'),
 ('Umar Green', '05', '2017'),
 ('Aiden Green', '09', '2017'),
 ('Riley Baker', '07', '2017'),
 ('Vera Long', '01', '2017'),
 ('Ariana Lopez', '06', '2017'),
 ('Kurt Harris', '04', '2017'),
 ('Olivia Campbell', '05', '2017'),
 ('Samantha Wilson', '02', '2017'),
 ('Eva Sanchez', '03', '2017'),
 ('Mia Gray', '02', '2017'),
 ('Nina Price', '01', '2017'),
 ('Parker Reed', '07', '2017'),
 ('Willow Young', '06', '2017'),
 ('Cameron Lee', '04', '2017'),
 ('Fiona Green', '05', '2017'),
 ('Oliver Walker', '04', '2017'),
 ('Ursula Rivera', '01', '2017'),
 ('Zachary Morris', '03', '2017'),
 ('Eva Lewis', '07', '2017'),
 ('Julia Carter', '03', '2017'),
 ('Nina Evans', '03', '2017'),
 ('Ryan Clark', '04', '2017'),
 ('Xander Walker', '03', '2017'),
 ('Ariana Davis', '05', '2017'),
 ('Emily Harris', '08', '2017'),
 ('Kelly Young', '06', '2017'),
 ('Quinn Cooper', '07', '2017'),
 ('Tina Williams', '04', '2017'),
 ('Will Scott', '01', '2017'),
 ('Zane Smith', '08', '2017'),
 ('Grace Turner', '01', '2017'),
 ('Liam Moore', '02', '2017'),
 ('Paul Lewis', '03', '2017'),
 ('Tina Evans', '05', '2017'),
 ('Will Turner', '05', '2017'),
 ('Zane Williams', '06', '2017'),
 ('Nina Evans', '03', '2017'),
 ('Ryan Clark', '04', '2017'),
 ('Xander Walker', '03', '2017'),
 ('Ariana Davis', '05', '2017'),
 ('Emily Harris', '08', '2017'),
 ('Kelly Young', '06', '2017'),
 ('Quinn Cooper', '07', '2017'),
 ('Tina Williams', '04', '2017'),
 ('Will Scott', '01', '2017'),
 ('Zane Smith', '08', '2017'),
 ('Grace Turner', '01', '2017'),
 ('Liam Moore', '02', '2017'),
 ('Paul Lewis', '03', '2017'),
 ('Tina Evans', '05', '2017'),
 ('Will Turner', '05', '2017'),
 ('Zane Williams', '06', '2017'),
 ('Ethan Harris', '02', '2017'),
 ('Jasmine Adams', '06', '2017'),
 ('Quincy Harris', '11', '2017'),
 ('Xander Lee', '01', '2017'),
 ('Zane Walker', '08', '2017'),
 ('Catherine Carter', '03', '2017'),
 ('Ulysses Brown', '01', '2017'),
 ('Carlos Adams', '07', '2017'),
 ('Ian Clark', '06', '2017'),
 ('Ian Reed', '02', '2017'),
 ('Michael Green', '10', '2017'),
 ('Victor Lewis', '09', '2017'),
 ('Zachary Wilson', '11', '2017'),
 ('Leo Martin', '01', '2017'),
 ('Sophia Lewis', '04', '2017'),
 ('Xena Lewis', '07', '2017'),
 ('Catherine Young', '06', '2017'),
 ('Laura Adams', '10', '2017'),
 ('Quincy Adams', '03', '2017'),
 ('Rachel Smith', '01', '2017'),
 ('Tina Green', '10', '2017'),
 ('Yvonne White', '04', '2017')]

In [42]:
%%sql
SELECT Name, Performance_Rating  FROM EMPLOYEE WHERE Department = 'Sales';

 * sqlite:///NewDB.sqlite3
Done.

[('Uma Baker', 3.3),
 ('Uma Grant', 2.7),
 ('David Brown', 3.0999999999999996),
 ('Olivia Scott', 2.9000000000000004),
 ('Yvonne Campbell', 2.8),
 ('Isabelle Turner', 2.9000000000000004),
 ('Quinn Howard', 2.9000000000000004),
 ('Zane Cooper', 3.0999999999999996),
 ('Ian Martinez', 3.0999999999999996),
 ('Tyler Martinez', 3.0999999999999996),
 ('Paul Collins', 3.0999999999999996),
 ('Charlotte Murphy', 2.9000000000000004),
 ('Sophia Knight', 2.8),
 ('Bella Martinez', 2.8),
 ('Michael Lopez', 2.8),
 ('Zachary Miller', 2.9000000000000004),
 ('Ivy Wright', 2.9000000000000004),
 ('David Lee', 3.0),
 ('Katherine Thompson', 2.7),
 ('Vera Lee', 2.8),
 ('Zachary Miller', 2.9000000000000004),
 ('Ivy Wright', 2.9000000000000004),
 ('David Lee', 3.0),
 ('Katherine Thompson', 2.7),
 ('Vera Lee', 2.8),
 ('Fiona Clark', 2.8),
 ('Riley Carter', 2.8),
 ('Yara Adams', 2.9000000000000004),
 ('Ivy Robinson', 2.9000000000000004),
 ('Paul Davis', 2.8),
 ('Aiden Martinez', 2.7),
 ('Fiona Turner', 2.5999999999999996),
 ('Brianna Scott', 2.5999999999999996),
 ('Ian Reed', 2.5999999999999996),
 ('Quincy Clark', 2.9000000000000004),
 ('Xander Roberts', 3.0999999999999996),
 ('Franklin Adams', 2.9000000000000004),
 ('Riley Adams', 2.7),
 ('Xena Lewis', 2.7),
 ('Eva White', 2.8),
 ('Ulysses Wright', 2.8),
 ('Yvonne White', 2.7),
 ('Uma Baker', 4.3),
 ('Uma Grant', 3.7),
 ('David Brown', 4.1),
 ('Olivia Scott', 3.9000000000000004),
 ('Yvonne Campbell', 3.8),
 ('Isabelle Turner', 3.9000000000000004),
 ('Quinn Howard', 3.9000000000000004),
 ('Zane Cooper', 4.1),
 ('Ian Martinez', 4.1),
 ('Tyler Martinez', 4.1),
 ('Paul Collins', 4.1),
 ('Charlotte Murphy', 3.9000000000000004),
 ('Sophia Knight', 3.8),
 ('Bella Martinez', 3.8),
 ('Michael Lopez', 3.8),
 ('Zachary Miller', 3.9000000000000004),
 ('Ivy Wright', 3.9000000000000004),
 ('David Lee', 4.0),
 ('Katherine Thompson', 3.7),
 ('Vera Lee', 3.8),
 ('Zachary Miller', 3.9000000000000004),
 ('Ivy Wright', 3.9000000000000004),
 ('David Lee', 4.0),
 ('Katherine Thompson', 3.7),
 ('Vera Lee', 3.8),
 ('Fiona Clark', 3.8),
 ('Riley Carter', 3.8),
 ('Yara Adams', 3.9000000000000004),
 ('Ivy Robinson', 3.9000000000000004),
 ('Paul Davis', 3.8),
 ('Aiden Martinez', 3.7),
 ('Fiona Turner', 3.5999999999999996),
 ('Brianna Scott', 3.5999999999999996),
 ('Ian Reed', 3.5999999999999996),
 ('Quincy Clark', 3.9000000000000004),
 ('Xander Roberts', 4.1),
 ('Franklin Adams', 3.9000000000000004),
 ('Riley Adams', 3.7),
 ('Xena Lewis', 3.7),
 ('Eva White', 3.8),
 ('Ulysses Wright', 3.8),
 ('Yvonne White', 3.7),
 ('Uma Baker', 4.8),
 ('Uma Grant', 4.2),
 ('David Brown', 4.6),
 ('Olivia Scott', 4.4),
 ('Yvonne Campbell', 4.3),
 ('Isabelle Turner', 4.4),
 ('Quinn Howard', 4.4),
 ('Zane Cooper', 4.6),
 ('Ian Martinez', 4.6),
 ('Tyler Martinez', 4.6),
 ('Paul Collins', 4.6),
 ('Charlotte Murphy', 4.4),
 ('Sophia Knight', 4.3),
 ('Bella Martinez', 4.3),
 ('Michael Lopez', 4.3),
 ('Zachary Miller', 4.4),
 ('Ivy Wright', 4.4),
 ('David Lee', 4.5),
 ('Katherine Thompson', 4.2),
 ('Vera Lee', 4.3),
 ('Zachary Miller', 4.4),
 ('Ivy Wright', 4.4),
 ('David Lee', 4.5),
 ('Katherine Thompson', 4.2),
 ('Vera Lee', 4.3),
 ('Fiona Clark', 4.3),
 ('Riley Carter', 4.3),
 ('Yara Adams', 4.4),
 ('Ivy Robinson', 4.4),
 ('Paul Davis', 4.3),
 ('Aiden Martinez', 4.2),
 ('Fiona Turner', 4.1),
 ('Brianna Scott', 4.1),
 ('Ian Reed', 4.1),
 ('Quincy Clark', 4.4),
 ('Xander Roberts', 4.6),
 ('Franklin Adams', 4.4),
 ('Riley Adams', 4.2),
 ('Xena Lewis', 4.2),
 ('Eva White', 4.3),
 ('Ulysses Wright', 4.3),
 ('Yvonne White', 4.2)]

In [43]:
# Update the performance rating of all employees in the 'Sales' department by decreasing it by 0.5.

%%sql
UPDATE employee
SET Performance_Rating = Performance_Rating - 0.5
WHERE Department = 'Sales';

 * sqlite:///NewDB.sqlite3
126 rows affected.

[]

In [44]:
%%sql
SELECT Name, Performance_Rating  FROM EMPLOYEE WHERE Department = 'Sales';

 * sqlite:///NewDB.sqlite3
Done.

[('Uma Baker', 2.8),
 ('Uma Grant', 2.2),
 ('David Brown', 2.5999999999999996),
 ('Olivia Scott', 2.4000000000000004),
 ('Yvonne Campbell', 2.3),
 ('Isabelle Turner', 2.4000000000000004),
 ('Quinn Howard', 2.4000000000000004),
 ('Zane Cooper', 2.5999999999999996),
 ('Ian Martinez', 2.5999999999999996),
 ('Tyler Martinez', 2.5999999999999996),
 ('Paul Collins', 2.5999999999999996),
 ('Charlotte Murphy', 2.4000000000000004),
 ('Sophia Knight', 2.3),
 ('Bella Martinez', 2.3),
 ('Michael Lopez', 2.3),
 ('Zachary Miller', 2.4000000000000004),
 ('Ivy Wright', 2.4000000000000004),
 ('David Lee', 2.5),
 ('Katherine Thompson', 2.2),
 ('Vera Lee', 2.3),
 ('Zachary Miller', 2.4000000000000004),
 ('Ivy Wright', 2.4000000000000004),
 ('David Lee', 2.5),
 ('Katherine Thompson', 2.2),
 ('Vera Lee', 2.3),
 ('Fiona Clark', 2.3),
 ('Riley Carter', 2.3),
 ('Yara Adams', 2.4000000000000004),
 ('Ivy Robinson', 2.4000000000000004),
 ('Paul Davis', 2.3),
 ('Aiden Martinez', 2.2),
 ('Fiona Turner', 2.0999999999999996),
 ('Brianna Scott', 2.0999999999999996),
 ('Ian Reed', 2.0999999999999996),
 ('Quincy Clark', 2.4000000000000004),
 ('Xander Roberts', 2.5999999999999996),
 ('Franklin Adams', 2.4000000000000004),
 ('Riley Adams', 2.2),
 ('Xena Lewis', 2.2),
 ('Eva White', 2.3),
 ('Ulysses Wright', 2.3),
 ('Yvonne White', 2.2),
 ('Uma Baker', 3.8),
 ('Uma Grant', 3.2),
 ('David Brown', 3.5999999999999996),
 ('Olivia Scott', 3.4000000000000004),
 ('Yvonne Campbell', 3.3),
 ('Isabelle Turner', 3.4000000000000004),
 ('Quinn Howard', 3.4000000000000004),
 ('Zane Cooper', 3.5999999999999996),
 ('Ian Martinez', 3.5999999999999996),
 ('Tyler Martinez', 3.5999999999999996),
 ('Paul Collins', 3.5999999999999996),
 ('Charlotte Murphy', 3.4000000000000004),
 ('Sophia Knight', 3.3),
 ('Bella Martinez', 3.3),
 ('Michael Lopez', 3.3),
 ('Zachary Miller', 3.4000000000000004),
 ('Ivy Wright', 3.4000000000000004),
 ('David Lee', 3.5),
 ('Katherine Thompson', 3.2),
 ('Vera Lee', 3.3),
 ('Zachary Miller', 3.4000000000000004),
 ('Ivy Wright', 3.4000000000000004),
 ('David Lee', 3.5),
 ('Katherine Thompson', 3.2),
 ('Vera Lee', 3.3),
 ('Fiona Clark', 3.3),
 ('Riley Carter', 3.3),
 ('Yara Adams', 3.4000000000000004),
 ('Ivy Robinson', 3.4000000000000004),
 ('Paul Davis', 3.3),
 ('Aiden Martinez', 3.2),
 ('Fiona Turner', 3.0999999999999996),
 ('Brianna Scott', 3.0999999999999996),
 ('Ian Reed', 3.0999999999999996),
 ('Quincy Clark', 3.4000000000000004),
 ('Xander Roberts', 3.5999999999999996),
 ('Franklin Adams', 3.4000000000000004),
 ('Riley Adams', 3.2),
 ('Xena Lewis', 3.2),
 ('Eva White', 3.3),
 ('Ulysses Wright', 3.3),
 ('Yvonne White', 3.2),
 ('Uma Baker', 4.3),
 ('Uma Grant', 3.7),
 ('David Brown', 4.1),
 ('Olivia Scott', 3.9000000000000004),
 ('Yvonne Campbell', 3.8),
 ('Isabelle Turner', 3.9000000000000004),
 ('Quinn Howard', 3.9000000000000004),
 ('Zane Cooper', 4.1),
 ('Ian Martinez', 4.1),
 ('Tyler Martinez', 4.1),
 ('Paul Collins', 4.1),
 ('Charlotte Murphy', 3.9000000000000004),
 ('Sophia Knight', 3.8),
 ('Bella Martinez', 3.8),
 ('Michael Lopez', 3.8),
 ('Zachary Miller', 3.9000000000000004),
 ('Ivy Wright', 3.9000000000000004),
 ('David Lee', 4.0),
 ('Katherine Thompson', 3.7),
 ('Vera Lee', 3.8),
 ('Zachary Miller', 3.9000000000000004),
 ('Ivy Wright', 3.9000000000000004),
 ('David Lee', 4.0),
 ('Katherine Thompson', 3.7),
 ('Vera Lee', 3.8),
 ('Fiona Clark', 3.8),
 ('Riley Carter', 3.8),
 ('Yara Adams', 3.9000000000000004),
 ('Ivy Robinson', 3.9000000000000004),
 ('Paul Davis', 3.8),
 ('Aiden Martinez', 3.7),
 ('Fiona Turner', 3.5999999999999996),
 ('Brianna Scott', 3.5999999999999996),
 ('Ian Reed', 3.5999999999999996),
 ('Quincy Clark', 3.9000000000000004),
 ('Xander Roberts', 4.1),
 ('Franklin Adams', 3.9000000000000004),
 ('Riley Adams', 3.7),
 ('Xena Lewis', 3.7),
 ('Eva White', 3.8),
 ('Ulysses Wright', 3.8),
 ('Yvonne White', 3.7)]

In [45]:
#Details of employees who joined in the last 6 years.

%%sql
SELECT *
FROM employee
WHERE Date_of_Joining >= date('now', '-6 years');

 * sqlite:///NewDB.sqlite3
Done.

[(9, 'Grace Lee', 26, '456 Birch St', 54000.0, 'Content Writer', 'Marketing', '2019-03-22', 2, 13, 4.0, 4.1, 0, 1),
 (357, 'Becca Davis', 29, '456 Birch St', 116923.02600000003, 'IT Specialist', 'IT', '2018-09-10', 2, 12, 4.1, 4.2, 0, 1),
 (374, 'Sophie Turner', 28, '123 Elm St', 60000.0, 'Finance Specialist', 'Finance', '2019-01-15', 1, 10, 4.1, 4.2, 0, 1),
 (398, 'Quinn Evans', 28, '123 Pine St', 118871.74310000004, 'IT Specialist', 'IT', '2019-01-15', 1, 12, 4.0, 4.1, 0, 1),
 (408, 'Aiden Martinez', 29, '456 Maple St', 60000.0, 'Sales Specialist', 'Sales', '2018-11-10', 2, 12, 2.2, 4.3, 0, 2),
 (423, 'Fiona Bell', 28, '789 Maple St', 61000.0, 'Design Specialist', 'Design', '2019-01-15', 1, 12, 4.0, 4.1, 0, 1),
 (433, 'Paige Turner', 29, '123 Elm St', 60000.0, 'Operations Coordinator', 'Operations', '2019-03-10', 1, 12, 4.1, 4.2, 0, 1),
 (452, 'Isabella Walker', 28, '456 Maple St', 60000.0, 'Operations Coordinator', 'Operations', '2019-02-15', 1, 12, 4.0, 4.1, 0, 1),
 (460, 'Quinn Moore', 29, '123 Birch St', 60000.0, 'Operations Specialist', 'Operations', '2019-01-15', 1, 12, 4.0, 4.1, 0, 1),
 (468, 'Yvette Turner', 29, '789 Maple St', 61000.0, 'HR Specialist', 'HR', '2018-09-15', 2, 11, 4.1, 4.2, 0, 1),
 (476, 'Grace Johnson', 29, '456 Birch St', 62000.0, 'Marketing Specialist', 'Marketing', '2018-11-10', 2, 12, 4.0, 4.1, 0, 1),
 (484, 'Oscar Wilson', 29, '123 Oak St', 61000.0, 'Customer Service Coordinator', 'Support', '2019-03-20', 1, 10, 4.0, 4.1, 0, 1),
 (491, 'Vera Adams', 29, '456 Birch St', 61000.0, 'Customer Service Specialist', 'Support', '2018-12-15', 2, 12, 4.0, 4.1, 0, 1),
 (496, 'John David', 30, None, 72600.0, 'Software Engineer', 'IT', '2023-05-08', None, 5, 4.0, None, 0, None),
 (497, 'Aiden Lee', 29, '123 Maple St', 72600.0, 'Software Engineer', 'IT', '2019-08-20', 3, 8, 4.3, 4.4, 1, 3),
 (498, 'Olivia Adams', 27, '789 Elm St', 71390.00000000001, 'Data Analyst', 'IT', '2020-02-15', 2, 7, 4.2, 4.3, 0, 2),
 (507, 'Grace Lee', 26, '456 Birch St', 54000.0, 'Content Writer', 'Marketing', '2019-03-22', 2, 13, 4.0, 4.1, 0, 1),
 (855, 'Becca Davis', 29, '456 Birch St', 72600.0, 'IT Specialist', 'IT', '2018-09-10', 2, 12, 4.1, 4.2, 0, 1),
 (872, 'Sophie Turner', 28, '123 Elm St', 60000.0, 'Finance Specialist', 'Finance', '2019-01-15', 1, 10, 4.1, 4.2, 0, 1),
 (896, 'Quinn Evans', 28, '123 Pine St', 73810.0, 'IT Specialist', 'IT', '2019-01-15', 1, 12, 4.0, 4.1, 0, 1),
 (906, 'Aiden Martinez', 29, '456 Maple St', 60000.0, 'Sales Specialist', 'Sales', '2018-11-10', 2, 12, 3.2, 4.3, 0, 2),
 (921, 'Fiona Bell', 28, '789 Maple St', 61000.0, 'Design Specialist', 'Design', '2019-01-15', 1, 12, 4.0, 4.1, 0, 1),
 (931, 'Paige Turner', 29, '123 Elm St', 60000.0, 'Operations Coordinator', 'Operations', '2019-03-10', 1, 12, 4.1, 4.2, 0, 1),
 (950, 'Isabella Walker', 28, '456 Maple St', 60000.0, 'Operations Coordinator', 'Operations', '2019-02-15', 1, 12, 4.0, 4.1, 0, 1),
 (958, 'Quinn Moore', 29, '123 Birch St', 60000.0, 'Operations Specialist', 'Operations', '2019-01-15', 1, 12, 4.0, 4.1, 0, 1),
 (966, 'Yvette Turner', 29, '789 Maple St', 61000.0, 'HR Specialist', 'HR', '2018-09-15', 2, 11, 4.1, 4.2, 0, 1),
 (974, 'Grace Johnson', 29, '456 Birch St', 62000.0, 'Marketing Specialist', 'Marketing', '2018-11-10', 2, 12, 4.0, 4.1, 0, 1),
 (982, 'Oscar Wilson', 29, '123 Oak St', 61000.0, 'Customer Service Coordinator', 'Support', '2019-03-20', 1, 10, 4.0, 4.1, 0, 1),
 (989, 'Vera Adams', 29, '456 Birch St', 61000.0, 'Customer Service Specialist', 'Support', '2018-12-15', 2, 12, 4.0, 4.1, 0, 1),
 (994, 'John David', 30, None, 66000.0, 'Software Engineer', 'IT', '2023-05-08', None, 5, 4.0, None, 0, None),
 (995, 'Aiden Lee', 29, '123 Maple St', 66000.0, 'Software Engineer', 'IT', '2019-08-20', 3, 8, 4.3, 4.4, 1, 3),
 (996, 'Olivia Adams', 27, '789 Elm St', 64900.00000000001, 'Data Analyst', 'IT', '2020-02-15', 2, 7, 4.2, 4.3, 0, 2),
 (1005, 'Grace Lee', 26, '456 Birch St', 54000.0, 'Content Writer', 'Marketing', '2019-03-22', 2, 13, 4.0, 4.1, 0, 1),
 (1353, 'Becca Davis', 29, '456 Birch St', 66000.0, 'IT Specialist', 'IT', '2018-09-10', 2, 12, 4.1, 4.2, 0, 1),
 (1370, 'Sophie Turner', 28, '123 Elm St', 60000.0, 'Finance Specialist', 'Finance', '2019-01-15', 1, 10, 4.1, 4.2, 0, 1),
 (1394, 'Quinn Evans', 28, '123 Pine St', 67100.0, 'IT Specialist', 'IT', '2019-01-15', 1, 12, 4.0, 4.1, 0, 1),
 (1404, 'Aiden Martinez', 29, '456 Maple St', 60000.0, 'Sales Specialist', 'Sales', '2018-11-10', 2, 12, 3.7, 4.3, 0, 2),
 (1419, 'Fiona Bell', 28, '789 Maple St', 61000.0, 'Design Specialist', 'Design', '2019-01-15', 1, 12, 4.0, 4.1, 0, 1),
 (1429, 'Paige Turner', 29, '123 Elm St', 60000.0, 'Operations Coordinator', 'Operations', '2019-03-10', 1, 12, 4.1, 4.2, 0, 1),
 (1448, 'Isabella Walker', 28, '456 Maple St', 60000.0, 'Operations Coordinator', 'Operations', '2019-02-15', 1, 12, 4.0, 4.1, 0, 1),
 (1456, 'Quinn Moore', 29, '123 Birch St', 60000.0, 'Operations Specialist', 'Operations', '2019-01-15', 1, 12, 4.0, 4.1, 0, 1),
 (1464, 'Yvette Turner', 29, '789 Maple St', 61000.0, 'HR Specialist', 'HR', '2018-09-15', 2, 11, 4.1, 4.2, 0, 1),
 (1472, 'Grace Johnson', 29, '456 Birch St', 62000.0, 'Marketing Specialist', 'Marketing', '2018-11-10', 2, 12, 4.0, 4.1, 0, 1),
 (1480, 'Oscar Wilson', 29, '123 Oak St', 61000.0, 'Customer Service Coordinator', 'Support', '2019-03-20', 1, 10, 4.0, 4.1, 0, 1),
 (1487, 'Vera Adams', 29, '456 Birch St', 61000.0, 'Customer Service Specialist', 'Support', '2018-12-15', 2, 12, 4.0, 4.1, 0, 1)]

In [46]:
# Insert an employee with null Address.

%%sql
INSERT INTO employee (Name, Age, Address, Department, Salary, Date_of_Joining, Position, Number_of_Promotions, Performance_Rating, Number_of_Leaves)
VALUES ('John David', 30, NULL, 'IT', 60000, '2023-05-08', 'Software Engineer', 0, 4.0, 5);

 * sqlite:///NewDB.sqlite3
1 rows affected.

[]

In [47]:
# Display details of John David'

%%sql
SELECT * FROM employee WHERE Name = 'John David';

 * sqlite:///NewDB.sqlite3
Done.

[(496, 'John David', 30, None, 72600.0, 'Software Engineer', 'IT', '2023-05-08', None, 5, 4.0, None, 0, None),
 (994, 'John David', 30, None, 66000.0, 'Software Engineer', 'IT', '2023-05-08', None, 5, 4.0, None, 0, None),
 (1492, 'John David', 30, None, 60000.0, 'Software Engineer', 'IT', '2023-05-08', None, 5, 4.0, None, 0, None)]

In [48]:
#Insert Multiple values
%%sql
INSERT INTO employee (Name, Age, Address, Salary, Position, Department, Date_of_Joining, Experience_Years, Number_of_Leaves, Performance_Rating, Employee_Satisfaction, Number_of_Promotions, Number_of_Projects_Working)
VALUES ('Aiden Lee', 29, '123 Maple St', 60000.0, 'Software Engineer', 'IT', '2019-08-20', 3, 8, 4.3, 4.4, 1, 3),
       ('Olivia Adams', 27, '789 Elm St', 59000.0, 'Data Analyst', 'IT', '2020-02-15', 2, 7, 4.2, 4.3, 0, 2);

 * sqlite:///NewDB.sqlite3
2 rows affected.

[]

In [49]:
# Find the total number of employees in each position.

%%sql
SELECT Position, COUNT(*) AS "Number of Employees"
FROM employee
GROUP BY Position;

 * sqlite:///NewDB.sqlite3
Done.

[('Account Manager', 3),
 ('Accountant', 6),
 ('Backend Developer', 3),
 ('Brand Manager', 3),
 ('Business Analyst', 45),
 ('Business Consultant', 3),
 ('Business Development', 3),
 ('Business Development Manager', 12),
 ('Business Development Specialist', 15),
 ('Compliance Officer', 3),
 ('Content Analyst', 3),
 ('Content Coordinator', 3),
 ('Content Creator', 3),
 ('Content Developer', 3),
 ('Content Manager', 9),
 ('Content Specialist', 3),
 ('Content Strategist', 9),
 ('Content Writer', 6),
 ('Copywriter', 3),
 ('Customer Service Coordinator', 15),
 ('Customer Service Manager', 33),
 ('Customer Service Representative', 3),
 ('Customer Service Specialist', 57),
 ('Customer Success Manager', 6),
 ('Customer Support', 3),
 ('Data Analyst', 12),
 ('Data Engineer', 3),
 ('Data Scientist', 9),
 ('Database Administrator', 3),
 ('Design Coordinator', 33),
 ('Design Lead', 6),
 ('Design Manager', 27),
 ('Design Specialist', 60),
 ('DevOps Engineer', 3),
 ('Digital Marketing Specialist', 3),
 ('Event Planner', 3),
 ('Finance Analyst', 39),
 ('Finance Coordinator', 24),
 ('Finance Manager', 27),
 ('Finance Specialist', 18),
 ('Financial Advisor', 3),
 ('Financial Analyst', 3),
 ('Financial Planner', 3),
 ('Front-end Developer', 3),
 ('Graphic Designer', 6),
 ('HR Consultant', 3),
 ('HR Coordinator', 39),
 ('HR Director', 6),
 ('HR Generalist', 3),
 ('HR Manager', 27),
 ('HR Specialist', 72),
 ('IT Administrator', 3),
 ('IT Analyst', 3),
 ('IT Coordinator', 24),
 ('IT Manager', 9),
 ('IT Project Manager', 6),
 ('IT Specialist', 42),
 ('IT Support', 3),
 ('IT Support Specialist', 6),
 ('Junior Developer', 3),
 ('Logistics Coordinator', 3),
 ('Logistics Manager', 3),
 ('Marketing Analyst', 12),
 ('Marketing Assistant', 6),
 ('Marketing Coordinator', 33),
 ('Marketing Director', 6),
 ('Marketing Lead', 3),
 ('Marketing Manager', 36),
 ('Marketing Specialist', 72),
 ('Network Administrator', 3),
 ('Network Engineer', 3),
 ('Operations Analyst', 9),
 ('Operations Assistant', 3),
 ('Operations Coordinator', 39),
 ('Operations Director', 3),
 ('Operations Manager', 42),
 ('Operations Specialist', 45),
 ('Operations Supervisor', 3),
 ('Product Analyst', 3),
 ('Product Coordinator', 3),
 ('Product Designer', 6),
 ('Product Manager', 69),
 ('Product Specialist', 54),
 ('Project Coordinator', 3),
 ('Project Manager', 6),
 ('Public Relations Coordinator', 3),
 ('Public Relations Manager', 6),
 ('Public Relations Specialist', 6),
 ('QA Engineer', 3),
 ('Research Analyst', 9),
 ('Research Coordinator', 3),
 ('Research Scientist', 3),
 ('Research Specialist', 3),
 ('SEO Specialist', 9),
 ('Sales Analyst', 3),
 ('Sales Consultant', 3),
 ('Sales Coordinator', 36),
 ('Sales Director', 3),
 ('Sales Executive', 3),
 ('Sales Manager', 42),
 ('Sales Representative', 3),
 ('Sales Specialist', 30),
 ('Sales Trainer', 3),
 ('Social Media Manager', 3),
 ('Software Developer', 3),
 ('Software Engineer', 12),
 ('Supply Chain Manager', 3),
 ('Support Engineer', 3),
 ('System Administrator', 3),
 ('Systems Analyst', 3),
 ('Systems Engineer', 3),
 ('Technical Support', 3),
 ('Technical Support Engineer', 3),
 ('Technical Writer', 6),
 ('UX Designer', 6),
 ('UX Researcher', 3),
 ('Web Developer', 6)]

In [50]:
# Retrieve the maximum salary in each department.

%%sql
SELECT Department, MAX(Salary) AS "Maximum Salary"
FROM employee
GROUP BY Department;

 * sqlite:///NewDB.sqlite3
Done.

[('Business', 76000.0),
 ('Content', 68000.0),
 ('Design', 67000.0),
 ('Finance', 85000.0),
 ('HR', 80000.0),
 ('IT', 159794.80220000012),
 ('Marketing', 74000.0),
 ('Operations', 77000.0),
 ('PR', 68000.0),
 ('Product', 65000.0),
 ('Project', 65000.0),
 ('Research', 67000.0),
 ('Sales', 75000.0),
 ('Support', 67000.0)]